.github/dependabot.yml
> This change will allow Dependabot to contribute package updates to this repo in the form of PRs …
=> Allow Dependabot to make automatic PRs to upgrade packages

.github/workflows/codeql-analysis.yml
Self explanatory -- largely based off of both what we already have in recidiviz-data and the template that GH proposes.
| …
=> Add CodeQL scanning for Javascript files

publisher/src/components/Reports/DataEntryForm.tsx
Fixes disaggregations for multi-system agencies -- currently, it displays one system's disaggregations for all systems.
Example (agency reporting for the Supervision & Prison systems):
This should show the disaggregations for Parole and not Prisons:
Corrected:
Closes #15207
=> [Frontend][Bug] Data Entry Form: Disaggregations Bug For Multi-System Agencies

.github/workflows/ci.yml
Adds frontend tests to our GitHub Actions workflow.
Closes #3
=> [Frontend] Add Frontend Tests to CI

publisher/package.json
`yarn lint` will now error if there are any lint warnings, enforcing us to make sure we don't leave any warnings in our code. …
=> [Frontend] Enforce no lint warnings

publisher/src/components/DataUpload/InstructionsTemplate.tsx
On a call with our alpha partners, we received feedback that our template spreadsheets were unclear. The users thought they had to fill these spreadsheets in, which is not the case. I'm updating some terminology here to make this clearer. 
| Type: Feature …
=> Rename "template" spreadsheets to "example" spreadsheets

README.md, publisher/src/App.tsx, publisher/src/components/DataViz/utils.ts, publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx, publisher/src/shared/types.ts, publisher/src/stores/DatapointsStore.ts
Implement logic to transform an array of Datapoints into a table, display Review Metrics page with incomplete styling (to be finalized in a follow-up PR).
For now, I am hydrating the data from the Datapoints API. In a follow-up, we will get the Datapoints from the Data Upload API instead.
To see this page, visit http://localhost:3000/review_metrics
NOTE:
- The display order of the metrics, disaggregations, and dimensions are different than the metric config or data entry page. We are discussing ways of maintaining the same order: https://recidiviz.slack.com/archives/C02VDN1LSSW/p1663097034150579
| Label                       	| Description …
=> [Frontend] Logic to transform array of Datapoints into a table, display Review Metrics page with basic styling

README.md, publisher/README.md
Self explanatory, just updating some copy. Also working on corresponding updates to the backend and frontend READMEs in recidiviz-data. …
=> Small adjustments to the READMEs

publisher/src/components/DataUpload/DataUpload.tsx, publisher/src/components/DataUpload/UploadErrorsWarnings.tsx, publisher/src/components/DataUpload/types.ts, publisher/src/components/DataViz/utils.ts, publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Display the uploaded metrics in the Review Metrics page.
A couple glaring TODOs that I am fixing on this PR, will update screenshots once fixed: …
=> [Frontend] Connect Review Metrics page with Data Upload API

publisher/src/components/DataUpload/types.ts, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx, publisher/src/shared/types.ts, publisher/src/utils/helperUtils.ts
Update RawDatapoint type and fix positive number to expect number input
Fixes issue "Navigating between Review page and Metrics page causes page to go blank with Uncaught TypeError (see stack trace below)" in https://paper.dropbox.com/doc/Bulk-Upload-v1-Playtesting--Bpj93zpAofJZ4F8dz2w82EBZAg-V5Y7JaZYdYAf169SL97QP …
=> [Frontend] Update RawDatapoint type and fix positive number to expect number input

publisher/src/components/DataUpload/DataUpload.styles.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
New table style with borders to make it clear that there is horizontal content
Fix vertical spacing of dimension names being off from the table of metrics
Add gradient on left and right edges of tables if there is content on the left or right you can scroll to see
| …
=> [Frontend][Review Metrics] New table style to convey horizontal content

publisher/src/stores/UserStore.ts
This PR updates updateOnboardingStatus function call to `api/users` with `PATCH` to correctly update the user.
=> [Justice Counts] change updateOnboardingStatus from PUT to PATCH

publisher/src/components/DataUpload/UploadErrorsWarnings.tsx, publisher/src/pages/AccountSettings.tsx, publisher/src/setupProxy.js
Adds autosave to Settings page and removes the 'Save' button.
Demo:
https://user-images.githubusercontent.com/59492998/192394219-ecd7c1f8-cff8-4961-b914-79bcb9231630.mov
Closes #43
=> Add autosave to Settings page

publisher/src/components/DataUpload/DataUpload.styles.tsx, publisher/src/components/DataUpload/DataUpload.tsx, publisher/src/components/DataUpload/UploadErrorsWarnings.tsx, publisher/src/components/DataUpload/types.ts, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Refactors the Data Upload Error/Warning/Success page to the updated API found here: https://github.com/Recidiviz/recidiviz-data/pull/15642
Demo:
https://user-images.githubusercontent.com/59492998/193101409-5898de9f-16df-41bc-a677-f2fa225eebda.mov
https://user-images.githubusercontent.com/59492998/193101562-1ae0439e-6159-416a-ad48-5d9f47e02ce7.mov
Closes #46 
=> Data Upload: Refactor Error/Warning/Success Page

publisher/src/setupProxy.js
add missing copyright header
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not …
=> add missing copyright header

publisher/.eslintrc.js, publisher/license-header.js, publisher/package.json, publisher/src/setupTests.ts, publisher/yarn.lock
Enforce Recidiviz copyright header using Eslint plugin …
=> Enforce Recidiviz copyright header

publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
Probably not worth an entire PR but ¯\\_(ツ)_/¯ …
=> Fix period in title

.github/workflows/ci.yml, common/babel.config.js, common/jest.config.js, common/package.json, common/setupTests.ts, common/tsconfig.json, yarn.lock
- Install Jest and run jest tests in common directory
- Run these tests on CI …
=> Install Jest and run jest tests in common directory & run tests on CI

agency-dashboard/src/stores/RootStore.ts, agency-dashboard/src/stores/index.ts, common/package.json, common/stores/BaseDatapointsStore.ts, publisher/src/stores/DatapointsStore.ts
Create a new BaseDatapointsStore class that is implemented by both the Publisher and Agency Dashboard. Each app overrides the BaseDatapointsStore with their own fetch method.
This allows us to share code between the two apps. 
Note that although mobx allows subclassing, they recommend to use composition over inheritance. Perhaps composition could be achieved by passing in the fetch method and the userStore and setting up the disposers somehow?
|-----------------------------	|------------------------------------------------------------------------- …
=> [Frontend] Implement BaseDatapointsStore class that is shared between our frontend apps

publisher/src/components/MetricConfiguration/Configuration.tsx, publisher/src/components/MetricConfiguration/ContextConfiguration.tsx, publisher/src/components/MetricConfiguration/MetricBox.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.tsx, publisher/src/components/MetricConfiguration/MetricDefinitions.tsx, publisher/src/components/MetricConfiguration/MetricsView.tsx, publisher/src/components/MetricConfiguration/types.ts, publisher/src/components/Settings/SettingsMenu.tsx, publisher/src/pages/Settings.tsx, publisher/src/stores/MetricConfigStore.tsx, publisher/src/stores/RootStore.ts
Introduces mobX store (`MetricConfigStore`) to house and organize metric configuration logic.
Closes #104
=> Metric Configuration Store (1/2)

publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
Updates copy from "Which of the following categories does _**that**_ case management system capture for race?" to "Which of the following categories does **_your_** case management system capture for race?"
Contributes to #180 
=> Race & Ethnicities (Playtesting Followup): Copy Update

publisher/src/components/MetricConfiguration/Configuration.tsx, publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx, publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
Allows the above callout box to become clickable & trigger opening the R&E right panel.
Demo:
https://user-images.githubusercontent.com/59492998/203652430-716b18a2-5ef6-46ca-a421-a37013022cb7.mov
Contributes to #180 
=> Race & Ethnicities (Playtesting Followup): Make Callout Box Clickable

publisher/src/components/Reports/CreateReport.tsx, publisher/src/components/Reports/DataEntryForm.tsx, publisher/src/components/Reports/PublishConfirmation.tsx, publisher/src/components/Reports/ReportDataEntry.styles.tsx
- Fix "thisrecord" typo
- Don't gray out tab icons, so you can tell if a tab has errors
- Fix issue with seeing "Review" button instead of "Unpublish"! This I just found. Screenshot is the fixed version.
| Type: Feature               	| non-breaking change that adds …
=> [Publisher] Iowa playtesting fixes

common/components/DataViz/DatapointsTitle.styles.tsx, common/components/DataViz/DatapointsView.styles.tsx, common/components/DataViz/MetricInsights.tsx
Allow a minimum of 16px gap between metric title and metric insights before insights get cut off …
=> tweak metric title in data viz

agency-dashboard/src/AgencyOverview.tsx, agency-dashboard/src/DashboardView.tsx, agency-dashboard/src/stores/AgencyDataStore.ts, common/components/DataViz/DatapointsView.styles.tsx, common/components/DataViz/DatapointsView.tsx, common/components/DataViz/MetricInsights.tsx
Use metric.description to populate metric description
ALSO fix issue of metric insights hiding when window width is narrow enough. …
=> [Agency Dashboard] Replace placeholder metric description with api + fix metric insights disappearing

agency-dashboard/src/AgencyOverview.test.tsx, agency-dashboard/src/DashboardView.test.tsx, agency-dashboard/src/Header/AboutModal.tsx, agency-dashboard/src/Header/HeaderBar.tsx, agency-dashboard/src/stores/AgencyDataStore.ts
Update store to consume the new format of the api and display agency name
NOTE: this requires the new backend change to the api made here: https://github.com/Recidiviz/recidiviz-data/pull/17142 otherwise the app will break
| Type: Feature               	| non-breaking …
=> update to use new agency info in updated endpoint

agency-dashboard/src/DashboardView.tsx, agency-dashboard/src/LearnMoreModal.styles.tsx, agency-dashboard/src/LearnMoreModal.tsx
Implement Learn More modal, style is not finalized but data is live. …
=> simple learn more screen w live data

agency-dashboard/src/DashboardView.tsx, agency-dashboard/src/Header/HeaderBar.tsx, agency-dashboard/src/setupProxy.js, common/types.ts, publisher/src/components/MetricConfiguration/MetricsView.tsx, publisher/src/components/Reports/DataEntryForm.test.tsx, publisher/src/stores/FormStore.test.tsx, publisher/src/stores/MetricConfigStore.tsx, publisher/src/stores/ReportStore.ts
https://www.loom.com/share/0633bc39badc415ea0df25e20c8e5dea
Uses the new system key endpoint change [here](https://github.com/Recidiviz/recidiviz-data/pull/17347) in order to implement downloading all feed files associated with a given metric on the charts page.
| …
=> [Agency Dashboard] Implement download data functionality

publisher/src/components/Settings/AgencySettings.tsx, publisher/src/components/Settings/SettingsMenu.tsx
> Change permissions of what non admins can view about agency settings …
=> Change permissions for agency settings

agency-dashboard/src/DashboardView.tsx, common/components/DataViz/DatapointsView.styles.tsx, common/components/DataViz/DatapointsView.tsx, common/components/DataViz/MobileFiltersModal.tsx, common/components/DataViz/MobileModal.styles.tsx, common/components/DataViz/MobileSelectMetricsModal.tsx, common/types.ts, publisher/src/components/DataViz/ConnectedDatapointsView.tsx
Pressing Select Metric and Filters buttons opens full-screen modals on mobile sizes to change the selected metric or selected filter settings. …
=> [Agency Dashboard] Mobile modals for selecting metric and filters

agency-dashboard/src/AgencyOverview.test.tsx, agency-dashboard/src/AgencyOverview.tsx, agency-dashboard/src/Header/AboutModal.styles.tsx, agency-dashboard/src/Header/AboutModal.tsx, agency-dashboard/src/Header/HeaderBar.tsx, agency-dashboard/src/stores/AgencyDataStore.ts, common/components/DataViz/utils.ts, common/types.ts, publisher/src/analytics.ts, publisher/src/components/Settings/AgencySettings.styles.tsx, publisher/src/components/Settings/AgencySettings.tsx, publisher/src/components/Settings/AgencySettingsDescription.tsx, publisher/src/components/Settings/AgencySettingsSupervisions.tsx, publisher/src/components/Settings/AgencySettingsURL.tsx, publisher/src/components/Settings/types.ts, publisher/src/stores/AgencyStore.ts
- Add new "Homepage URL" AgencySetting in the AgencySettings page
- Surface agency settings "HOMEPAGE_URL" and "PURPOSE_AND_FUNCTIONS" in agency dashboard. …
=> Add new agency setting and show agency settings in dashboard

common/types.ts, publisher/src/components/DataUpload/UploadedFiles.tsx, publisher/src/components/Menu/Menu.tsx, publisher/src/components/Settings/AgencySettings.tsx, publisher/src/pages/Reports.tsx, publisher/src/stores/UserStore.ts
This sets us up to display the frontend depending on recidiviz admin and agency admin permissions once I get clarification of the front-end design/functionality …
=> Small refactor to user permissions

publisher/src/components/DataUpload/InstructionsTemplate.tsx
Fix not being able to download bulk upload templates, this is due to a routing change causing the href to be outdated. 
Perhaps we should add a test to make sure this link works to avoid future regressions?
| Type: Feature               	| non-breaking change that …
=> Fix download template issue due to routing change

publisher/src/components/Settings/AgencySettings.tsx, publisher/src/components/Settings/AgencySettingsDescription.tsx, publisher/src/components/Settings/AgencySettingsJurisdictions.tsx, publisher/src/components/Settings/AgencySettingsTeamManagement.tsx, publisher/src/components/Settings/AgencySettingsURL.tsx
Only show links to edit agency settings and make admin and remove users to Recidiviz admins and agency admins.
Basically if you're none of the above, you can see but not edit agency settings, except to invite new team members.
| Type: Feature               	| …
=> [Admin Permissions] Only allow most agency settings if user is admin

publisher/src/components/MetricConfiguration/Configuration.tsx
Copy change in Metric Configuration reporting frequency: Annual -> Annually
Closes #296 
=> Change label from Annual to Annually in Metric Config

publisher/src/components/MetricConfiguration/MetricsView.tsx, publisher/src/components/Settings/hooks.ts, publisher/src/components/Settings/utils.ts
Make url params lower case for prettier URLs in the metric config …
=> Lower case url params in metric config

publisher/src/components/MetricConfiguration/Configuration.tsx, publisher/src/components/MetricConfiguration/ContextConfiguration.tsx, publisher/src/components/MetricConfiguration/MetricDefinitions.tsx, publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
> Remove all onclick/onchange logic from render and put it to handlers outside
| Type: Breaking …
=> Refactor metric configuration callbacks (remove them from render)

publisher/package.json, publisher/src/components/DataUpload/UploadedFiles.tsx, publisher/src/components/Reports/ReportSummaryPanel.tsx, publisher/src/components/primitives/index.tsx, publisher/src/index.tsx, publisher/src/pages/Reports.tsx, yarn.lock
Implement tooltip on hover over the admin badge
Note for Humphrey: I had to tweak the design a bit, I couldn't place the tooltip on the bottom right because it would overlap with the existing contributors tooltip on the Reports page. I also couldn't put it on top for some reason it gets cut off. See image:
so I put it directly on the right.
I also had to shrink the height of the tooltip a bit or it gets cut off:
|-----------------------------	|--------------------------------------------------------------------------------------------------------- …
=> Tooltip for admin badge

publisher/src/components/Guidance/Guidance.styles.tsx, publisher/src/components/Guidance/Guidance.tsx, publisher/src/components/Guidance/GuidanceHeader.tsx, publisher/src/components/Guidance/index.ts, publisher/src/components/Guidance/types.ts, publisher/src/components/Header/Header.styles.tsx, publisher/src/router/Router.tsx
Setting up some general scaffolding. The goal here is to allow you to progress through each step/screen within the flow from beginning (welcome screen) to end (redirected to the /records page after the Publish Data step).
*Right now, there's only a "Next" button on each screen - that's so you can go through all of the steps. When I focus on building out each screen (#252, #253, #254, #258, #259), I'll replace the Next button with the appropriate action/skip button(s).
Demo:
https://user-images.githubusercontent.com/59492998/210005168-06fdc2d1-4263-46dd-99cf-c4a07e1855c7.mov
Closes #250 #251 
=> Guidance: Scaffolding

common/types.ts, publisher/src/components/MetricConfiguration/Configuration.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
https://www.loom.com/share/9813a11e0a424d1cafcd11db85fb6cc2
Went through this with Humphrey: now that we see all supervision disaggregated metrics, we simply enable/disable them when they are toggled between combined and disaggregated.
This is enough to avoid the refresh experience. There is an even bigger design exercise in the future to make this more intuitive.
| Type: Bug                   	| …
=> New frontend handling of supervision disaggregations

publisher/src/components/Menu/Menu.tsx
This was bugging me: 
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as …
=> Sort Agency dropdown alphabetically by name

publisher/src/components/Reports/DataEntryForm.tsx
Right now the "Save as Draft" button just navigates you back to the Reports page. Modify it to actually save the report as well. 
I wonder if we want to enforce saving when the user navigates away, like if they press the back button or home icon before autosave kicks in? This PR doesn't do that, but it's something we could do.  …
=> Actually save draft with "Save as Draft" button

common/types.ts, publisher/src/components/Settings/AgencySettings.styles.tsx, publisher/src/components/Settings/AgencySettings.tsx, publisher/src/components/Settings/AgencySettingsDescription.tsx, publisher/src/components/Settings/AgencySettingsSupervisions.tsx, publisher/src/components/Settings/AgencySettingsTeamManagement.tsx, publisher/src/components/Settings/AgencySettingsURL.tsx, publisher/src/stores/AgencyStore.ts
> Connect team management API with team management page
Type: Feature …
=> Hook team management api with frontend

common/types.ts, publisher/src/components/Reports/CreateReport.test.tsx, publisher/src/components/Reports/DataEntryForm.test.tsx, publisher/src/components/Reports/ReportSummaryPanel.tsx, publisher/src/components/Reports/Reports.styles.tsx, publisher/src/components/Settings/AgencySettingsTeamManagement.tsx, publisher/src/components/primitives/index.tsx, publisher/src/mocks/reportOverviews.json, publisher/src/pages/Reports.tsx, publisher/src/stores/AgencyStore.ts, publisher/src/stores/FormStore.test.tsx
Show editor badges in reports and data entry form
Still need to update API to show badges in UploadedFiles page tho!
| Type: …
=> Hook up editor badges to roles api

publisher/src/components/Guidance/Guidance.styles.tsx, publisher/src/components/Guidance/Guidance.tsx, publisher/src/components/Guidance/types.ts, publisher/src/components/Reports/ReviewReportDataEntry.tsx
Implements the Configure Metrics step (just the main overview screen) in the guidance flow. Here a user will see a list of metrics with an overall progress indicator as well as individual metric progress indicator bars to show the user progress.
Each metric has 4 categories that need to be set by the user for that metric to be considered complete:
1. **[25%]** Confirm the metric’s availability/frequency (Unavailable, Monthly, Annual > Specify Starting Month)
2. **[25%]** Confirm metric definitions
3. **[25%]** Confirm breakdown (dimensions) availability
4. **[25%]** Confirm breakdown (dimensions) definitions
Completing all 4 items will be a 100% completion for that metric - and naturally completing 2 of the 4 will be a 50% completion (for example).
Interesting things to note:
* Per the …
=> Guidance: Configure Metrics - Overview Screen & Computing Progress

common/types.ts, publisher/src/components/DataUpload/DataUpload.tsx, publisher/src/components/DataUpload/UploadedFiles.tsx, publisher/src/components/Header/Header.tsx, publisher/src/components/Menu/Menu.tsx, publisher/src/components/MetricConfiguration/Configuration.tsx, publisher/src/components/MetricConfiguration/DimensionContexts.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.tsx, publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx, publisher/src/components/MetricConfiguration/MetricDefinitions.tsx, publisher/src/components/MetricConfiguration/MetricsView.tsx, publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx, publisher/src/components/Reports/CreateReport.test.tsx, publisher/src/components/Reports/CreateReport.tsx, publisher/src/components/Settings/AgencySettings.tsx, publisher/src/components/Settings/AgencySettingsTeamManagement.tsx, publisher/src/components/Settings/SettingsMenu.tsx, publisher/src/pages/NotFound.tsx, publisher/src/pages/Reports.tsx, publisher/src/router/Router.tsx, publisher/src/stores/UserStore.ts
Transition from auth0 permissions to a user's agency role instead.
I also went ahead and removed using the assertion `agencyId!` in our codebase as well …
=> Transition from auth0 permissions to roles

publisher/src/stores/GuidanceStore.ts
Updates `onboardingTopicsStatuses` in the store to be a mapped object vs. an array of objects.
Contributes to #329 
=> Guidance (Follow Ups): Update `onboardingTopicsStatuses` to be a mapped object

publisher/src/components/Guidance/Guidance.styles.tsx, publisher/src/components/Guidance/Guidance.tsx, publisher/src/components/Guidance/types.ts, publisher/src/components/Menu/Menu.tsx, publisher/src/pages/Reports.tsx, publisher/src/stores/ReportStore.test.tsx
Addresses general UI feedback:
* Metric Configuration vertical responsiveness (should still be able to see and scroll through all metrics on the list)
* Adjust flashing of 0 of X metrics before being replaced by the right number (added a loader to the container)
* Adjust alignment of Onboarding screen (adjusted per the new Figma [design](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=6094%3A14587&t=KRytwPgZ2chhIBYR-1))
* Reduce spacing between “Skip” and button in Agency Setup (reduced by 16px)
* Update Records page copy to “No records to display. Create a record?”
* Update all Guidance copy to replace “Report” with “Record”
https://user-images.githubusercontent.com/59492998/219802960-323d6dac-3137-4b5b-9c3e-cec464ed81d2.mov
NOTE: I don't have a demo …
=> Guidance (Follow Ups): General UI

common/types.ts
Updated jurisdictions json.
Old format:
```
{
"id": "0100000000",
"area_name": "Alabama",
"state_name": "Alabama",
"state_abbrev": "AL",
"state_code": "01",
"fips": "01000",
"county_name": None,
"county_code": None,
"county_subdivision": None,
"county_subdivision_code": None,
"type": "state",
},
```
New format:
```
{ "0100000000": 
{
"id": "0100000000",
"state_abbrev": "AL",
"state_name": "Alabama",
"county_name": null,
"county_subdivision_name": null,
"name": "Alabama",
"type": "state"
},
}
```
Note: The new column 'name' can take the following values:
1. for states, name = 'state_name'
2. for counties, name = 'county_name, state_name'
3. for county subdivisions, name = 'county_subdivision_name, county_name, state_name'
This allows us to distinguish between county subdivisions with the …
=> [Justice Counts] updated jurisdictions json fields

publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
> Comment out code in jurisdictions so build can be made …
=> Hotfix for jurisdictions to make a build

publisher/src/components/DataUpload/InstructionsTemplate.tsx, publisher/src/components/DataUpload/SystemSelection.tsx, publisher/src/components/DataUpload/UploadErrorsWarnings.tsx, publisher/src/components/DataUpload/UploadedFiles.tsx, publisher/src/components/Global/constants.ts, publisher/src/components/MetricConfiguration/MetricConfiguration.tsx, publisher/src/components/MetricConfiguration/MetricsView.tsx, publisher/src/components/Settings/AgencySettingsBasicInfo.tsx, publisher/src/mocks/mockReport.ts, publisher/src/stores/AgencyStore.ts
> Change all appearances of "system(s)" to "sector(s)"   …
=> Replace "system(s)" with "sector(s)"

publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
> Description here
Improved algorithm for jurisdictions search …
=> Improve search algorithm for jurisdictions

publisher/src/components/Menu/Menu.tsx, publisher/src/stores/GuidanceStore.ts
Updates API route to match new backend endpoint.
Closes #431
=> Guidance: Update API route

common/components/DataViz/DatapointsTableView.styles.tsx, publisher/src/components/DataUpload/UploadedFiles.styles.tsx, publisher/src/components/Forms/Form.styles.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx, publisher/src/components/Reports/Reports.styles.tsx, publisher/src/components/Settings/AgencySettings.styles.tsx, publisher/src/components/Settings/Settings.styles.tsx
> Remove empty scrollbars for users which browser shows scrollbars always …
=> Remove empty scrollbars from publisher app

common/components/DataViz/DatapointsView.styles.tsx, publisher/src/components/DataUpload/UploadedFiles.styles.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx, publisher/src/components/MetricConfiguration/MetricsView.tsx, publisher/src/components/Settings/AgencySettings.styles.tsx
> Sticky headers for:
1. Data page (title + dropdown)
2. agency settings
3. team management
4. uploaded files
Records page already had sticky header
Sticky header for metric config I will do in follow-up task for metric configuration responsive design …
=> Sticky headers for responsive view

publisher/src/components/Guidance/Guidance.styles.tsx, publisher/src/components/Guidance/Guidance.tsx, publisher/src/components/Menu/Menu.tsx, publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
Addresses the following P0 followups:
* Add Agency dropdown and logout to Welcome screen
* Reduce unnecessary calls to backend
* Remove overflow container and allow user to scroll anywhere on the page
* ~Fix cropped CSG icon in footer~ (fixed in main)
* (P1) Metric Config: update copy of “Reset to default” in metric definitions -- “Reset” to default doesn’t quite make sense. Might just be “Choose Justice Counts Preferred Definition” or something. 
* Configure Metrics screen: hovering on metric should also highlight the specific metric you’re hovering over more. I think our usual pattern is to gray out all the others so that you’re focused on the current one.
* Configure Metrics screen: adjust the z-index of tooltips so they appear over the container (if possible)
Demo: …
=> Guidance: Playtesting II Followups

agency-dashboard/src/DashboardModals/DashboardModal.styles.tsx, agency-dashboard/src/Header/AboutModal.styles.tsx, publisher/src/components/DataUpload/DataUpload.styles.tsx, publisher/src/components/Menu/Menu.styles.tsx, publisher/src/components/Onboarding/OnboardingDataEntrySummary.tsx, publisher/src/components/Reports/DataEntryHelpPage.styles.tsx, publisher/src/components/Reports/HelperText.tsx, publisher/src/components/Reports/ReportSummaryPanel.tsx, publisher/src/components/Settings/AgencySettings.styles.tsx, publisher/src/components/Settings/AgencySettingsEditModeModal.tsx
Follow up on Ivan's work - extending the replacement of `overflow: scroll` to `auto` across all instances in the different apps.
Contributes to #441
=> Remove empty scrollbars from all repos

publisher/src/components/DataUpload/DataUpload.styles.tsx
Re-centers loader in Data Upload component. 
Before:
After:
Closes #475 
=> Re-center loader in Data Upload component

publisher/src/components/MetricConfiguration/Configuration.tsx, publisher/src/components/MetricConfiguration/DimensionContexts.tsx, publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.tsx, publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx, publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx, publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
> Description here
Fixes for metric configuration responsive view …
=> Follow up responsive fixes for metric configuration

agency-dashboard/src/DashboardModals/DashboardModal.styles.tsx, agency-dashboard/src/DashboardModals/LearnMoreModal.tsx, common/types.ts, publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx, publisher/src/stores/GuidanceStore.test.tsx, publisher/src/stores/GuidanceStore.ts, publisher/src/stores/MetricConfigStore.tsx
Updates Metric Configuration's (and other affected components') includes/excludes to conform to the new API and data structure. 
Note: this PR's diff is larger than it really is as the largest diff was updating the GuidanceStore tests which used the old data structure to access metric/dimension includes/excludes.
Playtesting Demo: [mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app](https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/)
Demo:
https://user-images.githubusercontent.com/59492998/223876307-83d8f48c-a82a-416c-876d-1659c75896c6.mov
Closes #474 
=> Multiple Includes/Excludes

common/package.json, publisher/package.json, yarn.lock
Update `recharts` to version 2.4.0 to fix known issue causing empty bar charts to show `0 auto` in the x-axis.
Issue reference: https://github.com/recharts/recharts/issues/2593
Closes #476 
=> [Bug] Fix empty bar charts showing '0 auto' in the x-axis

publisher/src/components/DataUpload/DataUpload.styles.tsx, publisher/src/components/Global/constants.ts, publisher/src/components/Reports/CreateReport.test.tsx, publisher/src/components/Reports/RemoveRecordsModal.tsx, publisher/src/components/Reports/Reports.styles.tsx, publisher/src/pages/Reports.tsx
> Changes to records page UI
Non-breaking refactor …
=> Records page UI refresh

publisher/src/components/Reports/Reports.styles.tsx, publisher/src/pages/Reports.tsx, publisher/src/stores/ReportStore.ts
Implements the API calls to the new endpoint to update multiple reports' status to "PUBLISHED" or "DRAFT". 
Demo:
https://user-images.githubusercontent.com/59492998/225148976-f68c74a8-7fa6-4ffb-9768-e04fbf967012.mov
Closes #499
=> Bulk Publishing: API

publisher/src/components/Settings/AgencySettings.styles.tsx
> Fix breakpoint change for agency settings wrapper
Fix agency title width for desktop view 
Type: Bug …
=> Fix agency settings responsiveness

publisher/src/pages/Reports.tsx
> Disable "Publish" if no drafts in 'All records" tab
Disable "Unpublish" if no published records in 'All records" tab
Type: Feature …
=> Extend disabled behavior for bulk actions

publisher/src/components/Menu/Menu.tsx, publisher/src/router/Router.tsx
Ensures all navigation links and routes are visible and accessible during Guidance while debugging random behavior.
Closes #XXXX
=> [Fix] Temp. show and unrestrict all navigation during Guidance

publisher/src/components/Header/Header.styles.tsx, publisher/src/components/Header/Header.tsx, publisher/src/stores/API.ts
This PR adds a 'Local' or 'Staging' badge on the header bar depending on which environment the app is deployed on.
| Type: …
=> [Justice Counts] Staging Badge FE: add badge to indicate environment

common/components/MiniLoader/MiniLoader.tsx, publisher/src/components/Reports/DataEntryForm.tsx
Adds loader to the review button in the data entry page when the form is saving.
https://user-images.githubusercontent.com/59492998/234618185-1ff3fe7a-9cc4-45f5-8dd5-8f9123928afa.mov
Closes #589
=> Bulk Publishing: Follow Ups - Add loader to Review button in the data entry form when saving

publisher/src/components/MetricSettings/DefinitionModalForm.tsx
> Remove description for definitions if there are none
Change appearance if no contexts and definitions
Type: Breaking Change …
=> Remove description if no definitions

publisher/src/components/DataUpload/InstructionsTemplate.tsx, publisher/src/components/DataUpload/UploadFile.tsx
Previously, the bulk upload flow only allowed .xlsx and .xls files to be uploaded. This PR changes this so that the bulk upload flow allows for .csv files as well. …
=> [Justice Counts] allowing bulk upload to accept csv files

publisher/src/components/DataUpload/UploadFile.tsx
This PR changes the UploadButton to now accept csv input. …
=> [Justice Counts] change UploadButton to accept csv

common/components/Button/Button.tsx, common/components/Dropdown/Dropdown.tsx, common/components/TabbedBar/TabbedBar.styled.tsx, common/components/TabbedBar/TabbedBar.tsx, common/components/TabbedBar/index.ts, common/components/TabbedBar/types.ts, publisher/src/components/Forms/Form.styles.tsx, publisher/src/components/Forms/NotReportedIcon.tsx, publisher/src/components/Forms/TabbedDisaggregations.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx, publisher/src/components/MetricConfiguration/MetricConfiguration.tsx, publisher/src/components/Reports/Reports.styles.tsx, publisher/src/pages/Reports.tsx
=> Shared tabbed bar

publisher/src/components/MetricsConfiguration/Configuration.tsx
Matt from CSG noticed a bug on both staging and prod. The description was a static string, rather than the description of each unique metric.
Before:
After: …
=> [Justice Counts] metric description bug fix

common/components/DataViz/DatapointsTitle.tsx, common/utils/helperUtils.ts, publisher/src/components/DataViz/MetricsDataChart.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.tsx, publisher/src/utils/dateUtils.ts
Changes all instances of 'Annual' to 'Anually' in the UI.
Records page:
Data page:
Config page: …
=> [Justice Counts] Converting Annual to Annually in UI

publisher/src/components/MetricsConfiguration/Configuration.tsx
Removes the green floating box that displays "Available for data upload" and "Available for publishing" since we are currently allowing users to upload and publish data regardless of metric configuration.
https://github.com/Recidiviz/justice-counts/assets/59492998/3351ff85-541b-4214-9dda-a9fe841b186e
Closes #634 
=> Remove green floating "Available for data upload/publishing" box

publisher/src/pages/Reports.tsx
> Bulk actions dropdown is now seen for agency admins as well
| Type: Breaking Change       	| fix …
=> Enable records bulk actions for agency admins

common/types.ts, publisher/src/components/DataUpload/DataUpload.styles.tsx, publisher/src/components/DataUpload/DataUpload.tsx, publisher/src/components/DataUpload/UploadFile.tsx, publisher/src/components/Header/Header.tsx, publisher/src/components/Header/hooks.tsx, publisher/src/components/Reports/DataEntryForm.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx, publisher/src/stores/UserStore.ts
> Add label and badge to headers on overlay pages
Type: Bug  …
=> Header label and badge for overlay headers

common/components/ToggleSwitch/ToggleSwitch.styles.tsx, common/components/ToggleSwitch/ToggleSwitch.tsx, common/components/ToggleSwitch/types.ts, publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx, publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx, publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
> Disable unknown race toggle if Hispanic or Latino is turned on
Type: Feature …
=> Address unintiuitive behavior on Race/Ethnicity popup

publisher/src/components/Menu/Menu.tsx, publisher/src/stores/UserStore.ts
> Add state code next to agency name in menu dropdown if it has state code and if agencies are belong to multiple states …
=> Add state abbreviation next to agency name in Agencies dropdown

publisher/src/components/MetricsConfiguration/Configuration.tsx, publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx, publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
> Adjusting styles and adding button to metric availability page …
=> Nit #1: changes to metric availability page

publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
> Make arrow appear instantly on hover on metric overview page …
=> Nit #6: Metric Settings hover interaction

publisher/src/components/Reports/DataEntryForm.tsx
> Blue color for "Saved" record toast  …
=> Nit #7: Change Save toast

publisher/src/components/DataUpload/DataUpload.tsx
Previously, when I user selected the system in which they wanted to upload a file for via Bulk Upload, we called setSelectedFile(undefined). This triggered a conditional that redirected the user to the reports page, rather than the bulk upload review page. By removing this line, we now go to the review page as expected.
Before:
https://github.com/Recidiviz/justice-counts/assets/82831800/8ab01578-9e66-4cdf-ae74-60026d6d58fa
Now:
https://github.com/Recidiviz/justice-counts/assets/82831800/5d507385-ff84-4b99-99e5-1b099e4aa1f4 …
=> [Justice Counts] Do not redefine SelectedFile on System Selection

publisher/src/components/Forms/Form.styles.tsx, publisher/src/components/Reports/CreateReport.styled.tsx, publisher/src/components/Reports/DataEntryForm.tsx
> Remove scroll and shrink behavior from data entry title …
=> Nit #10: Change heading on Data Entry page

publisher/src/components/DataViz/MetricsDataChart.styled.tsx
> Make system title on data page desktop view bigger …
=> Nit #11: Make headline for Data page bigger

publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
> Refactor definition modal form …
=> Refactor logic in definition modal form

common/components/DataViz/BarChart.tsx
> Sort bar chart values to be same as legend's instead of the opposite …
=> Make bar chart order same as legend from top to bottom

README.md, common/.babelrc.json, common/.storybook/main.ts, common/.storybook/preview-head.html, common/.storybook/preview.ts, common/components/Badge/Badge.stories.tsx, common/components/Badge/Badge.tsx, common/components/Button/Button.stories.tsx, common/components/Button/Button.styled.tsx, common/components/Button/Button.tsx, common/components/Dropdown/Dropdown.stories.tsx, common/components/Dropdown/Dropdown.styled.tsx, common/components/GlobalStyles/index.ts, common/components/HeaderBar/HeaderBar.stories.tsx, common/components/HeaderBar/HeaderBar.styled.tsx, common/components/Input/Input.stories.tsx, common/components/Input/Input.styled.tsx, common/components/MiniLoader/MiniLoader.tsx, common/components/RadioButton/RadioButton.stories.tsx, common/components/RadioButton/RadioButton.styled.tsx, common/components/TabbedBar/TabbedBar.stories.tsx, common/components/TabbedBar/TabbedBar.styled.tsx, common/components/ToggleSwitch/ToggleSwitch.stories.ts, common/components/ToggleSwitch/ToggleSwitch.styles.tsx, common/components/Tooltip/Tooltip.stories.tsx, common/components/Tooltip/Tooltip.styled.tsx, common/package.json, yarn.lock
Design Doc: https://paper.dropbox.com/doc/Design-Doc-Justice-Counts-Design-System--B76K_8ysZDYlN2WqNEI8eDI4Ag-dAYgys5PFyh8qxAVMYfMF
Adds Storybook configuration inside `common`, plus some stories:
- Tooltip
- ToggleSwitch
- Button
- RadioButton
- TabbedBar
- Dropdown
- HeaderBar
- Badge
- Input
More permutations and components to come. Configuration was tricky but seems to all work now. 
To run Storybook, cd into `common` and run `yarn storybook` after updating dependencies. 
Contributes to #21328
=> [#21328] Add Storybook configuration + shared components

common/components/Toast/Toast.ts
Adjusts the toast from top left corner to bottom right. Huge thanks to Forrest for helping figure out a good alternative location for the toast. Would love to hear your thoughts! It might take a bit of getting used to esp. since we've been used to the top left corner position for so long.
Demo:
https://github.com/Recidiviz/justice-counts/assets/59492998/b9f12824-b403-4679-ad4a-8e9ed3425f1e
Link: https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/
Note: if the Storybook story for the Toast needs updating, I will do this in a subsequent PR once everything is merged in (issue #773)
Closes #715
These boxes should be checked by reviewers prior to …
=> New Homepage: Toast Adjustment

publisher/src/components/DataUpload/UploadedFiles.tsx
Force page reload when selecting Agency dropdown items
Bug
Closes #777
=> [#777] force reload on change dropdown selector event

agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx, agency-dashboard/src/CategoryOverview/CategoryOverview.tsx, common/.storybook/main.ts, common/components/DataViz/CategoryOverviewLineChart.stories.tsx, common/components/DataViz/CategoryOverviewLineChart.tsx
Adds a story for @ivan-kishko's [LineChart component](https://github.com/Recidiviz/justice-counts/pull/804) PR
Closes #22805
=> [#22805] linechart component story

agency-dashboard/src/Footer/Footer.styles.tsx
=> Footer adjustments

agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx, agency-dashboard/src/CategoryOverview/CategoryOverview.tsx, common/components/DataViz/BarChartComponents.tsx, common/components/DataViz/MetricsCategoryBarChart.tsx, common/components/DataViz/Tooltip.tsx, common/components/DataViz/types.ts
> Add dollar sign to money metric values and add metric name to total tooltip
| Type: Breaking …
=> Changes to bar charts

publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
> Add left padding to metric name in metrics config page …
=> Add padding to metric name

agency-dashboard/src/Header/HeaderBar.styles.tsx, agency-dashboard/src/Header/HeaderBar.tsx
> Remove link from JC logos on agency dashboard …
=> Remove homepage link from logos

agency-dashboard/src/Footer/Footer.tsx
> Remove Clackamas county jail from footer …
=> Remove Clackamas county jail from footer

agency-dashboard/src/Home/Home.tsx, agency-dashboard/src/Home/types.ts
The query we use to determine how many published metrics an agency has is [really slow](https://recidiviz-inc.sentry.io/issues/4372359872/?project=4504532096516096&query=is%3Aunresolved&referrer=issue-stream&stream_index=0). Let's change this to just show how many published records the agency has! I think this still provides the same value -- it tells you basically whether it's worthwhile to click into this agency or not.
I tested locally along with [this BE PR](https://github.com/Recidiviz/recidiviz-data/pull/23030): …
=> [Justice Counts] Speed up Agency Dashboard home page [FE]

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> Fix mini charts on agency overview, so dates under charts reflect data bars correctly
| Type: …
=> Fix mini charts

common/components/DataViz/MetricsCategoryBarChart.tsx
> Change y-axis labels on category overview page in agency-dashboard to avoid ugly numbers like 3.2, 4.7 and only leave .5 based or round numbers only …
=> Change y-axis labels

common/components/DataViz/BarChart.tsx, common/components/DataViz/DatapointsView.tsx, common/components/DataViz/MiniBarChart.tsx, common/components/DataViz/Tooltip.tsx, common/components/DataViz/types.ts
> Fix "Total undefined" bar chart tooltip in publisher
Type: Bug …
=> Fix bar chart tooltip

publisher/src/components/Menu/Menu.tsx, publisher/src/components/MetricsConfiguration/Configuration.tsx, publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.tsx, publisher/src/pages/NotFound.tsx
> Fix bug where you get thrown back to data/config page after you switch to another page
Type: Bug …
=> Fix bounce back bug in publisher configuration page

publisher/src/components/Home/Home.tsx
Simple bug fix to replace '_' with whitespace for system tabs on Home page.
Before:
After: …
=> [Justice Counts] System replace underscore with space

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
> Removed category name and description If category metrics have no data  …
=> Remove category title if category metrics have no data

publisher/src/App.tsx
Kind of ugly, but maybe okay? 
Set flag to true and deployed to playtesting: https://lilitest---justice-counts-web-qqec6jbn6a-uc.a.run.app/ …
=> Toggle "Down for Maintenance" page with boolean flag

publisher/src/components/DataViz/ConnectedDatapointsView.tsx, publisher/src/components/DataViz/MetricsDataChart.tsx, publisher/src/components/Settings/hooks.ts
> Fix bounce back data page bug
Type: Bug …
=> Fix data page bug

agency-dashboard/src/Footer/Footer.tsx
Remove agency dashboard footer temporarily
Closes #866 
=> [#866] Remove footer from Agency Dashboard

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
Allow agencies of any system to have a dashboard (with capacity and costs metrics only)
This will unblock CSG since they need a Law Enforcement demo tomorrow. They can use the Law Enforcement [DEMO] agency on staging, which @morden35 just added fake data to!
Playtesting: https://lilitest---agency-dashboard-web-b47yvyxs3q-uc.a.run.app/agency/law-enforcement-%5Bdemo%5D
| Type: Bug                   	| …
=> Allowing agencies of any system to have a Capacity and Costs dashboard (as long as they are allowlisted)

agency-dashboard/src/CategoryOverview/CategoryOverview.tsx, common/components/DataViz/CategoryOverviewBreakdown.tsx, common/components/DataViz/CategoryOverviewLineChart.tsx, common/components/DataViz/MetricsCategoryBarChart.tsx
Fixes error that happens when no reported metrics are available.
**Note: Depends on #880 and incorporates changes from there**
Thanks to @mxosman for his help tracking this down
Closes #22940
These boxes …
=> [#22940] Fix Iowa DOC error

agency-dashboard/src/App.tsx, agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
[Follow up for #883]
This wraps the `CategoryOverview` and the `DashboardView` within the `<Protected>` component to enforce the allowlist incase a user goes to the `/agency/:slug/:category` or `/agency/:slug/dashboard` paths directly. 
In this demo - you'll see an example of not wrapping the components and then one with wrapping them:
https://github.com/Recidiviz/justice-counts/assets/59492998/66316de7-5c6b-4acf-b252-2df0afa8a93b
Thankfully, I assumed wrong about the multiple fetch calls - since this component stays mounted, it will only ever call when you load any one of those wrapped components once and anytime the slug-line changes.
**Here's how I tested this**:
* Added a console.log to the `fetchAgencyData` method in the AgencyDataStore
* Go to the `/agency/:slug` path which loads …
=> [Agency Dashboards] Wrap CategoryOverview and DashboardView within the <Protected> component to enforce the allowlist

publisher/src/components/DataViz/MetricsDataChart.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.tsx, publisher/src/components/Reports/Reports.styles.tsx, publisher/src/components/primitives/index.tsx, publisher/src/pages/Reports.tsx
Updates copy to refer to "child agencies" specifically vs. "other agencies" and adds banner to Records page to help clarify how to view/add data for metrics belonging to a child agency. 
[Note: I didn't add the banner in the data entry form because it would require quite a bit of styling adjustments to accommodate and it didn't seem worth it to do for a banner that only shows up for superagencies - but do LMK if there's a strong preference to move this from the overview page to the form.]
**Records:**
**Set Up Metrics:**
**Explore Data:**
Closes #934
=> [Publisher] Superagency: Playtesting Followups - Update copy and add banner to Records page

publisher/src/components/DataUpload/InstructionsTemplate.tsx
Updates instructions to help the user correctly upload for fiscal-year metrics. 
=> update instructions for fiscal year

publisher/src/App.tsx, publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx, publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx, publisher/src/components/HelpCenter/HelpCenter.styles.tsx, publisher/src/components/HelpCenter/HelpCenterSetup.tsx
Adds styling adjustments for links, code blocks, in-line code blocks and embedded videos for now. Will update as things keep adjusting - just adding some more styling to bring this to a good pause point for now!
Play with it here: 
https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/help
Code blocks:
https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/help/publisher/automated-bulk-upload
Embedded videos:
https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/help/publisher/bulk-upload
Contributes to #936 
=> Help Center: Styling Adjustments

publisher/src/components/DataUpload/InstructionsTemplate.tsx
Quick fix for a small bug that Matt found. Initially mis-matched the column titles. …
=> [Justice Counts] Small fixes to Bulk Upload Instructions page

publisher/src/App.tsx, publisher/src/components/Menu/Menu.tsx
Gates the Help Center in the menu - I completely forgot to gate this (thank you @morden35 for noticing this!)
=> [Publisher] Help Center - Gate Help Center in menu until launch

publisher/src/components/HelpCenter/Guides/AccountSetupGuide.tsx, publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx, publisher/src/components/HelpCenter/Guides/DashboardsGuide.tsx, publisher/src/components/HelpCenter/Guides/ExploreDataGuide.tsx, publisher/src/components/HelpCenter/Guides/ManualEntryGuide.tsx, publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx, publisher/src/components/HelpCenter/Guides/SuperagenciesGuide.tsx, publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx
> Updated help center content for all pages except bulk upload
=> Help center content update

agency-dashboard/src/AgencyOverview/AgencyOverview.styles.tsx, agency-dashboard/src/AgencyOverview/AgencyOverview.tsx, agency-dashboard/src/CategoryOverview/CategoryOverview.tsx, agency-dashboard/src/stores/AgencyDataStore.ts, common/components/DataViz/MetricsCategoryBarChart.tsx, common/components/DataViz/utils.ts
A few bugs were surfaced when Laura requested that we make 2 Cass County dashboards live. Currently the dashboards look like this:
* https://dashboard-demo.justice-counts.org/agency/cass-county-court-and-pretrial-services
* https://dashboard-demo.justice-counts.org/agency/cass-pulaski-community-corrections
After the fixes, they look like this:
* https://test---agency-dashboard-web-crmdkxchya-uc.a.run.app/agency/cass-pulaski-community-corrections/
* https://test---agency-dashboard-web-crmdkxchya-uc.a.run.app/agency/cass-county-court-and-pretrial-services
The issues are:
* Header layout is wonky
* Clicking into Capacity and Cost page from system X brought you to the Capacity and Cost page for system 1, no matter what
* Cass Pulaski home page didn't show anything until you clicked "Other …
=> Some dashboard fixes

publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
Filled in Help Center text for the following Bulk Upload sections:
- Single Page with Multiple Metrics
- Breakdown Column 
- Superagency Agency Column …
=> [Justice Counts] Help Center Bulk Upload copy changes

agency-dashboard/package.json, publisher/package.json, yarn.lock
Addresses the following critical security vulnerabilities with a simple core package upgrade:
https://github.com/Recidiviz/justice-counts/security/dependabot/43
https://github.com/Recidiviz/justice-counts/security/dependabot/44
=> [Security] Update @babel/core to 7.23.2 to address @babel/traverse vulnerability

publisher/src/components/HelpCenter/HelpCenterDirectory.tsx, publisher/src/components/HelpCenter/HelpCenterGuideLayout.tsx, publisher/src/components/HelpCenter/HelpCenterSetup.tsx
Addresses the following items:
* Add scroll-to-top logic when opening a guide
* Update Add Data guide order in the Publisher directory to be Manual Entry > Bulk Upload > Automated Upload
* Add relevant pages for the Advanced Concept guides
https://github.com/Recidiviz/justice-counts/assets/59492998/9599d69b-686f-426c-ad50-1bbf0f5a4f7e
Contributes to #1004
=> [Publisher] Help Center: Playtesting Followups (2/3)

publisher/src/App.tsx
I promise this is the last of these PRs... I was manually testing something and forgot to undo the `!` in the AppWrapper 🤦 . One character change. Sorry for the extra noise!
=> [Publisher] Help Center: Playtesting Followups Quick Adjustment

publisher/src/App.tsx, publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.tsx, publisher/src/components/DataViz/MetricsDataChart.tsx, publisher/src/components/Menu/Menu.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
Ungates Help Center to launch! 🚀 
Closes #960 
=> [Publisher] Help Center: Launch

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx, agency-dashboard/src/Home/Home.tsx, agency-dashboard/src/utils/formatting.ts, common/utils/helperUtils.ts, publisher/src/components/DataUpload/DataUpload.tsx, publisher/src/components/HelpCenter/Guides/AgencySettingsGuide.tsx, publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx, publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx, publisher/src/components/HelpCenter/Guides/DashboardsGuide.tsx, publisher/src/components/HelpCenter/Guides/ExploreDataGuide.tsx, publisher/src/components/HelpCenter/Guides/ManualEntryGuide.tsx, publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx, publisher/src/components/HelpCenter/Guides/SuperagenciesGuide.tsx, publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx, publisher/src/components/HelpCenter/HelpCenterSetup.tsx, publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
Updates content and adds links to Publisher and Dashboard apps according to what was outlined in the playtesting [doc](https://paper.dropbox.com/doc/Publisher-Help-Center-Playtesting--CCamGWVDM~qA87fVXDPaVWcdAg-1PLOZR6bSe6KHaerRumc3#:h2=%E2%80%9CAdd-more-links-back-to-Publis). 
Link to test: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/help (Jessica & Forrest - let me know if there's anything you'd like adjusted after playing around with the new changes)
Closes #1020
=> [Publisher] Help Center: Content Updates & Links to Publisher and Dashboards

.github/workflows/auto-merge-dependabot.yml
> This PR will automatically allow Helperbot to merge PRs opened by Dependabot if the version change is minor, of if it is a patch …
=> [Security] Auto-merge Dependabot minor and patch bumps

publisher/src/components/Reports/CreateReport.tsx
A follow up to an issue Stephanie ran into when trying to create a new fiscal year record for 7/2022 - 7/2023. The attempt raised an error that a record already exists with the specified date-ranges despite there being no existing record with the aforementioned date-ranges. 
We learned that the year input when trying to create a FY record is processed as the ending year and not the starting year - this adjustment was made to accommodate bulk upload but the Create Report UI was not updated to reflect this. So, Stephanie's attempt at creating a new fiscal year record for 7/2022 - 7/2023 (by selecting 2022 as the starting year in the UI) was processed as trying to create a FY record for 7/2021 - 7/2022 (which already exists, hence the error thrown).
The proposed solution is the update the …
=> [Publisher] UI adjustment for creating fiscal year records

common/components/GlobalStyles/Palette.ts, common/components/Modal/Modal.tsx, common/utils/helperUtils.ts, publisher/package.json, publisher/src/App.tsx, publisher/src/components/AdminPanel/AdminPanel.styles.tsx, publisher/src/components/AdminPanel/AdminPanel.test.tsx, publisher/src/components/AdminPanel/AdminPanel.tsx, publisher/src/components/AdminPanel/InteractiveSearchList.tsx, publisher/src/components/AdminPanel/SaveConfirmation.tsx, publisher/src/components/AdminPanel/UserProvisioning.tsx, publisher/src/components/AdminPanel/UserProvisioningOverview.tsx, publisher/src/components/AdminPanel/index.ts, publisher/src/components/AdminPanel/types.ts, publisher/src/components/Reports/DataEntryForm.tsx, publisher/src/components/Reports/Reports.styles.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx, publisher/src/components/Settings/AgencySettingsTeamManagement.tsx, publisher/src/stores/AdminPanelStore.test.tsx, publisher/src/stores/AdminPanelStore.ts, publisher/src/utils/featureFlags.ts, yarn.lock
Adds the User Provisioning flow to the admin panel. Within this flow, an admin can create users by providing a name, email address and optionally connecting them to one or more agency(ies). Admins can also update existing users' names and add/remove agencies to/from the user's account. 
I know I sound like a broken record when I say the diff is deceiving - but, it is a bit deceiving (a huge chunk are tests, styling adjustments, lots of comments, and minor updates). It was a bit challenging to think about how to best break this up while implementing this - so, I'm totally happy to try and break this apart into smaller chunks if this feels too overwhelming and not straightforward, but this at least gives an overview of this feature as a whole and all of the puzzle pieces that make this flow …
=> [Publisher] Admin Panel: User Provisioning

common/components/Dropdown/Dropdown.styled.tsx, common/components/Dropdown/Dropdown.tsx, publisher/src/components/AdminPanel/AdminPanel.styles.tsx, publisher/src/components/AdminPanel/InteractiveSearchList.tsx, publisher/src/components/AdminPanel/UserProvisioningOverview.tsx, publisher/src/components/AdminPanel/types.ts
Styling and clean up adjustments in preparation for the Agency Provisioning view.
Contributes to https://github.com/Recidiviz/justice-counts/issues/1051
=> [Publisher] Admin Panel: Agency Provisioning - Styling & Misc. Adjustments (1/n)

publisher/src/components/AdminPanel/AdminPanel.styles.tsx, publisher/src/components/AdminPanel/AdminPanel.test.tsx, publisher/src/components/AdminPanel/AgencyProvisioning.tsx, publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx, publisher/src/components/AdminPanel/UserProvisioning.tsx, publisher/src/components/AdminPanel/types.ts, publisher/src/stores/AdminPanelStore.ts
Addresses the following clean up items:
- Styling clean up adjustments
- Update "System" to "Sector"
- Ensure proper error handling and messaging (when trying to create existing users/agencies)
- Remove superagency system addition/removal -> checkmark update logic b/c it is no longer necessary (user doesn't select the superagency system anymore, the checkmark adds or removes it accordingly)
- Fix clash between search box and filter checkmarks in `AgencyProvisioningOverview`
Here's a quick demo of the error handling for existing users/agencies:
https://github.com/Recidiviz/justice-counts/assets/59492998/37544267-f6d4-40c3-b423-223eb24dfab3
Closes #1075 
These …
=> [Publisher] Admin Panel: Clean Up

publisher/src/App.tsx, publisher/src/components/Menu/Menu.tsx
Enables the admin panel for use in the production environment.
=> [Publisher] Admin Panel: Enable admin panel in production environment

publisher/package.json, publisher/src/components/Auth/AuthStore.ts, publisher/src/index.tsx, yarn.lock
Sets up basic sentry logging and adds an exception listener in the `AuthStore.getToken` method to try to better triangulate an intermittent forced logout issue reported by a member of CSG.
I'm sure there's more fine-tuning we can do to the configurations as we move along and expand FE error logging, but this is just a start. Here's the log for the test error I threw:
https://recidiviz-inc.sentry.io/issues/4766635999/?environment=production&environment=staging&project=4504532096516096&query=is%3Aresolved&referrer=issue-stream&statsPeriod=7d&stream_index=0
[P.S. the replay feature is super cool - shows you a replay of the users session before/during/after the error]
Closes #1059
These boxes should be checked by the submitter …
=> [Publisher] Add Sentry Logging

.github/workflows/deploy_to_playtesting.yml
Add a GH action to trigger playtesting deployment from frontend PRs.
Note: We added a similar feature for backend PRs [here](https://github.com/Recidiviz/recidiviz-data/pull/26922). 
We have a [deploy_for_playtesting.sh](https://github.com/Recidiviz/recidiviz-data/blob/main/recidiviz/tools/deploy/justice_counts/deploy_for_playtesting.sh) script for deploying to playtesting. However, this has to be run from the command line so only engineers can do it (e.g. if a PM wants to test our a PR, they have to bug an engineer to do a playtesting deploy). This change enables anyone with access to the PR to deploy to playtesting.
The GH action will be triggered manually from the PR. The user must specify the Service Name (defaults to publisher-web) and the [Playtest URL …
=> [Justice Counts] Add a GH action to trigger playtesting deployment from frontend PRs.

publisher/src/stores/AgencyStore.ts
Adds new toast to confirm that email settings were updated
https://github.com/Recidiviz/justice-counts/assets/19961693/f9d817e8-45de-4a39-b64c-b5c920dc982d
Closes https://github.com/Recidiviz/recidiviz-data/issues/26810
=> [Justice Counts] add toast to confirm that email settings were updated

.github/workflows/deploy_to_playtesting.yml
Tag the triggering actor and add failure message for playtest deployment.
Update the frontend playtest deployment action to:
Triggered both successful and unsuccessful deployments to verify that the helper bot commented as expected.
| Type: Feature               	| …
=> [Justice Counts] Tag actor and add failure message for playtest deployment.

publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
Updates toggle copy to describe what emails a user will be receiving.
=> [Justice Counts] Update toggle copy to describe emails

common/components/Dropdown/Dropdown.styled.tsx, common/components/HeaderBar/HeaderBar.styled.tsx, publisher/src/components/Menu/Menu.styles.tsx, publisher/src/components/Reports/DataEntryForm.tsx
Add agency name to header when viewing a record.
https://github.com/Recidiviz/justice-counts/assets/59492998/b38b9277-8208-4e7c-8a68-ec2e7f34bc4d
Closes #1138
=> [Publisher] Add agency name header when viewing a record

common/components/Button/Button.styled.tsx, common/components/CheckboxOptions/CheckboxOptions.styles.tsx, common/components/CheckboxOptions/CheckboxOptions.tsx, common/components/CheckboxOptions/index.ts, common/components/GlobalStyles/Typography.ts, common/components/Input/Input.styled.tsx, common/components/Input/Input.tsx, common/components/RadioButton/RadioButton.styled.tsx, publisher/src/components/AdminPanel/AdminPanel.test.tsx
Add new typography CSS and updated primitive components (inputs, checkboxes, radio buttons, regular buttons). 
Basically fleshes out the items outlined in the screenshot below so I can readily use them when I go through and update the other pages. None of the new components and styling are being used yet in this PR (aside from a super minor shade of grey adjustment in the button) - this is just setting things up for subsequent PRs.
Reference: [Figma Designs](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9412%3A1321&mode=design&t=ci5NxaeS7H9lTree-1)
Closes #1165 #1166
These boxes should be checked by reviewers …
=> [Publisher][Design Updates] Add new typography CSS and updated primitive components

common/components/GlobalStyles/Typography.ts, common/components/TabbedBar/TabbedBar.styled.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
Updates the layout of Metric Settings overview page to match the [Figma designs](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9418%3A4011&mode=design&t=6EO7qWlRKq8bn1bC-1).
The changes are purely styling changes - no functionality was touched/updated.
Note: there's a new treatment for handling an agency w/ a long list of sectors in the overview page incoming - will update this PR once that design is ready.
Note: I'm also going to hold off merging these updates until parts 1, 2, and 3 are ready to go at once and we're ready to release.
Demo: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/
Contributes to #1167 
These boxes should be checked by the submitter prior to …
=> [Publisher][Design Update][Metric Settings] Update layout of Metric Settings overview page (1/3)

common/components/Button/Button.styled.tsx, common/components/CheckboxOptions/CheckboxOptions.styles.tsx, common/components/CheckboxOptions/CheckboxOptions.tsx, common/components/GlobalStyles/constants.ts, common/components/RadioButton/RadioButton.tsx, publisher/src/components/MetricsConfiguration/Configuration.styled.tsx, publisher/src/components/MetricsConfiguration/Configuration.tsx, publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx, publisher/src/components/MetricsConfiguration/MetricAvailability.tsx, publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx, publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx, publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx, publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.styled.tsx, publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
Updates the layout of Metric Availability & Breakdowns page to match the [Figma designs](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9418%3A3634&mode=design&t=RMICoZJlXhkvO6rU-1).
The changes are mostly styling changes - no-op with regards to functionality.
Note: there is a treatment for the annual frequency custom month dropdown incoming, will update this PR once that design is ready.
Demo: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/
Contributes to #1167 
=> [Publisher][Design Update][Metric Settings] Update layout of Metric Availability & Breakdowns page (2/3)

common/components/CheckboxOptions/CheckboxOptions.styles.tsx, common/components/Input/Input.styled.tsx, common/components/Input/Input.tsx, common/components/Tooltip/Tooltip.styled.tsx, publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx, publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx, publisher/src/components/MetricsConfiguration/MetricAvailability.tsx, publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx, publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx, publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx, publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
Update the layout of the Metric Definitions page to match the [Figma designs](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=9412%3A1321&mode=design&t=ZZyWrKU782rw1044-1) [note, the character limit counter on the context input will not be implemented - not worth the added complexity at this point].
The changes are mostly styling changes - no-op with regards to functionality.
Demo: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/
Closes #1167
=> [Publisher][Design Update][Metric Settings] Update layout of Metric Definitions page (3/3)

publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.tsx
First PR, yay! I think everything should be ok here :) …
=> [Publisher] Copy change on Enter Data page

common/components/DataViz/DatapointsTableView.styles.tsx, common/components/DataViz/DatapointsView.styles.tsx, common/components/GlobalStyles/constants.ts, publisher/package.json, publisher/src/components/DataViz/MetricsDataChart.styled.tsx, publisher/src/components/DataViz/MetricsDataChart.tsx, yarn.lock
1. added `react-intersection-observer` package
2. made right container sticky
3. added top and bottom scroll shadows to left container …
=> [Publisher] Improve toggle experience for metrics page

publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
This PR ungates the offset picker for next week's launch!
Closes #1251 
=> [Justice Counts] ungate offset picker in production environment

publisher/src/components/AdminPanel/AgencyProvisioning.tsx, publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx, publisher/src/components/AdminPanel/UserProvisioning.tsx, publisher/src/components/AdminPanel/UserProvisioningOverview.tsx, publisher/src/components/AdminPanel/types.ts, publisher/src/stores/AdminPanelStore.ts
1. Auto-add logic for users/agencies created via second flow by id …
=> [Publisher][Admin Panel] Auto-add users/agencies created via second flow

publisher/src/stores/FormStore.ts
Temporary fix for crash that happens when opening a record. Will need to investigate further, but this will unblock the crash. …
=> [Justice Counts][Temp Bug Fix] Handle undefined case in FormStore `validate` logic

publisher/src/components/AdminPanel/AgencyProvisioning.tsx, publisher/src/components/AdminPanel/InteractiveSearchList.tsx, publisher/src/components/AdminPanel/UserProvisioning.tsx, publisher/src/components/AdminPanel/types.ts
Add functionality to select all filtered items from InteractiveSearchList …
=> [Publisher][Admin Panel] Add functionality to select all filtered items from InteractiveSearchList

common/components/Dropdown/Dropdown.styled.tsx, common/components/Dropdown/Dropdown.tsx, publisher/src/components/Menu/Menu.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.tsx, publisher/src/stores/AgencyStore.ts
Reverts Recidiviz/justice-counts#1295
=> Revert "[Publisher][Superagencies] Add dropdown for child agencies to Set Up Metrics page"

publisher/src/components/AdminPanel/AgencyProvisioning.tsx, publisher/src/stores/AdminPanelStore.ts
Trim leading/trailing white spaces and duplicate spaces (like "first[][]last") in the agency name when creating a new agency or updating an existing agency.
I created a new agency that contained both leading and trailing whitespace as well as multiple spaces within the agency name. Based on logging to the console (and how the agency name is saved in the database) I confirmed that all whitespace was trimmed as expected. I also attempted to edit the agency name and add in whitespace. I confirmed that this was saved with the expected trimming. …
=> [Justice Counts] Trim whitespace from agency name

agency-dashboard/src/Home/Home.tsx
Adjust "records" to record when there is only one published record in the staging Home page.  …
=> [Agency Dashboards] Adjust "records" to record when there is only one published record

publisher/src/components/DataUpload/UploadedFiles.styles.tsx, publisher/src/components/Settings/AccountSettings.styles.tsx, publisher/src/router/Router.tsx
Fix broken link to Uploaded Files component from menu dropdown and minor styling updates so it doesn't look off as a standalone page. …
=> [Publisher][Bug] Fix link to Uploaded Files

publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
Ungate email reminders to production users. …
=> [Publisher] Agency Settings - Ungate email reminders to production users

publisher/src/components/AdminPanel/AdminPanel.styles.tsx, publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx, publisher/src/stores/AdminPanelStore.ts
Added delete agency functionality …
=> [Admin Panel] Add delete agency functionality

common/components/Dropdown/Dropdown.tsx, common/components/Dropdown/types.ts, publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx
Solution for searching deduplicated dropdown options that are grouped by sector. …
=> [Publisher] Option for unique search filter results w/ group headers

common/package.json, yarn.lock
Reverts Recidiviz/justice-counts#1372
=> Revert "Bump @babel/preset-react from 7.24.1 to 7.24.7"

publisher/src/components/DataViz/MetricsDataChart.tsx, publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx
Added initial logic for metric persistence …
=> [Publisher] Persist current metric after switching to a different child agency via the dropdown

publisher/src/components/DataUpload/SpreadsheetReview.tsx, publisher/src/components/Reports/BulkActionReview.tsx, publisher/src/components/Reports/DataEntryReview.tsx, publisher/src/components/Reports/constants.ts, publisher/src/components/ReviewMetrics/helpers.ts
Copy update in confirmation modal after publishing and swap positions of "View Data" and "Go to Records" buttons, as requested by CSG. I thought this was a great suggestion - it's much clearer now.
Before:
After:
| Type: Feature               	| non-breaking change …
=> [Publisher] Copy update in confirmation modal after publishing and swap positions of "View Data" and "Go to Records" buttons

common/utils/dateUtils.ts, publisher/src/components/DataUpload/DataUpload.styles.tsx, publisher/src/components/DataUpload/SpreadsheetReview.tsx, publisher/src/components/DataUpload/UploadSpreadsheet.tsx, publisher/src/stores/HomeStore.ts
Add agency name and CY/FY suffix to record names in the publish review existing records warning message.
Single agency uploads with CY/FY suffix:
Superagency uploads to multiple agencies: …
=> [Publisher] Add agency name and CY/FY suffix to record names in the publish review existing records warning message

common/components/DataViz/DatapointsView.styles.tsx, common/components/DataViz/DatapointsView.tsx, publisher/src/components/DataViz/ConnectedDatapointsView.tsx
> Description here
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as …
=> [Publisher] Keep chart calculation regardless of screen width

common/components/Dropdown/Dropdown.styled.tsx, common/components/Dropdown/Dropdown.tsx, publisher/package.json, publisher/src/components/Home/ChildAgenciesTable.styled.tsx, publisher/src/components/Home/ChildAgenciesTable.tsx, publisher/src/components/Home/EditModal.tsx, publisher/src/components/Home/Home.test.tsx, publisher/src/components/Home/Home.tsx, publisher/src/components/Home/SystemsCheckboxDropdown.styled.tsx, publisher/src/components/Home/SystemsCheckboxDropdown.tsx, publisher/src/components/Home/TableSearchInput.styled.tsx, publisher/src/components/Home/TableSearchInput.tsx, publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx, publisher/src/stores/AdminPanelStore.ts, publisher/src/stores/HomeStore.ts, yarn.lock
Added search filter to the Home page table …
=> [Publisher][Superagencies] Add filters to Home page table

common/utils/downloadHelpers.ts, publisher/src/components/DataViz/MetricsDataChart.tsx
Added Agency Name to Data Download CSV
| Type: Breaking Change       	| fix or feature that would cause existing functionality …
=> [Publisher] Add Agency Name to Data Download CSV

common/components/Input/Input.styled.tsx, common/types.ts, publisher/src/components/Settings/AgencySettings.styles.tsx, publisher/src/components/Settings/AgencySettingsTeamManagement.tsx, publisher/src/components/Settings/Settings.styles.tsx
Updated team members tab in agency settings …
=> [Publisher] Update team members tab in agency settings

publisher/src/components/Reports/DataEntryForm.tsx
Removes autosave before exit to help mitigate overwrites when multiple people are viewing, editing and refreshing the same record. Resolves issue reported by CSG where a user refreshing while the record is empty would overwrite changes made by another user viewing the same record.
Thank you @Recidiviz/justice-counts team for your help playtesting this!
| Type: Bug                   	| non-breaking change …
=> [Publisher] Remove autosave before exit in records

publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.styled.tsx, publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.tsx
Updated Enter Data homepage layout …
=> [Publisher][Design Updates] Update Enter Data homepage layout

common/components/Button/Button.styled.tsx, common/components/Modal/Modal.styled.tsx, common/components/Modal/Modal.tsx, common/components/TabbedBar/TabbedBar.styled.tsx, publisher/src/components/Modals/UnauthorizedDeleteActionModal.tsx, publisher/src/components/Reports/BulkActionReview.tsx, publisher/src/components/Reports/Reports.styles.tsx, publisher/src/components/Reports/constants.ts, publisher/src/components/ReviewMetrics/helpers.ts, publisher/src/pages/Reports.tsx, publisher/src/utils/dateUtils.ts
Updated Records overview page layout
| Type: Breaking Change       	| fix or feature that would cause existing functionality …
=> [Publisher][Design Updates] Update Records overview page layout

common/components/ScrollToTop/ScrollToTop.tsx, common/components/ScrollToTop/index.ts, publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx, publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
Created scroll to top button and added to overview pages …
=> [Publisher][Admin Panel] Add scroll to top button in overview pages

agency-dashboard/src/stores/AgencyDataStore.ts, common/components/DataViz/DatapointsView.stories.tsx, common/components/DataViz/DatapointsView.styles.tsx, common/components/DataViz/DatapointsView.tsx, common/components/DataViz/Legend.tsx, common/components/DataViz/MobileFiltersModal.stories.tsx, common/components/DataViz/utils.test.ts, common/components/DataViz/utils.ts, common/hooks/useBarChart.ts, common/stores/DataVizStore.ts, common/types.ts, publisher/src/components/DataViz/ConnectedDatapointsView.tsx, publisher/src/components/DataViz/MetricsDataChart.tsx
Added initial copy and UI updates …
=> [Publisher] Update Explore Data page to allow toggle between metric reporting frequencies

agency-dashboard/src/react-app-env.d.ts, common/types.ts, publisher/src/components/MetricsConfiguration/ConfigurationStatusButton.tsx, publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx, publisher/src/components/MetricsConfiguration/MetricAvailability.tsx, publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx, publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx, publisher/src/components/MetricsConfiguration/types.ts, publisher/src/components/Reports/DataEntryForm.test.tsx, publisher/src/mocks/HomeMocksHelpers.ts, publisher/src/stores/FormStore.test.tsx, publisher/src/stores/MetricConfigStore.tsx, publisher/src/window.d.ts
Add configuration status buttons to metric breakdowns and includes/excludes (top-level and dimension). This will help agencies see and indicate whether the breakdowns and includes/excludes have been configured to their satisfaction.
You can play with it here: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/ …
=> Metric Settings: Add Configuration Status button

publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Disable secondary Create New User flow in the admin panel until the bugs in #1442 are resolved. …
=> [Publisher][Admin Panel][Bug] Disable secondary Create New User flow

common/components/DataViz/Tooltip.tsx
Added total number to breakdown tooltip on Explore Data page …
=> [Publisher] Add total number to breakdown tooltip

agency-dashboard/package.json, yarn.lock
Add resolution upgrades for vulnerable transitive packages to address security alerts. …
=> [Agency Dashboard] Upgrades for vulnerable transitive packages

publisher/src/pages/Settings.tsx
Fix "edit you account" typo.
CSG's Esteem Brumfield flagged this typo!
=> [Publisher] Fix "edit you account" typo.

publisher/src/components/AdminPanel/AdminPanel.styles.tsx, publisher/src/components/AdminPanel/AdminPanel.test.tsx, publisher/src/components/AdminPanel/AgencyProvisioning.tsx, publisher/src/components/AdminPanel/UserProvisioning.tsx, publisher/src/stores/AdminPanelStore.ts
Add preload spinner to admin panel modals …
=> [Publisher][Admin Panel] Add preload spinner to admin panel modals

common/utils/dateUtils.ts, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Order the list of records in the left side panel in ascending order (oldest records -> newest records) …
=> [Publisher] Sort records list by year and month in review metrics page

publisher/src/components/AdminPanel/AdminPanel.test.tsx
Added modal loader unit tests
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not …
=> [Publisher][Admin Panel] Add modal loader unit tests

publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Hide users search feature when creating new agency …
=> [Publisher][Admin Panel] Hide users search feature when creating new agency

publisher/src/components/DataUpload/UploadedFiles.styles.tsx, publisher/src/components/DataUpload/UploadedFiles.tsx
Removed "Mark as Pending" and "Mark as Processed" buttons …
=> [Publisher][Uploaded Files] Remove "Mark as Pending" and "Mark as Processed" buttons

publisher/src/components/AdminPanel/AgencyProvisioning.tsx, publisher/src/components/AdminPanel/types.ts, publisher/src/stores/AdminPanelStore.ts
Added Agency URL and Description Fields to Admin Panel …
=> [Publisher][Admin Panel] Add Agency URL and Description Fields to Admin Panel

publisher/src/components/Forms/Form.styles.tsx, publisher/src/components/Reports/CreateReport.styled.tsx, publisher/src/components/Reports/CreateReport.tsx
Updated create new record page layout
| Type: Breaking Change       	| fix or feature that would cause existing functionality …
=> [Publisher] Update create new record page layout

publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Removed "Copy metric settings to child agencies" feature from new agency flow …
=> [Publisher][Admin Panel] Remove "Copy metric settings to child agencies" feature from new agency flow

publisher/src/components/Home/Home.styled.tsx, publisher/src/components/Home/Home.tsx, publisher/src/components/Home/TaskCard.tsx, publisher/src/components/Home/types.ts
1. Added tooltip to Task Cards for read only users …
=> [Publisher] Gate create records route from non-admins

common/components/Input/Input.styled.tsx, common/components/Input/Input.tsx, common/components/RadioButton/RadioButton.styled.tsx, publisher/src/components/Forms/Form.styles.tsx, publisher/src/components/Reports/DataEntryForm.tsx, publisher/src/components/Reports/DataEntryFormComponents.tsx, publisher/src/components/Reports/HelperText.tsx, publisher/src/components/Reports/ReportSummaryPanel.tsx, publisher/src/pages/Reports.tsx
Updated data entry form page layout …
=>  [Publisher] Update data entry form page layout

publisher/src/components/AdminPanel/AdminPanel.styles.tsx
Fixed sizing of user cards when searching team members …
=> [Publisher][Admin Panel] Fix sizing of user cards when searching team members

publisher/src/components/AdminPanel/AdminPanel.styles.tsx, publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx, publisher/src/components/AdminPanel/VendorManagementModal.tsx, publisher/src/components/AdminPanel/types.ts, publisher/src/stores/AdminPanelStore.ts
Adding Vendor Management Modal UI and logic …
=> [Publisher][Admin Panel] Add Vendor Management Modal

.eslintrc.js, agency-dashboard/package.json, common/components/DataViz/DatapointsTableView.styles.tsx, common/components/DataViz/DatapointsTableView.tsx, common/components/GlobalStyles/Typography.ts, common/package.json, publisher/package.json, publisher/src/components/AdminPanel/UserProvisioning.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx, publisher/src/components/ReviewMetrics/ReviewMetrics.tsx, publisher/src/stores/AdminPanelStore.ts
Updated publish review page layout …
=> [Publisher][Design Updates] Update publish review page layout

common/stores/BaseDatapointsStore.ts
Fixed breakdowns data overriding …
=> [Publisher][Bug] Fix breakdowns data overriding

.github/workflows/ci.yml
Update CI workflow actions/cache version to v4 from deprecated v2 …
=> Update CI workflow actions/cache version to v4

publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
> Description here
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as …
=> [Publisher][Bug] Fix app crash when missing Metric Definitions

publisher/src/components/DataUpload/DataUpload.tsx, publisher/src/components/DataUpload/UploadedFiles.styles.tsx, publisher/src/components/DataUpload/UploadedFiles.tsx
Added new Datapoints Shared column to Uploaded Files table …
=> [Publisher] Add Datapoints Shared column to Uploaded Files table

publisher/src/components/AdminPanel/AdminPanel.test.tsx, publisher/src/components/AdminPanel/VendorManagementModal.tsx, publisher/src/stores/AdminPanelStore.test.tsx
Added more unit tests for Admin Panel
| Type: Breaking Change       	| fix or feature that would cause existing functionality …
=> [Publisher][Admin Panel] Add more unit tests for Admin Panel

publisher/src/components/Forms/Form.styles.tsx, publisher/src/components/Reports/DataEntryForm.tsx
Added empty record state message …
=>  [Publisher] Data Entry: Update empty record state

publisher/src/components/DataUpload/ShareSpreadsheet.tsx, publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx, publisher/src/components/DataViz/MetricsDataChart.tsx, publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx, publisher/src/components/Reports/BulkActionReview.tsx, publisher/src/components/Reports/DataEntryForm.test.tsx, publisher/src/components/Reports/ReportDataEntry.tsx, publisher/src/pages/Reports.tsx
Updated loading error
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as …
=> [Publisher] Update loading error

publisher/src/components/AdminPanel/AdminPanel.test.tsx, publisher/src/components/AdminPanel/UserProvisioning.tsx
Disable create new agency secondary flow until we can investigate and fix the current bug that's wiping out a set of user's existing agencies. …
=> [Publisher][Bug] Admin Panel: Disable create new agency secondary flow

publisher/src/components/AgencySettings/SteppingUpContextualInformation.tsx
Updates copy for Stepping Up context questions in the agency settings page, as requested by CSG. 
=> [Publisher] Update Copy for Stepping Up Context Questions

publisher/src/components/Menu/Menu.tsx, publisher/src/router/Router.tsx
Fixed crash when attempting to go to non provisioned agency …
=> [Publisher][Bug] Fix crash when attempting to go to non provisioned agency

common/components/DataViz/DatapointsTableView.tsx, common/components/TabbedBar/TabbedBar.styled.tsx, common/components/TabbedBar/TabbedBar.tsx, common/hooks/index.ts, common/hooks/useScrollShadows.ts, publisher/src/components/AdminPanel/AdminPanel.styles.tsx, publisher/src/components/AdminPanel/AgencyProvisioning.tsx, publisher/src/components/AdminPanel/AgencyProvisioningComponents/BreakdownSettings.tsx, publisher/src/components/AdminPanel/AgencyProvisioningComponents/index.ts, publisher/src/components/AdminPanel/AgencyProvisioningContext.tsx, publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx, publisher/src/components/AdminPanel/BreakdownSettings.tsx, publisher/src/components/AdminPanel/types.ts, publisher/src/stores/AdminPanelStore.ts
Added Custom Other Configuration logic & UI in Admin Panel …
=> [Publisher] Add Custom Other Configuration in Admin Panel
