publisher/src/components/Forms/TabbedDisaggregations.tsx
publisher/src/components/Reports/DataEntryForm.tsx

This removes all `index` and `reportMetric[index]` references to a metric within the `TabbedDisaggregations` component. Prior to organizing metrics by system, the disaggregation tabs referenced a metric by its index for speedy access. Since that is no longer necessary, we can pass the current `metric` directly to the `TabbedDisaggregations` component to render the appropriate disaggregation tabs for each metric.
Closes #15207

[Frontend][Bug][2/2] Data Entry Form: Disaggregations Bug For Multi-System Agencies

---

README.md
publisher/src/components/MetricsView/MetricsView.tsx
publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/pages/Reports.tsx
publisher/src/stores/DatapointsStore.ts
publisher/src/stores/ReportStore.ts
publisher/src/stores/StoreProvider.tsx

https://www.loom.com/share/8ec11e17e8004218859c43a77141a461
Set up reactions to clear reports and datapoints state when user switches agencies. 
For the Reports page, we only fetch the reports list when the user navigates to that page, OR the user agency id has changed.
For the Metrics page, we only fetch the datapoints when the user navigates to that page, OR the user agency id has changed.
This means if the user switches agencies while on a different page, we clear, but don't fetch the new data until the user visits a page that needs to load that data, minimizing needless fetches.
| Label                       	| Description …

[Frontend] Clear reports and datapoints state when switching agencies

---

.github/workflows/require_labels.yml

Adds pull request label requirement to our CI workflows.
Closes #9

Require Pull Request Labels on all PRs

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.tsx

Fleshes out the Error/Warning page. There are a two main types of errors that can occur after an upload:
1. Pre-ingest errors (errors that occur when the file cannot be properly parsed)
2. Metric errors and/or warnings that occur within the sheets of the Excel file
If an upload has only warnings (and no errors), the user will have a `Continue` button that will enable them to continue to the confirmation page.
Uploading a file that only has warnings (lorem ipsum for now - would love copy ideas):
https://user-images.githubusercontent.com/59492998/190512328-b79ac837-2191-4591-b712-52739dcf86bb.mov
Uploading a file that has metric errors & a file that generates pre-ingest errors:
https://user-images.githubusercontent.com/59492998/190512319-69e7de02-0c04-4757-915f-987c220f208e.mov
Closes #18 …

[Frontend] Data Upload: Error/Warning Page

---

publisher/src/components/Reports/DataEntryForm.test.tsx

Uncomments and adjusts old data entry form test
Closes #13325 on `recidiviz-data`

[Frontend] Data Entry Form Test

---

publisher/src/components/ReviewMetrics/ReviewMetrics.tsx

Filter out metrics we are getting in the data upload api response if there are no updated datapoints for that metric
| Type: …

[Frontend] Fix filtering metrics in review metrics page

---

publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
publisher/src/shared/types.ts

- Fix overwritten values count
- Due to duplicate datapoint values in the Data Upload API response, we overcount overwritten values sometimes. 
- I filed a task to fix this on the [backend](https://github.com/Recidiviz/justice-counts/issues/31), but for now, we can ignore duplicates in the frontend. I didn't put a TODO to undo this change because I don't think it's really necessary. 
- Change "Overwrites" to "Overwritten Values"
- Allow continuing to the Review Metrics page even if the upload had errors
- Tweaked Review Metrics to make it more clear that their data has already been successfully uploaded
- Changed the "Review 0 Uploaded Metrics" copy into a very simple No Metrics to Review
> All pull requests must have at least one of the following labels applied (otherwise the PR will …

[Frontend][Review Metrics] Review Metrics Playtesting follow-ups

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.tsx

Show old values in the Review Metrics page
Optional code to show when a metric is "new", as in the previous value was Null
| …

[Frontend][Review Metrics] Show old values

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/InstructionsTemplate.tsx
publisher/src/components/DataUpload/SystemSelection.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/types.ts
publisher/src/components/Loading/Loading.tsx
publisher/src/components/Menu/Menu.styles.tsx
publisher/src/components/Menu/Menu.tsx

Addresses the following Data Upload (v1) playtesting feedback:
| # | Description | Demo |
|-|-|-|
|1| Redesigned error/warning page |  <video src="https://user-images.githubusercontent.com/59492998/191634559-b150711d-20ac-480e-b798-5cf2d4c5e09f.mov"> |
|2| Redesigned upload loading component |  <video src="https://user-images.githubusercontent.com/59492998/191634139-0dd92403-7ccf-4bbd-bc1c-91d6a773c415.mov"> |
|3| Constraint height of menu dropdown + make it scrollable |  <video src="https://user-images.githubusercontent.com/59492998/191634230-5f0f8e32-a7d3-4fa2-ae33-fd96db30bcd5.mov"> |
|4| Hitbox for downloading a template/example should be the entire button and not the `Download` text | <video src="https://user-images.githubusercontent.com/59492998/191634265-0e647e5a-c8f2-4c94-b99e-11eb …

[Frontend] Data Upload v1: Playtesting Followups

---

publisher/.env.example
publisher/README.md
publisher/package.json
publisher/src/setupProxy.js
publisher/yarn.lock

So far, when developing, we have been running our backend locally in a Docker container on port localhost:5001 and then running our frontend against that via `proxy: localhost5001` in `package.json`. This works fine, but there are a couple of reasons why we might want to run our frontend against a deployed version of our backend on staging:
* Contractors who don't have access to our Docker container
* To test out performance/latency on staging
* To test against our staging database
By default, the behavior will stay the same, but we can now run against staging via this command `REACT_APP_PROXY_HOST=<staging url> yarn run dev`.
NOTE to @mxosman and @terryttsai -- once this gets merged, you will need to make a copy of `.env.example` and rename it to `.env` (see updated README).
> All pull …

Make it possible to run frontend against staging backend

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/DataUpload/UploadedFiles.tsx
publisher/src/components/Forms/TextInput.tsx
publisher/src/pages/AccountSettings.tsx

Moves the UploadedFiles component (which displays a list of files the user uploaded) to the new Settings page, and updates the Settings page to the new design.
Demo:
https://user-images.githubusercontent.com/59492998/191997458-6f8ae4e3-dea1-4faf-9941-613ef5b6827b.mov
Loading & Error States (ignore the buttons - updated in the demo above):
Closes #38

[Frontend] Data Upload v1: Move Uploaded Files to New Settings Page

---

publisher/src/setupProxy.js

Adjusts the path in the `setupProxy.js` to `["/api", "/app_public_config.js"]` as that seems to fix some strange issue with proxying and connecting to the backend.
Closes #XXXX

Adjust Proxy Paths

---

publisher/src/setupProxy.js

Adds `/auth` to the list of paths in `setupProxy.js` to allow logging out.

Add /auth path to proxy

---

publisher/src/components/DataUpload/UploadErrorsWarnings.tsx

Updates the copy for the following cases after a spreadsheet has been uploaded:
1. Only warnings present
2. Only errors present
3. Warnings and errors present
Since warnings only appear on successful metrics, you can assume anything here with a warning was successfully ingested.
**Warnings Only**:
**Errors Only**:
**Warnings and Errors**:
Closes #52 

Data Upload: Playtesting Followup (Update Error/Warning/Success Page Copy)

---

publisher/src/App.tsx
publisher/src/components/Badge/Badge.tsx
publisher/src/components/Menu/Menu.tsx
publisher/src/components/MetricsView/MetricsView.styles.tsx
publisher/src/components/MetricsView/MetricsView.tsx
publisher/src/pages/Settings.tsx

Removes the `/metrics` route (and from the Menu) and refactors the MetricsView component to match the updated design (up until the detailed metrics view which is currently styled the same as before]). This will help set up the next phase of work within the Metric Configuration which will be updating the detailed metrics view per the new design.
Demo of current change:
https://user-images.githubusercontent.com/59492998/194413204-9c17a55d-be9f-40a4-869c-8fd44cef3bb6.mov
Closes #63 

Settings: Metric Configuration (1/n)

---

publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
publisher/src/components/Reports/ReportSummaryPanel.tsx
publisher/src/components/Settings/Settings.styles.tsx
publisher/src/components/Settings/SettingsMenu.tsx
publisher/src/pages/Settings.tsx

Adds table-of-content navigation of metrics in the settings menu once a user has clicked into a metric that allows users an easy way to toggle between metrics while in the detailed view.
https://user-images.githubusercontent.com/59492998/195896182-9e69ea0c-509a-497a-990c-9dc27cba9b7a.mov
Closes #80

Settings: Metric Configuration: Navigation (Table of Contents) (4/n) 

---

publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
publisher/src/components/MetricConfiguration/index.ts
publisher/src/components/Reports/ReportSummaryPanel.tsx
publisher/src/components/Settings/Settings.styles.tsx
publisher/src/components/Settings/SettingsMenu.tsx
publisher/src/pages/Settings.tsx
publisher/src/shared/types.ts

Implements the UI for the metric configuration definitions (includes/excludes) and moves the metric context configuration to the overall metric's definition. Currently it uses a mock settings object that is appended to the response and for now updates do not persist - the logic to save settings and send them to the backend will be implemented in a follow up PR (#82 specifically).
https://user-images.githubusercontent.com/59492998/195665047-73f32934-72a3-4914-8109-74eff6e3044a.mov
Closes #73

Settings: Metric Configuration: Definitions (3/n)

---

agency-dashboard/package.json
publisher/package.json
yarn.lock

Move react-scripts to devDependencies
This helps avoid security vulnerability as Peter surfaced here: https://recidiviz.slack.com/archives/C034W7C26NL/p1665182436209979 …

[Frontend] Move react-scripts to devDependencies

---

publisher/src/App.tsx
publisher/src/components/DataViz/DatapointsView.styles.tsx
publisher/src/components/Forms/NotReportedIcon.tsx
publisher/src/components/Menu/Menu.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricsView.tsx

Recreates the old MetricsView component to render data visualizations that were previously a part of the metric configuration. I only kept what was needed to render the metrics list and the data visualization. The metric boxes look different because I reused the metric box component from the new metric config (which are styled slightly differently).
Demo:
https://user-images.githubusercontent.com/59492998/196814023-e48ad674-a392-424d-a994-55a527124c73.mov
[Update] Added spacing between the right side header and the data viz:
Closes #99 

Recreate MetricsView Component for Data Visualization

---

publisher/src/App.tsx
publisher/src/components/DataViz/DatapointsView.styles.tsx
publisher/src/components/Forms/NotReportedIcon.tsx
publisher/src/components/Menu/Menu.tsx
publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricBox.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
publisher/src/components/MetricConfiguration/MetricsView.tsx
publisher/src/components/MetricConfiguration/index.ts
publisher/src/components/Settings/Settings.styles.tsx
publisher/src/components/Settings/SettingsMenu.tsx
publisher/src/pages/Settings.tsx
publisher/src/shared/types.ts

Cleans up the Metric Configuration component and specifically accomplishes the following items:
- Move components into their respective files and general code clean up
- Merge newly created types for metric config with original types
- Fix bugs (switching agencies, out-of-sync checking and unchecking)
- Handles case where no definitions are sent
Closes #81 

Settings: Metric Configuration: Refactor & Clean Up (5/n)

---

publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx

Implements responsive layout and adds bottom padding to not block element visibility in reduced screen heights.
Demo:
https://user-images.githubusercontent.com/59492998/197863878-9745c456-0692-4379-b0f2-7bb4d917fa33.mov
Closes #109 

Settings: Metric Configuration: Playtesting Followups - Responsiveness (5/n)

---

publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx

Allows user to re-enable a dimension field (by clicking the unchecked area) when the entire disaggregation is off. The result will be enabling the clicked dimension and enabling the disaggregation.
Demo:
https://user-images.githubusercontent.com/59492998/197656591-eca39beb-e69a-4ff4-b257-b509741ff20c.mov
Contributes to #109 

Settings: Metric Configuration: Playtesting Followups - Enable Dimension Selection When Disaggregation is Off (4/n) 

---

publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx

Highlights the default settings values when hovered over the `Choose Default Definition` button.
https://user-images.githubusercontent.com/59492998/197642025-c4daa319-8bd6-422c-8c05-d3799c8698f1.mov
Contributes to #109 

Settings: Metric Configuration: Playtesting Followups - Default Definition Hover State (3/n)

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
publisher/src/components/Settings/Settings.styles.tsx

Miscellaneous styling adjustments based on round 2 of playtesting feedbacks. 
General description of the changes:
- Adjusted the padding between the menu & the metric config main sections, and between the metric/breakdown selections area and the definitions area
- Reduced the font-size of the overall metric
- Made adjustments to prevent the arrow from squishing into the badge
- Fixed the multiple scrollbar issue
- Updated copy for metrics/breakdowns without definitions
- Slightly increased spacing between the definition items
- Added a slight transition easing the reveal of the default metric buttons when hovering over the `Choose to Default` button
- Added a border-top to the Context and increased the “Context” title font-size
Demo: …

Settings: Metric Configuration: Playtesting Followups - Misc. Styling Adjustments (6/n)

---

publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx

Fixing the visual bug below where the MetricBoxes were taking up the entire height when there are 2 or less boxes. Did a manual test of each tab and other agencies and it no longer persists.
Before:
After:
Closes #125 

[Bug] Metric Configuration: MetricBoxes Taking Up Entire Height

---

publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricBox.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
publisher/src/components/MetricConfiguration/MetricsView.tsx
publisher/src/components/MetricConfiguration/types.ts
publisher/src/components/Settings/SettingsMenu.tsx
publisher/src/pages/Settings.tsx
publisher/src/stores/MetricConfigStore.tsx

Equip with a new mobx data store, this PR refactors and connects all Metric Configuration & related UI components to the store. This should be a no-op refactor with regards to behavior (everything here should behave exactly the same as it does in staging). 
Closes #134 

Metric Configuration Store: Refactor & Connect UI Components to the Store (2/2)

---

publisher/src/components/Forms/Form.styles.tsx
publisher/src/components/Forms/NotReportedIcon.tsx
publisher/src/components/Forms/TabbedDisaggregations.tsx
publisher/src/components/Reports/DataEntryForm.test.tsx
publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/Reports/DataEntryHelpPage.styles.tsx
publisher/src/components/Reports/DataEntryHelpPage.tsx
publisher/src/components/Reports/HelperText.tsx
publisher/src/components/Reports/PublishConfirmation.styles.tsx
publisher/src/components/Reports/PublishConfirmation.tsx
publisher/src/components/Reports/PublishConfirmationSummaryPanel.styles.tsx
publisher/src/components/Reports/PublishDataPanel.tsx
publisher/src/components/Reports/ReportDataEntry.styles.tsx
publisher/src/components/Reports/ReportDataEntry.tsx
publisher/src/components/Reports/ReportSummaryPanel.tsx
publisher/src/components/Settings/Settings.styles.tsx
publisher/src/pages/Settings.tsx

> Redesigned data entry page implementation
- Redesigned summary panel
- Redesigned publish data panel
- Redesigned data entry form 
- Add Help Page …

Redesigned data entry page

---

publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/Reports/PublishConfirmation.tsx
publisher/src/components/Reports/PublishConfirmationSummaryPanel.tsx
publisher/src/components/Reports/ReportDataEntry.tsx
publisher/src/components/Reports/ReportSummaryPanel.tsx

See video for reproducing the bug here: https://app.zenhub.com/workspaces/justice-counts--622109ea3bb6e0001d2d06ad/issues/recidiviz/recidiviz-data/16570
This bug is caused by `formStore.validatePreviouslySavedInputs` being called when the user is navigating from the Publish Confirm page back to the data entry page, which replaces all user inputs with what was originally fetched from the server when the data entry page was first loaded.
The `DataEntryForm` component gets unmounted and remounted when navigating to and away from the Publish Confirm page, which causes `formStore.validatePreviouslySavedInputs` to get triggered. I believe `formStore.validatePreviouslySavedInputs` is intended to be triggered once on loading the data entry page and not when navigating from Publish Confirm back to …

[Justice Counts] Fix data entry form bug when navigating back from publish confirm page

---

publisher/src/components/Reports/PublishConfirmation.tsx

> Fix metrics count at header of review page (without disabled ones) …

[Frontend][Publisher][Bug] Fix metric count in header inside review page

---

publisher/src/stores/FormStore.ts

Removes context validation from the FormStore and updates the `key` parameter names to be more readable.
Closes #136

FormStore: Remove Context Validation

---

publisher/src/components/Reports/CreateReport.test.tsx
publisher/src/pages/Reports.tsx
publisher/src/stores/ReportStore.test.tsx
publisher/src/utils/dateUtils.ts

This PR adds details about if the annual report represents a calendar or fiscal year in the reports overview page.
Related to #16219

include FY/CY details for annual reports

---

.eslintrc.js
agency-dashboard/src/AgencyOverview.test.tsx
agency-dashboard/src/AgencyOverview.tsx
agency-dashboard/src/App.tsx
agency-dashboard/src/DashboardView.test.tsx

This PR reverts the configuration change made [here](https://github.com/Recidiviz/justice-counts/pull/111)
When we turn off `react/react-in-jsx-scope`, the eslint rule doesn't seem to stay off for some reason. If I start `yarn dev` in a new tab, usually we get no errors, but when modifying a file and recompiling, we start getting `react/react-in-jsx-scope` errors again. I'm at a loss as to why this is happening, and by now we've reimported React in most of our files to get around this issue. 
So this PR just reinstates these rules. …

revert eslint rule to disable requiring react in jsx scope

---

common/types.ts
publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesGridStates.ts
publisher/src/components/MetricConfiguration/constants.ts
publisher/src/components/MetricConfiguration/types.ts
publisher/src/stores/MetricConfigStore.tsx

Implements the required functionality of R&E components according to the updated specification for Race and Ethnicity.
A brief description of the 3 core states users can find themselves in--
There are 3 distinct states (outlined below) that dictate the maximum available dimensions (of the 24 race & ethnicity dimensions) a user can enable/disable. 
- Answered “Yes” to this question (**Does your case management system allow you to specify an individual’s ethnicity (Hispanic, Non-Hispanic, or Unknown) for this metric?**)
- User can report all 24 dimensions and can choose to disable a race if they are unable to report it
- Turning off a single race is equivalent to turning off 3 dimensions because a single race has 3 ethnicities (HISPANIC/LATINO, NOT HISPANIC LATINO, UNKNOWN ETHNICITY)
- …

Race & Ethnicity: Logic & Functionality (2/2)

---

publisher/src/components/Reports/CreateReport.tsx

When creating reports with the same start and end date, I was seeing a generic response. This PR makes a change in the FE where we now check what the description is before displaying the toast. We deprecated all api responses that were not 500 because only 500 responses show up in our logs. As a result, the check to see if the response code is 400 to display the toast with the specific error date error was always ignored.
https://user-images.githubusercontent.com/19961693/202267336-91582317-8d70-44ab-b519-a69f39e1aad9.mov
Closes #XXXX

display report creation error when there are overlapping report dates

---

publisher/src/utils/dateUtils.ts

I didn't realize that the `months_by_name` array is zero-indexed so all of the months in the frequency column were off by one! 
Associated with #16219

fix month off by one error for report frequency

---

publisher/src/utils/dateUtils.ts

This PR is a follow-up to playtesting. Now all annual frequencies will have the name of the month provided, not just fiscal years. 

add month name to all annual frequencies

---

publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx

When disaggregation is disabled, the grid area is grey'd-out.
Demo:
https://user-images.githubusercontent.com/59492998/203653152-10446df7-54bb-4123-a60e-d8cd5254feb1.mov
Contributes to #180

Race & Ethnicities (Playtesting Followup): Grey Out Grid When Disaggregation Is Disabled

---

agency-dashboard/src/DashboardView.styles.tsx
agency-dashboard/src/DashboardView.tsx
common/components/DataViz/DatapointsView.styles.tsx
common/components/DataViz/DatapointsView.tsx
common/components/DataViz/MetricInsights.tsx

New dataviz controls design + place metric insights in the left panel of agency dashboard but show it below the chart in tablet or mobile mode …

[Agency Dashboard] New dataviz controls design + metric insights placements

---

common/types.ts
publisher/src/components/MetricConfiguration/MetricBox.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/stores/MetricConfigStore.tsx

This PR updates the badges used in the metric settings pages so that they reflect the custom reporting frequency of a metric if the custom frequency is not `undefined`.
The default reporting frequency for `Civilians Complaints Sustained` is annual, but a custom reporting frequency has been added such that it is now reported monthly. 
Related to #16218

update metric settings badges to reflect custom reporting frequency

---

publisher/src/components/Reports/PublishConfirmation.styles.tsx
publisher/src/components/Reports/PublishConfirmation.tsx

Cleans up the Data Entry Publish Confirmation rendering of the Race & Ethnicities dimensions by grouping the dimensions by ethnicity w/ respective headers. 
The disaggregation headers are already an incredibly small font size and I couldn't reasonably go smaller for the ethnicity headers - so I opted to keep them the same size but with a grey font color. Not sure if it's clear or confusing - would love some design help or your ideas if unclear.
Demo:
https://user-images.githubusercontent.com/59492998/203653011-35d52c6a-9a5b-42ae-9098-ba4784318e8c.mov
Contributes to #180

Race & Ethnicities (Playtesting Followup): Group Races by Ethnicities in Data Entry Publish Confirmation

---

publisher/src/components/Settings/SettingsMenu.tsx

Terry pointed out an issue with the Metric Configuration link in the Settings side menu where it shows up nothing when clicked (after you've selected a metric). After debugging, it looks like it navigates back to `/settings/metric-config` without the additional params. The solution is to update the Settings menu navigation to include the system params for the Metric Configuration link.
Closes #XXXX

[Fix] Settings: Metric Configuration Link

---

publisher/src/components/MetricConfiguration/MetricConfiguration.tsx

Removes the Back To Metrics link.
Reference:
Contributes to #180 

Race & Ethnicities (Playtesting Followup): Remove Back To Metrics

---

publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
publisher/src/stores/MetricConfigStore.tsx

Replace all instances of the MetricConfig store's `activeMetricKey` and `activeSystem` with URL params & updates related Race & Ethnicities components. [Huge shout out to all of @ivan-kishko work with implementing the routing]
Closes #185 

Race & Ethnicities: Replace activeMetricKey and activeSystem with URL params

---

publisher/src/components/Forms/BinaryRadioButton.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
publisher/src/stores/MetricConfigStore.tsx

Debounce saving and send all 24 dimensions instead of the deltas. Also, optimize saving by using `input`s for the buttons and utilizing `onChange`.
Demo: https://playtesting---justice-counts-web-qqec6jbn6a-uc.a.run.app/
Contributes to #180 

Race & Ethnicities (Playtesting Followup): Debounce Saving & Send All Dimensions

---

publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
publisher/src/components/MetricConfiguration/utils.ts
publisher/src/components/Settings/Settings.styles.tsx

Quick last minute items:
- Almost forgot about sorting the races (sorted based on the updated spec):
- The active metric in the Settings menu metrics list lost its bottom blue border - it must've gotten lost somewhere in the overlapping PRs & rebases:
Closes #180

Race & Ethnicities: Sorting Races & Quick Fix

---

common/components/Toast/Toast.ts
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
publisher/src/components/Onboarding/Onboarding.tsx

General styling-related clean up:
- Reduce toast height 
- <img width="206" alt="Screenshot 2022-12-02 at 12 55 18 PM" src="https://user-images.githubusercontent.com/59492998/205382066-730e3034-e68d-4652-b43d-13863ee53197.png"> to <img width="167" alt="Screenshot 2022-12-02 at 12 55 34 PM" src="https://user-images.githubusercontent.com/59492998/205382063-ab687fed-1348-428d-a3b0-2d07fd294e7d.png">
- Reduce top padding on right panel in Metric Config
- <img width="728" alt="Screenshot 2022-12-02 at 2 44 43 PM" src="https://user-images.githubusercontent.com/59492998/205383494-dc317e3b-2b40-4da5-a57c-980a6b02199f.png">
- Adjust hover state of call out box to have a light blue background
- <img width="644" alt="Screenshot 2022-12-02 at 2 45 01 PM" …

Playtesting Followup: General Styling Fixes

---

publisher/src/components/MetricConfiguration/ContextConfiguration.tsx

Removes the Additional Context subheader text.
Closes #195

Playtesting Followup: Remove additional context subheader

---

publisher/src/components/Auth/VerificationPage.tsx
publisher/src/components/Onboarding/Onboarding.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.tsx

Updates the following items in the Onboard/First Run Experience:
- Replace Humphrey's email with our new support email
- Copy update: Settings & Publish
- Fix positioning of "Publish" box
Closes #192

Playtesting Followup: FRE Updates

---

publisher/src/components/MetricConfiguration/Configuration.tsx

This fix sets the reporting frequency starting month to July, not June, when a user selects a fiscal year reporting frequency. 
https://user-images.githubusercontent.com/19961693/206739231-00d08615-1cb5-4ed4-8d09-5a04ecbeb182.mov
Related to #204 

fix: set starting month to July when user selects fiscal year

---

publisher/src/stores/UserStore.ts

Send the user email on requests to `PUT` `api/users` so that the BE can store the email in the `UserAccount` table. 
I checked this locally end-to-end while using the `nichelle-hall/update-backfill-script` branch in the BE, and saw that the database was updated when I logged in. 
Closes #17274

send user email in requests to /api/users

---

common/types.ts
publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/types.ts
publisher/src/stores/MetricConfigStore.tsx

This is the frontend piece to [#17161](https://github.com/Recidiviz/recidiviz-data/pull/17161/files) which allows an agency to specify whether or not a metric is reported as disaggregated by supervision subsystems.
Quick Demo:
https://user-images.githubusercontent.com/59492998/207926892-2198ecce-fd0c-49d1-8e81-39fb080e4a69.mov
Deployed here: https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app
Closes #229 #231 

Supervision Metrics - Disaggregated vs Combined

---

agency-dashboard/src/AgencyOverview.tsx
agency-dashboard/src/DashboardView.styles.tsx
agency-dashboard/src/DashboardView.tsx
agency-dashboard/src/index.tsx
common/components/DataViz/BarChart.tsx
common/components/DataViz/DatapointsView.styles.tsx
common/components/DataViz/DatapointsView.tsx
common/components/DataViz/Legend.tsx
common/components/DataViz/MobileSelectMetricsModal.tsx
common/components/DataViz/Tooltip.tsx

<div>
- "24 months 2 years" becomes "4 years", "13 months" becomes "1 year 1 month"
- Fix legend in Race & Ethnicity overflow
- Add selected metric state for Select Metrics dropdown
- Fix “No reported data for this metric” placement in tablet and mobile
- Scrolling issue when navigating
- Make the url all lower case
- Fix issue with monthly values formatted as yearly (Agency 152 Readmissions show 4 2022 values)
- I just made each bar say "month year" or "year" depending on whether that datapoint is annual, or monthly
- [Agency 152] Funding says 1 year of data in the overview, but the chart says No Data Available
- The issue is that the frontend is receiving datapoints with Null values. In the aggregate case, it seems like we don't need this, but in the disaggregations case, that might be …

Agency Dashboard playtesting followups

---

publisher/src/components/MetricConfiguration/MetricsView.tsx

A bug came up during playtesting today where the data table labels did not reflect the custom reporting frequency. This PR is a fix! 
https://user-images.githubusercontent.com/19961693/210908068-d644253b-2209-4d86-be41-c9bf4791bebe.mov
Closes #17241

update data table labels with custom reporting frequency

---

common/types.ts
publisher/src/components/Settings/AgencySettings.tsx

This PR grabs the email address from the agency response instead of hard coding the email addresses in the Team Management section of Agency Settings. 
Results after deploying to my playtesting branch and using the `nichelle-hall/surface-emails` branch in the BE. 

[Justice Counts] Replace hardcoded email addresses with emails from the DB

---

publisher/src/stores/UserStore.ts

We need to send email_verified on first login so that we can update the invitation in the Team Management section of Agency Settings ([figma](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?node-id=6255%3A15227&t=EL8ATUOzlRF42TOS-0)). I added it to the `UserStore.updateAndRetrieveUserPermissionsAndAgencies` method since it is called on login. 

send email_verified when retrieving user permissions

---

publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/Settings/hooks.ts

> Fix link to metric config at the bottom of data entry form
Fix back button behavior on metric config page
Type: Bug
| Type: …

Fix link to metric config in data entry form, fix back button on metric config

---

publisher/src/pages/Reports.tsx

After clarifying with Humphrey, allow agency admins as well as recidiviz admins to create reports …

[Frontend] Allow agency admins to create reports

---

publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx

It looks like there are some metrics that do not have a metric level context. This fix prevents us from rendering any of the context component (right now it just shows the header) when the metric level context array is empty. I thought that all metric level contexts have at least one free text box - but I'm not 100% sure. Either way, this helped expose the unnecessary rendering.
Closes #326 

[Bug] Prevent rendering of metric level context component when the context array is empty

---

publisher/src/App.tsx
publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Guidance/index.ts
publisher/src/router/Router.tsx

Sets up `/getting-started` route to redirect users who have not completed onboarding to the new barebones Guidance component.
There is a mock `hasCompletedOnboarding` boolean flag in the `App.tsx` and `Router.tsx` that controls whether to redirect the user to `/getting-started` route. The `hasCompletedOnboarding` will eventually live in a mobX data store `App.tsx` and `Router.tsx` can refer to that single source of truth.
Expected behavior: when `hasCompletedOnboarding` is set to `false` in both `App.tsx` and `Router.tsx` - you are redirected to `/agency/{:agencyId}/getting-started`. When set to `true`, you can enter and explore the app as usual.
https://user-images.githubusercontent.com/59492998/209717169-6c23e628-d208-4b03-a37d-868435ad38c9.mov
Closes #248 
**This box MUST be checked by …

Guidance: Routing

---

publisher/src/components/Guidance/Guidance.styles.tsx
publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Guidance/types.ts

Implements the Setup Your Agency flow where a user can navigate to the `Agency Settings` portion of the settings page or skip this step.
Working demo:
https://user-images.githubusercontent.com/59492998/210026979-3b3c0360-e008-4116-a787-f9db8db6c95c.mov
*NOTE: since we're just working with mock data that's not persisted, going back to the home screen via (Get Started) or refreshing will clear the temp. persisted progress and start you back at the beginning (you can adjust this by changing the mock values of `mockTopicsStatus`). The actual behavior once the state is persisted on the BE will be that the user goes back to the screen appropriate for the step they are on.
Closes #253 
These boxes should be checked by the submitter …

Guidance: Setup Your Agency

---

publisher/src/components/Guidance/Guidance.styles.tsx
publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Guidance/GuidanceHeader.tsx
publisher/src/router/Router.tsx

Implements the Add Data step in the guidance flow which allows a user to choose between uploading a spreadsheet or manually filling out a record. This step unlocks the `Records` page as well as the `Upload Data` button (in the header). 
NOTE: I've commented out the line that updates the topic status based on whether or not the user has at least one report. Since we all have atleast one report - I figured I'll disable it for now so you can experience this step (otherwise, it'll skip this step because you've already added data and go to the Publish Data step).
Demo:
https://user-images.githubusercontent.com/59492998/210604999-0bdea03f-1ef5-487f-b51d-b1c047fc2ef8.mov
Closes #258 
These boxes should be checked by the submitter …

Guidance: Add Data

---

publisher/src/components/Guidance/Guidance.styles.tsx
publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Guidance/GuidanceHeader.tsx
publisher/src/components/Reports/PublishConfirmation.tsx
publisher/src/components/Reports/ReviewReportDataEntry.tsx
publisher/src/router/Router.tsx

Implements the Publish Data step in the guidance flow. Here a user will see a list of their draft/unpublished records and be encouraged to publish data. The `Data` link to view the visualizations of the uploaded metrics is unlocked which means the rest of the app functionality is available to the user. If they haven't published data yet, every time they return to the app, they will be greeted by the "Publish Data" step of guidance.
Demo:
https://user-images.githubusercontent.com/59492998/210675307-38561b4d-7d1d-4d4c-a9dd-fec5df38529c.mov
NOTE: the "Next" button won't exist here in the final version (it's just to get you through to the next screen - which is completing the guidance journey)
Closes #259 
These boxes should be …

Guidance: Publish Data

---

publisher/src/components/MetricConfiguration/MetricDefinitions.tsx

Adjusts the logic that displays the "Technical definitions are not available for this metric yet." for the top level metric and dimensions.
Description of the different cases as outlined in issue #336:
Case 1: Top-level metric does not have any includes/excludes defined.
We should show "Technical Definitions are not available for this metric yet." (I believe this is the current behavior already!)
Case 2: Dimension does not have any includes/excludes define, BUT it does have at least one context (i.e. all Other dimensions will fall in this category).
We should not show the "Technical Definitions are not available for this metric yet.", and should just show the text box.
Case 3: Dimension does not have any includes/excludes define, and doesn't have a context either (all Unknown dimensions …

[Fix] Adjustments to "Technical Definitions are not available for this metric yet." logic

---

publisher/src/components/MetricConfiguration/Configuration.tsx

For some `ANNUAL` metrics, there is no default selection for the starting month (it should default to `Calendar Year (Jan)`). 
I'm wondering if this is the right fix or if I should adjust the backend for these cases (when the backend sends `null` for `starting_month`). My adjustment might just be a bandaid if the backend is meant to send `1` for the `starting_month`. Open to your thoughts!
Closes #353

[Fix] Add starting month selection for an annual metric

---

publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx

Adjusts the padding of the dimension boxes for dimensions with really long names.
Example of current behavior:
Example w/ padding adjustment:
Closes #357

[Fix] Adjust dimension box padding to prevent arrow overlap in long dimension names

---

publisher/src/components/Forms/BinaryRadioButton.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx

Adjust spacing between context boxes to turn something like this:
Into this:
I double checked all other context box spacings and everything looks fine after this adjustment - but please let me know if you catch any strange spacing issues!
Closes #354 

[Fix] Add spacing between context items

---

common/types.ts
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
publisher/src/stores/MetricConfigStore.tsx

Adds metric-level and dimension-level descriptions in the Metric Configuration settings.
Demo:
https://user-images.githubusercontent.com/59492998/216123174-bc280b6a-942e-440f-81e5-ca7a99cb9780.mov
Closes #363 

Add metric and dimension descriptions in the Metric Config settings

---

publisher/src/components/Onboarding/Onboarding.tsx

Makes the following adjustments to the First Run Experience:
* Update copy for the Settings modal
Before:
After:
* Fix opacity overlay gap in data entry view
* Adjust positioning of Record Summary modal in responsive view (moved to bottom right corner)
* Adds text that lets a user know that the Record Summary is available in wider screens
https://user-images.githubusercontent.com/59492998/216125291-d302342b-9f45-4b6e-b30f-974ae636f834.mov
Closes #362 

Small adjustments to the First Run Experience

---

publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/stores/MetricConfigStore.tsx

Fix a couple issues with initializing metric config store values from this refactor: https://github.com/Recidiviz/justice-counts/pull/315
- Make sure to create nested objects so we can access them later
- Make sure to only create new nested objects if they hadn't been created yet
This fixes the two issues of not being able to load the metric config page and accidentally only setting one dimension in each metric.
|-----------------------------	|--------------------------------------------------------------------------------------------------------- …

Fix initializing metric config values

---

publisher/src/stores/ReportStore.test.tsx

Simplifies and removes `async` in one of our tests to prevent it from taking longer than 5 seconds to pass (which fails the CI test).
Closes #377

Adjust ReportStore tests to reduce the run time to < 5s

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/DataUpload/UploadedFiles.tsx
publisher/src/components/Loading/Loading.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/Settings/AgencySettings.tsx

Fix loader position within the Agency Settings, Uploaded Files and Metric Configuration components in the Settings so that it is more uniform and consistent. Introduced a more specific loader `ContainedLoader` that will take up the width of the container it is in as opposed to the full width and height of the entire screen.
Before:
https://user-images.githubusercontent.com/59492998/216488172-4a256fd9-5d40-4c32-8586-a72ef0f5267b.mov
After:
https://user-images.githubusercontent.com/59492998/216488210-59d6dca1-3607-4470-b6a2-4029503d1631.mov
Closes #355 

Fix loader position (make more consistent) between different settings pages

---

common/types.ts
publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx

Replacing the old `EXCLUDED_SYSTEMS` array that was a list of supervision subsystems with the `SupervisionSubsystems` constant to prevent a TypeError caught by @nichelle-hall (thank you for catching this!)
Test: https://nichelletest---justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/153
Additionally, fixes the reference path to downloading templates from the UploadErrorsWarnings component.
Closes #386 

[Fix] Replace EXCLUDED_SYSTEMS in Data Upload with SupervisionSubsystems

---

common/types.ts
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/UploadedFiles.tsx
publisher/src/components/Forms/Form.styles.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
publisher/src/components/MetricConfiguration/MetricsView.tsx
publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/Reports/PublishConfirmationSummaryPanel.tsx
publisher/src/components/Reports/ReportSummaryPanel.tsx
publisher/src/components/Settings/AgencySettings.styles.tsx
publisher/src/components/Settings/AgencySettingsBasicInfo.tsx
publisher/src/utils/helperUtils.ts

In general, this formats all areas the render a system name and specifically formats the Supervision system name to "Supervision (Combined)" if the Supervision system has subsystems (e.g. Parole, Probation, etc.)
Thanks to @lilidworkin's suggestion - there's a helper function that helps format the system name and if provided a list of systems can determine whether or not to add "(Combined)" to the Supervision system name. We'll just have to remember any time we're rendering a system name to feed it into the helper function for consistency.
Please let me know if there are areas I may have missed that render the system name. The only areas I was unsure about updating were 3 of the bulk upload screens:
Demo (Supervision agency with subsystems): …

Update Supervision name to be "Supervision (Combined)" for supervision agencies with subsystems

---

publisher/src/pages/NoAgencies.tsx

Adds a logout button to the no agencies screen - this is a follow up to the Team Management playtesting section. 
Closes #18444

add logout button to the no agencies screen

---

publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
publisher/src/stores/AgencyStore.ts

Throws toast when user is added to an agency that they are already a part of. 
[Loom](https://www.loom.com/share/c8d74036d7ca4a4a9e844aee54c889a9)

[Team Management] toast for error when user is already a part of an agency

---

publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Guidance/GuidanceHeader.tsx
publisher/src/components/Guidance/types.ts
publisher/src/stores/GuidanceStore.ts

Implements the frontend API calls to retrieve and save progress throughout the Guidance flow.
Demo:
https://user-images.githubusercontent.com/59492998/218617077-18f05808-ecb5-45d5-a4db-0a5e12c9c360.mov
Note: it looks like I clicked on Skip the first time - but I refreshed twice on each screen after the welcome screen - my mouse just showed up at the perfect spot.
Closes #408

Guidance: API

---

publisher/src/pages/Reports.tsx

Fixes persistent loading error message in Reports overview page. When there is an error in the Reports overview page, the error message persists when you switch to an agency that has no errors. This resets the `loadingError` back to `undefined` when there is no longer an error.
**Test:**
https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/
(Agency 161 is currently erroring and displaying an error message -- when you switch to a different agency, the error message goes away and the respective reports load.)
Closes #426 

[Bug] Resolve persistent error message in Reports overview page

---

publisher/src/stores/MetricConfigStore.tsx

The disaggregation toggles appear to always default to on (checked) and the dimensions off (unchecked) for every breakdown and saving doesn't appear to persist on the FE. The issue was in the initialization of the metric config store dimensions - there was no `enabled` property included in the store's dimensions object for the FE to read from. The fix is adding back the storage of `.enabled` property in the `initializeDimension` function.
Demo of out-of-sync behavior:
https://user-images.githubusercontent.com/59492998/220479226-1e9ab8de-ba7a-4308-84bd-e8a6d201cbcc.mov
--
Demo of correction:
https://user-images.githubusercontent.com/59492998/220479215-5173d92e-a011-445a-8b9f-da6764f82ef8.mov
Closes #420 
These boxes should be …

[Fix] Disaggregation and dimensions out of sync with the backend

---

publisher/src/components/Guidance/Guidance.styles.tsx
publisher/src/components/MetricConfiguration/Configuration.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/stores/MetricConfigStore.tsx

Addresses the following playtesting feedback related to breakdowns:
* (P0) Update breakdown help text copy
* (P0) For breakdowns - find another option aside from gray and similar styling to make it easy to scan
* (P0) More easily see which breakdowns are available/not available
* (P1) Collapse breakdown section when disabled
https://user-images.githubusercontent.com/59492998/220957156-154884a6-0f19-4618-b563-936e71dd4294.mov
Note: the logo missing on the top left is fixed by #417
Closes #433 

Guidance: Playtesting Followups - Breakdowns

---

publisher/src/components/Settings/AgencySettings.tsx

> Everyone can see jurisdictions section now in agency settings …

Remove admin flag for displaying jurisdictions

---

publisher/src/components/Guidance/Guidance.styles.tsx
publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Menu/Menu.tsx
publisher/src/stores/GuidanceStore.test.tsx
publisher/src/stores/GuidanceStore.ts
publisher/src/stores/MetricConfigStore.tsx

Allows users to switch agencies during the guidance flow.
Other small adjustments made:
* Bug with overflow container in metric configuration overview
* Alignment of long text in metric configuration overview
* Upload Data button text color bug when onboarding is complete
* Bug with disabling disaggregations and progress tracking (dimensions were still counted towards progress which prevented user for proceeding)
Closes #450

Guidance: Support switching agencies

---

publisher/src/components/Forms/TabbedDisaggregations.tsx
publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
publisher/src/components/MetricConfiguration/RaceEthnicitiesGridStates.ts
publisher/src/components/MetricConfiguration/types.ts
publisher/src/components/Reports/PublishConfirmation.tsx
publisher/src/stores/MetricConfigStore.tsx

Bug: Race/Ethnicities breakdowns do not update and intermittently crash when trying to access an invalid race/ethnicity.
Fix: Update the names for races & ethnicities to conform to what the backend sends.
* "Hispanic" is now "Hispanic or Latino"
* "Not Hispanic" is now "Not Hispanic or Latino"
* "American Indian / Alaskan Native" is now "American Indian or Alaska Native" 
* curious - should it be **Alaska** Native or **Alaskan** Native?
* "Native Hawaiian / Pacific Islander" is now "Native Hawaiian or Pacific Islander"
Closes #467

[Bug] Update the FE names for races and ethnicities to match what the backend sends

---

publisher/src/components/Guidance/Guidance.styles.tsx
publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Guidance/types.ts
publisher/src/stores/GuidanceStore.ts

In the Configure Metrics step of the guidance flow, the agencies that have multiple systems will now see the overview list split by system. For Supervision agencies with subsystems - this removes those metrics from the view (those metrics are marked as unavailable so removing them from view should be OK as they will not count towards progress/block progressing from this step).
Demo:
https://user-images.githubusercontent.com/59492998/222842285-cbb79f85-19e1-409e-9f7c-94ecfafdcae3.mov
Closes #466 

Guidance: Update Metric Configuration overview list for multi-system agencies & agencies with subsystems

---

publisher/src/components/Guidance/Guidance.tsx
publisher/src/components/Menu/Menu.tsx

Adjusts the rendering of the toast checklist when:
* a metric is disabled
* when a metric is disabled, no other steps are required
* this removes the other 3 required checklist items and only leaves the "Confirm metric availability" in the toast checklist
* all breakdowns are disabled
* when a breakdown is disabled, setting its definitions is no longer a required step
* this removes the "Confirm breakdown definitions" from the toast checklist
Demo:
https://user-images.githubusercontent.com/59492998/223276638-7d6e18c3-aba3-4526-a704-81af999a3231.mov
Closes #472 

Guidance: Playtesting II Followups - Metric Configuration Toast Checklist

---

publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx

Fixes spacing issues caused by long dimension names.
Spacing issues:
Adjustment:
Closes #468 

Metric Configuration: Adjustment for long dimension names

---

publisher/src/components/MetricConfiguration/MetricBox.tsx

Updates Metric Config overview metric boxes to show "Annually" instead of "Annual".
Before:
After
Contributes to #296 

Metric Configuration Overview: show "Annually" instead of "Annual

---

publisher/src/components/MetricConfiguration/MetricsView.tsx

> Fix automatic choose of disabled metric when change system while in desktop view in Data page
Type: Bug
| Type: Breaking …

Fix choosing disabled metric after system change

---

common/components/DataViz/utils.ts

Updates sorting logic for DataViz legend. Previously, we had "Unknown" and "Other" dimensions - solely. Now, the "Unknown" and "Other" dimensions are more specific (e.g. "Other Funding", "Unknown Staff", etc.) and that requires us to update the sorting logic to not strictly check equality of the strings "Unknown"/"Other" but whether or not those words are included in the string.
Closes #491

Update sorting logic for DataViz legend

---

publisher/src/stores/GuidanceStore.ts

Gates the guidance feature for all users who are **not** Justice Counts Admins. This is accomplished by setting all non-JC Admin's guidance progress to completed for all topics. JC Admins will have their guidance progress read from the DB as usual.
Contributes to #495

Guidance: Gate feature for non-JC Admins

---

publisher/src/components/Guidance/Guidance.tsx

Adjusts the completion logic for the ADD DATA step to only mark it complete if there is at least one draft report. Users who only have reports in `NOT STARTED` status will not have completed this step unless they input data in one of the reports (or explicitly save a report as draft).
Demo:
https://user-images.githubusercontent.com/59492998/225458167-353c8f55-6dd0-40c9-9506-83956fef0b1b.mov
(I created a report in this one - but this also works when there's already a report/s in the user's account in NOT STARTED status)
Closes #503

Guidance: adjust the step-completion logic for ADD DATA step

---

publisher/src/components/Menu/Menu.tsx

Removes permissions for agency dropdown menu (this was originally in place per PR #414 and was unintentionally restricted again).
Closes #509 

Remove permissions for agency dropdown menu

---

publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/types.ts

Previously, we considered metrics as being saved successfully via bulk upload if no errors were associated with those metrics. For example, the title below is shown when an empty template is uploaded (no data is saved).
We want to change this logic so that we consider metrics as being saved successfully via bulk upload if they are associated with datapoints in the database (if we actually persisted some data) and no errors were associated with those metrics.
Now, when an empty template is uploaded, the user sees the following:
When 1 metric was uploaded:
When 2 (or more) metrics were uploaded:
| Label                       	| Description …

[Bulk Upload] Adjust title / definition of a successfully saved metric 

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/types.ts

Greying out disabled metrics upon Bulk Upload:
1. When no data is uploaded for a disabled metric
2. When data is uploaded for a disabled metric …

[Bulk Upload] Grey out disabled metrics

---

publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx

Updates copy for Confirming breakdown availability from "Are you currently able to share any part of this metric?" to "Can you share data for this breakdown?"
Question: revisiting Matt's suggestion - is it strange to have the options as "Available"/"Unavailable" in response to this copy change? The previous copy with these options looks strange too now.
Closes #527 

Metric Config: Update copy for confirming breakdown availability

---

publisher/src/components/Menu/Menu.tsx
publisher/src/router/Router.tsx

Allows JC Admins to access the Records page and the Bulk Upload component (and see them actively in the nav bar) throughout each step of the Guidance flow.
Note: to test the guidance flow as a user would experience it, you'll need to use a non-JC admin account.
https://user-images.githubusercontent.com/59492998/228670294-70d8938c-46c6-4a20-8dd8-535720f6d074.mov
Closes #528 

Allow JC Admins to access Records / Bulk Upload during Guidance

---

publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/UploadReview.tsx
publisher/src/components/DataUpload/types.ts
publisher/src/components/Reports/Reports.styles.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx

Update the Bulk Upload review page to:
* display a list of reports being reviewed after ingest on the left side panel
* display a warning modal when a user attempts to publish if they have existing (modified) reports that will also be published
Demo:
User has existing reports that are modified by spreadsheet upload:
https://user-images.githubusercontent.com/59492998/229591843-8498458e-7594-4444-932c-1136842b9a36.mov
---
User has _**NO**_ existing reports that are modified by spreadsheet upload:
https://user-images.githubusercontent.com/59492998/229592092-da4662dc-2a25-476d-8b0a-32463f4ddbf2.mov
Closes #540 
Closes #559 
These boxes should be checked by reviewers …

Bulk Publishing: Update Bulk Upload Publish Confirmation (List of Reports + Warning Modal)

---

publisher/src/components/DataUpload/UploadReview.tsx
publisher/src/components/Reports/BulkActionReview.tsx
publisher/src/components/Reports/DataEntryReview.tsx

Goal: add basic error handling when publishing is unsuccessful and handle user refresh in the BulkActionReview and DataEntryReview pages
* Adds basic error toast when the bulk publishing is not successful.
* Previously, a refresh in the BulkActionReview and DataEntryReview crashed the app. Now, the BulkActionReview can handle a refresh and still persist data. The DataEntryReview will redirect a user back to the data entry form on refresh. I'm thinking there should be a way to persist this too and spent time trying to figure out, but kept coming up empty. I'll keep digging - but for now, we can redirect users back to the data entry form and avoid the crash behavior.
* Update on persisting the data entry review: 
* There's no way to do this without making another call to the backend. When a …

Bulk Publishing: Error handling & review page refresh fix

---

publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx

The Ethnicities column titles within the Race/Ethnicities grid header were not properly aligned with the on/off indicator cells beneath (the blue circles). This breaks the words so that they can be better aligned with the cells beneath. The entire Metric Config will be redone any way - so this is more/less a fix until then.
**Before**
**After**
Closes #520  

[Bug Bash] Fix spacing in Race/Ethnicities grid header

---

publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx
publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx

When a metric's availability is in a `null` state (no selection has been made), the metric's title & description on the right panel are under an overlay that greys them out. This PR removes that overlay from the metric title & description so they are always visible.
**Before**
---
**After**
https://user-images.githubusercontent.com/59492998/231305555-895953f3-52ca-4902-9e9f-aabd6a45afd4.mov
Closes #525

[Bug Bash] Remove overlay on top of a metric's definitions when a metric has no availability set  

---

publisher/src/components/Reports/ReportSummaryPanel.tsx

Within a report's Report Summary panel, the "Last modified by X" would always choose the name of the last person on the list of editors instead of the user who actually made the last edit. Since the user who made the last edit is the first on the list, this PR adjusts the `filteredReportEditors` to choose the first user on the editors list instead of the last.
**Before**
https://user-images.githubusercontent.com/59492998/231016133-6b3a2901-43ed-421c-8043-72e7ff7269c7.mov
**After**
https://user-images.githubusercontent.com/59492998/231015134-c362a4c2-a5ec-4107-a9c8-9b9976bdc544.mov
Closes #522 

[Bug Bash] Fix "Last modified by" section within a record's summary panel to show the name of the last user who modified the record

---

common/components/DataViz/DatapointsView.styles.tsx
common/components/DataViz/DatapointsView.tsx
publisher/src/components/DataViz/ConnectedDatapointsView.tsx
publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
publisher/src/components/MetricConfiguration/MetricsView.tsx

The Data page currently shows a chart for the first metric (regardless of whether or not it is enabled/disabled) when a user loads the page. It also does not currently handle a case where no metrics are enabled. This PR allows a user to see the first _enabled_ metric on load, and when no metrics are enabled, the user sees a message with a link to the Metric Configuration page. 
Currently, when there are no metrics enabled, the user just sees a loader that never resolves. Does this new message screen feel jarring or does it feel like it works within this context? Open to all thoughts!
Before:
https://user-images.githubusercontent.com/59492998/231017800-92ea5000-bcad-44ca-a51c-09e0bc247c62.mov
After:
https://user-images.githubusercontent.com/59492998/231018789-fbcb4410-919d-4b7c-9db7-b4031a0 …

[Bug Bash] Data Page: Show the first enabled metric for an agency on load and handle no enabled metrics case

---

publisher/src/components/Settings/AgencySettings.tsx
publisher/src/stores/AgencyStore.ts

This PR removes the call to the deprecated get_agency_jurisdictions() endpoint and instead calls the get_agency_settings() endpoint to retrieve an agency's jurisdictions. …

[Justice Counts] Jurisdictions GET refactor FE

---

publisher/src/stores/GuidanceStore.ts

Gates the entire backend call for non-JC admins as opposed to overwriting the completion boolean on each topic. 
* Non-JC-admins will not go through the guidance flow and the app will not make a call to the guidance endpoint
* JC-admins will go through the guidance flow based on their guidance status in the DB

Guidance: Gate entire backend call to non-JC admins

---

common/components/DataViz/DatapointsTableView.styles.tsx
common/components/DataViz/DatapointsTableView.tsx
publisher/src/components/Reports/BulkActionReview.tsx
publisher/src/components/Reports/DataEntryReview.tsx
publisher/src/components/ReviewMetrics/ReviewMetricsModal.tsx
publisher/src/components/ReviewMetrics/types.ts
publisher/src/stores/ReportStore.ts

Refactoring the `BulkActionReview` & `DataEntryReview` components to:
* show all metrics that have datapoints in the review page instead of only enabled metrics
* use the datapoints as the source of truth for the list of metrics and everything else needed by the review components
* this helps efforts to improve performance by minimizing excess calls to the backend
* consolidate similar logic
* render a consistent review page across all review components
* handle no datapoints consistently
Still left to figure out:
* handling Supervision agency with subsystems that have datapoints and the overall Supervision system is combined (it shows the subsystems' data in the review page - maybe this is the right behavior!)
Demo:
https://user-images.githubusercontent.com/59492998/233157121-0e7f5e0f-02a …

Bulk Publishing: Refactor for UX, code reusability and performance

---

publisher/src/components/DataUpload/UploadFile.tsx

Removes `.csv` from supported file types within the Bulk Upload page.
Closes #583 

Remove supported type `.csv` from the Bulk Upload home screen

---

publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.tsx

Makes the following styling adjustments:
* Centers text in the success modal after publishing an uploaded spreadsheet
* Before:
* <img width="528" alt="Screenshot 2023-04-25 at 5 42 05 PM" src="https://user-images.githubusercontent.com/59492998/234424097-4e447061-4f1e-4349-b037-a2a74bc3e839.png">
* After:
* <img width="528" alt="Screenshot 2023-04-25 at 5 41 53 PM" src="https://user-images.githubusercontent.com/59492998/234424100-4177cc93-c9fa-4dd9-a92c-3d7e95e9fd33.png">
---
* Reduces left panel width within the review page (where the list of metrics and reports live)
* Before:
* <img width="528" alt="Screenshot 2023-04-25 at 5 51 46 PM" src="https://user-images.githubusercontent.com/59492998/234424626-34672b8b-122a-4e66-89b0-b9fed3b7f0a7.png">
* After:
* <img width="528" alt="Screenshot …

Bulk Publishing: Follow Ups - Small Styling Adjustments

---

publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/Reports/DataEntryReview.tsx
publisher/src/stores/ReportStore.ts

Sorts the list of metrics on the publish review page to match the order of the metrics list in the data entry page. 
[Thank you Michelle & Lili for unblocking me w/ your great suggestions!]
https://user-images.githubusercontent.com/59492998/234736512-7533099b-e1dd-4cbe-bd64-944377b3fbc7.mov
Closes #590

Bulk Publishing: Follow Ups - Match order of metrics list in Data Entry and Publish Review pages

---

publisher/src/components/Menu/Menu.tsx

**Issue**: when you are on the `Data` page and you click on the `Data` link, you're redirected to the `Data` page with no query params, and will encounter the "There are no enabled metrics to view. Please go to Metric Configuration to enable a metric."
This is more/less a temporary fix - ~I need to dig deeper to figure out why things don't appear to be reinitializing~ (see below conversation). We're basically taking no action if a user is already on the page, and clicking on the link - which might be good to do anyway because doing a reinitialization seems excessive and not entirely necessary. Open to thoughts!
https://user-images.githubusercontent.com/59492998/235522899-898981cb-3773-434e-835a-4ead01e782ee.mov
These boxes …

[Bug] Clicking on Data link while in the Data page does not reload the page

---

publisher/src/components/DataUpload/DataUpload.tsx

Removes parenthesis from uploaded file name and replaces opening parenthesis with an `_` underscore and removes the closing parenthesis entirely. This takes care of the PHP WAF rule that kept triggering for file names with more than one set of parentheses.
Open to suggestions if you have other formatting ideas! I originally had a regex match and replace all parenthesis with a `_` but that made a file like `HELLO (1)(2).xlsx` become `HELLO _1__2_.xlsx` - which felt too strange. With these changes, the `HELLO (1)(2).xlsx` file name becomes `HELLO_1_2.xlsx`
Closes #594 

Bulk Upload: sanitize uploaded file name

---

publisher/src/components/Menu/Menu.tsx
publisher/src/stores/GuidanceStore.ts

Disabling the current guidance flow for all users as it's not currently being used/referenced. A task has been made to fully deprecate this (#621) - but I wasn't sure if that was necessary just yet.
Closes #XXXX

Disable Guidance flow for all users

---

publisher/src/components/MetricsConfiguration/MetricAvailability.tsx

Hides "Show All" button for metrics that only have one breakdown
https://github.com/Recidiviz/justice-counts/assets/59492998/908175f4-0028-4088-9ec1-7a3dbb9bcea2
Closes #619 

Metric Config: Hide "Show All" button for metrics that only have one breakdown

---

publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
publisher/src/stores/MetricConfigStore.tsx

Adds back the rendering of the descriptions for multiple includes/excludes and updates the key for the includes/excludes that have no descriptions from "null" to "NO_DESCRIPTION".
Before:
After:
https://github.com/Recidiviz/justice-counts/assets/59492998/900e5b87-0bfa-46c6-9ebe-fce9eecea2cb
Closes #624, [#20517](https://github.com/Recidiviz/recidiviz-data/issues/20517)

Metric Config: Render multiple includes-excludes descriptions

---

publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx

Renders any captured warnings for metrics in the `notUploadedMetrics` category (these are any metrics that have no errors and no datapoints).
https://github.com/Recidiviz/justice-counts/assets/59492998/d73a2db6-a866-4fb1-ab81-16cad3b9f5f6
Side mission: fix the button styling (both were showing up blue, with the "New Upload" having a grey border)
Closes [#20733](https://github.com/Recidiviz/recidiviz-data/issues/20733)

Bulk Upload: Render warnings (if any) for metrics that will not be uploaded

---

publisher/src/components/Settings/AgencySettingsSupervisions.tsx

Gates the `Edit populations` button to users who are not admins (AGENCY_ADMIN or JUSTICE_COUNTS_ADMIN).
While we wait to do a more thorough audit - I figured we could at the very last gate this to resolve the error that was brought up.
Demo: https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/ (feel free to use a non admin account/adjust your role in staging admin panel)
Contributes to #628 

[Fix] Restrict editing Supervision Populations to admins

---

publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx

Allows context values to count towards includes/excludes configuration. Basically, if you have no includes/excludes selected, entering any value in the context text box will give you an includes/excludes-has-been-configured checkmark.
https://github.com/Recidiviz/justice-counts/assets/59492998/bb789bfe-2a2b-44b0-83eb-c5b7cad3b184
Closes #631 

Context values within includes/excludes should "count" as configuring

---

common/components/ToggleSwitch/ToggleSwitch.styles.tsx
common/components/ToggleSwitch/ToggleSwitch.tsx
common/components/ToggleSwitch/index.ts
common/components/ToggleSwitch/types.ts
publisher/src/components/MetricsConfiguration/DefinitionModalForm.styled.tsx
publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.styled.tsx
publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx

The return of the Toggle Switch!
Adds reusable ToggleSwitch component to `common` repo and replaces clickable checkmarks within the `MetricAvailability`, `DefinitionModalForm`, and `RaceEthnicitiesModalForm` components w/ toggle switches.
Demo (would love a sanity check):
https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app
3 places to check:
* Metric Breakdowns in the Metric Availability screen
* Any definitions modal w/ includes/excludes
* Any Race & Ethnicities modal
Closes #635 

Metric Config: Replace checkmarks with toggles

---

publisher/src/components/MetricsConfiguration/DefinitionModalForm.styled.tsx
publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.styled.tsx

Revert to using toggles in definition modals & remove hover states.
Closes #635

Quick Adjustment: Use toggles in definition modals and remove hover states

---

common/components/DataViz/DatapointsTableView.styles.tsx
common/components/DataViz/DatapointsTableView.tsx
publisher/src/components/DataUpload/UploadReview.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
publisher/src/components/ReviewMetrics/types.ts

Refactors the bulk upload review page to handle and properly display multiple agency uploads. The review page treatment remains the same for single agency uploads.
Screenshot of multiple agency upload treatment w/ overwrites:
Question: does this look right for uploading overwrites? It doesn't show the Staff metrics in the review page, which I thought were included in the spreadsheet (albeit there were no changes there - I only changed the arrest metrics to trigger the overwrite)
Video comparing single agency vs multiple agency upload:
https://github.com/Recidiviz/justice-counts/assets/59492998/fc2221a0-c227-4a8d-b311-d5f1477b713c
Spreadsheet I've been using: 
[sample-super-agency-sheet-two-metrics.xlsx](https://github.com/Recidiviz/justice-counts/files/11568161/sample-super-agency-sheet-tw …

Refactor bulk upload review page to handle and properly display multiple agency uploads

---

common/components/DataViz/DatapointsTableView.styles.tsx
common/components/DataViz/DatapointsTableView.tsx
common/components/Modal/Modal.styled.tsx
common/components/Modal/Modal.tsx
common/types.ts
publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/UploadReview.tsx
publisher/src/components/DataUpload/types.ts
publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
publisher/src/components/ReviewMetrics/types.ts

Now that the BE sends reports' metadata, this updates the `UploadReview` logic to utilize the metadata for rendering instead of the report IDs + querying the `reportStore`.
Closes #653 

Adjustment to UploadReview logic to allow a super agency to publish for their child agencies

---

publisher/src/pages/Reports.tsx

The BE currently throws a JusticeCountsServerError when a user tries to delete records but is not a JC admin. The FE currently allows agency admins and JC admins to access the Bulk Actions > Delete button. This effectively gates the Delete action button to JC admins only in-line with the BE.
Let me know if there's a preference in not rendering it at all - for now I kept it in a disabled state for non-JC admins.
Closes #710
*Resolves the `JusticeCountsServerError - api.delete_reports` error

Gate the Delete functionality of Bulk Actions to JC Admins only

---

publisher/src/components/Settings/AgencySettingsDescription.tsx
publisher/src/components/Settings/AgencySettingsEditModeModal.tsx
publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
publisher/src/components/Settings/AgencySettingsSupervisions.tsx
publisher/src/components/Settings/AgencySettingsURL.tsx

> Transparent background for agency settings edit mode modals
| Type: Breaking Change       	| fix …

Nit #9: Change visual treatment for Agency Settings modal

---

publisher/src/components/Home/TaskCard.tsx
publisher/src/components/Home/helpers.ts
publisher/src/components/Home/types.ts
publisher/src/components/Reports/DataEntryForm.tsx

When a user clicks on the "Manual Entry" action link of a metric's task card and they are redirected to the latest record form - and the form loads as usual with the scroll position at the top of the page. This updates that transition and automatically scrolls a user to the metric on the form when they click on the "Manual Entry" action link.
https://github.com/Recidiviz/justice-counts/assets/59492998/7db87f51-4303-48ef-9850-98f1faab336a
Closes #705

Home Page: Scroll to metric in Data Entry Form after clicking on "Manual Entry" action link in task card [3/n]

---

publisher/src/components/Home/Home.styled.tsx
publisher/src/components/Home/Home.tsx
publisher/src/components/Home/TaskCard.tsx
publisher/src/components/Home/helpers.ts
publisher/src/components/Home/types.ts
publisher/src/components/Reports/DataEntryForm.tsx

Adds system selector buttons (for agencies with multiple systems) to toggle the home page task cards based on system.
Preview:
https://github.com/Recidiviz/justice-counts/assets/59492998/70c27a9b-f443-438c-a717-da67d39fb05b
[Would love a sanity check of the supervision with subsystems cases if folks have the bandwidth.]
Closes #716 

New Homepage: Support agencies with multiple systems [2/n]

---

publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
publisher/src/components/Settings/AgencySettings.styles.tsx
publisher/src/components/Settings/AgencySettingsDescription.tsx
publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
publisher/src/components/Settings/AgencySettingsURL.tsx

Adds red text color treatment to Metric Configuration "Action Required" title and adds red "Action Required" text to agency settings with no values entered.
https://github.com/Recidiviz/justice-counts/assets/59492998/2c85f288-c467-4989-8dcf-ec3e01169776
Closes #672 

Agency Settings & Metric Config: Action Required treatment

---

publisher/src/components/Home/Home.tsx
publisher/src/components/Home/helpers.ts
publisher/src/components/Home/types.ts
publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/ReviewMetrics/helpers.ts
publisher/src/stores/ReportStore.ts

Random bug fixes from testing:
* Fix links back to home to include agency ID
* Fix crash issue due to `latestRecordsAndMetrics` logic in `ReportStore` - properly handles cases when no monthly &/ annual records are sent
* Fix switching agencies bug by updating the `currentSystem` when user switches agencies
* Fix issue with `hasCompletedAllTasks` - now determined by the task card arrays used for rendering (prev. solution was not sufficient for all cases)

New Homepage: Bug Fixes [6/n]

---

publisher/src/components/Home/Home.tsx
publisher/src/components/Home/TaskCard.tsx
publisher/src/components/Home/helpers.ts
publisher/src/components/Home/types.ts
publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/ReviewMetrics/helpers.ts
publisher/src/stores/ReportStore.ts

In PR #682 - there was a temporary solution in place for users without records (or without a record tied to a metric - e.g. a monthly metric but the user has 0 monthly records) - if there is no record, the task card doesn't appear. 
After discussing with product and design, we realized a better solution would be to still display all metrics (because users without records can still technically upload a spreadsheet), but link the "Manual Entry" action link to the Create Record page if a metric doesn't have any records to link to.
https://github.com/Recidiviz/justice-counts/assets/59492998/eea4ec5a-6afe-4864-bca5-3bdb60cb5bb5
Closes #744 
These boxes should be …

Home Page: Link “Manual Entry” action link to Create Report page for users who do not have a records [5/n]

---

publisher/src/components/DataUpload/UploadedFiles.tsx

We decided to (for now) remove users' ability to delete uploaded files in Settings > Uploaded Files page.
Closes #755 

Remove Delete button in UploadedFiles

---

publisher/src/components/Forms/TabbedDisaggregations.tsx

Fixes bug in the data entry form's dissaggregation tabs where the checkmarks would sometimes appear, and other times not appear at all.
Closes #697 

[Bug] Fix checkmark bug in Record disaggregation tabs

---

common/components/Badge/Badge.tsx
common/components/Dropdown/Dropdown.styled.tsx
common/components/GlobalStyles/Palette.ts
common/components/HeaderBar/HeaderBar.styled.tsx
common/components/HeaderBar/HeaderBar.tsx
common/components/Toast/Toast.ts
publisher/src/components/Auth/VerificationPage.tsx
publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.styled.tsx
publisher/src/components/DataUpload/DataUpload.styles.tsx
publisher/src/components/Footer/Footer.styles.tsx
publisher/src/components/Forms/Form.styles.tsx
publisher/src/components/Header/Header.tsx
publisher/src/components/Home/Home.styled.tsx
publisher/src/components/Menu/Menu.styles.tsx
publisher/src/components/Menu/Menu.tsx

Implements a P0 of tablet & mobile responsiveness. It's not 100% to spec - the only thing missing is the profile and agency dropdowns appearing at bottom (Figma screenshot below) -
-- for now, the dropdowns appear as they usually do.
Demo:
https://github.com/Recidiviz/justice-counts/assets/59492998/226d9b67-26b6-4d27-bab5-f677eaf8a478
Closes #668

New Homepage: P0 Mobile Responsiveness [7/n]

---

publisher/src/components/Home/Home.tsx
publisher/src/components/Home/helpers.ts

There was an issue with supervision subsystem metric task cards that were incorrectly linking the "Manual Entry" to the Create Record page (thank you for catching this, Michelle!). This was because the supervision subsystem metric objects have a default `null` value in the `starting_month` property. When we create task cards, we need a `starting_month` for annual metrics in order to link them to the appropriate latest annual record.
To solve for this, when we create task cards, before assigning the `startingMonth` we can do a boolean check of `metric.disaggregated_by_supervision_subsystems`. If it's `true`, then we can assume this is a supervision subsystem that will have a `null` value for `starting_month`, so we check the parent `SUPERVISION_<METRIC KEY>` metric object for the …

New Homepage: Playtesting Followups (P0)

---

common/components/Tooltip/Tooltip.styled.tsx
publisher/src/components/DataViz/MetricsDataChart.styled.tsx
publisher/src/components/DataViz/MetricsDataChart.tsx
publisher/src/components/Forms/TabbedDisaggregations.tsx
publisher/src/components/Home/Home.tsx
publisher/src/components/Home/helpers.ts
publisher/src/components/Reports/DataEntryReview.tsx

Addresses the following P1 items:
* Fixes “(No Enabled Metrics)” text overflow in Data Viz page
* Adds system name in parenthesis on metric task cards for multi-system agencies (in the “All” filtered stated)
* Fixes Tooltip’s capitalized text-transform
* Updates “Your data is updated and published” copy to “Your data is up-to-date and published”
* Removes Metric Settings button
* Fix Publish review metric checkmarks (sometimes they show, other times they do not)
Demo:
https://github.com/Recidiviz/justice-counts/assets/59492998/cd67bc62-8cbf-4c02-8995-930a2d6cc863
Closes #761 

New Homepage: Playtesting Followups (P1)

---

publisher/src/components/Home/TaskCard.tsx
publisher/src/components/Menu/Menu.tsx
publisher/src/components/Reports/CreateReport.styled.tsx
publisher/src/components/Reports/CreateReport.tsx

When a user clicks on the "Manual Entry" link in a metric's 'add data' task card and there are no records that match the metric's frequency, the user is redirected to the Create Record page where they will now see the following copy that will explain how they got there:
"It looks like there are no records for the metric you would like to manually input data for. Please create a new record."
Took some small liberties design and copy-wise - _**always**_ open to suggestions to improve both!
https://github.com/Recidiviz/justice-counts/assets/59492998/ac17f9f6-12a4-402e-816a-e07236b52a81
Closes #761

New Homepage: Playtesting Followup - add helpful message to Create Records page when redirected from task card

---

publisher/src/App.tsx
publisher/src/components/Auth/Maintenance.tsx

Adds a basic down-for-maintenance page.

Add basic down-for-maintenance page

---

common/components/GlobalStyles/Typography.ts
common/components/Modal/Modal.styled.tsx
common/components/Tooltip/Tooltip.styled.tsx
common/components/Tooltip/Tooltip.tsx
publisher/src/components/Home/TaskCard.tsx
publisher/src/components/Home/helpers.ts
publisher/src/components/Menu/Menu.tsx

* Adds tooltip to `Upload Data` action links to clarify to the user that they can include other metrics within the same file upload; to help avoid the assumption that by clicking the `Upload Data` link on a metric task card, that they can only upload for that metric. (Always open to better copy suggestions!)
* Updates the menu link names (to be more calls-to-action)
Link: https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app
Closes #786 

New Homepage: CSG Playtesting Followups

---

publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx

For the new standalone errors/warnings page, the 'Close' button did not lead anywhere when clicked. Since this is a 'standalone' page, we assume that the user does not have a previous page in the history stack. So  `onClick={() => navigate(-1)}` does not go anywhere. To resolve this, this PR changes the onClick so that the user is navigated to the home page when the click the 'Close' button.
Before:
https://github.com/Recidiviz/justice-counts/assets/82831800/d640abf1-9dde-431b-910b-3760575fa748
|----------------------------- …

[Justice Counts] Standalone Errors/Warnings Page Close Fix

---

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
agency-dashboard/src/NotFound/NotFound.tsx

Removes dependency tracking and management from AgencyOverview
Relates to #770
* Navigate to playtesting https://alfonsotest---agency-dashboard-web-b47yvyxs3q-uc.a.run.app/
* Click on an agency
* Verify that agency loads after some loading time during which you see the spinner

Remove useEffects from AgencyOverview

---

agency-dashboard/src/App.tsx
agency-dashboard/src/Home/Home.tsx
agency-dashboard/src/stores/API.ts

Hides the home page in production (`path="/"`) and displays the 404 not found page instead.
https://github.com/Recidiviz/justice-counts/assets/59492998/9316b1b0-4c4b-497c-93bf-f8d04c90ac49
Closes #772

[Agency Dashboard] Hide homepage in production

---

publisher/src/components/Home/Home.tsx
publisher/src/components/Reports/DataEntryReview.tsx

Quick bug fix - checks for `metricDisplayNames` before sorting - otherwise, if metricDisplayNames comes up `undefined`, this page crashes.
[This might've only happened while I was moving things around in my refactor and may not happen in practice - but, it exposed this possibility.]

[Bug] DataEntryReview sometimes crashes when metricDisplayNames is initially undefined

---

publisher/src/components/Home/Home.styled.tsx

Quick follow up to @morden35's snake case fix (thank you again so much!) - adjusts the styling so the system name doesn't wrap:
From:
To:

[Publisher] Styling fix for long system names

---

publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx

Removes HeaderBar label from standalone errors/warnings page because it is not needed.
Before:
After:
Closes #861

[Publisher] Remove HeaderBar label from standalone errors/warnings page

---

agency-dashboard/src/AgencyOverview/AgencyOverview.test.tsx
agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
agency-dashboard/src/App.tsx
agency-dashboard/src/DashboardView/DashboardView.tsx
agency-dashboard/src/Protected/Protected.tsx
agency-dashboard/src/Protected/index.ts
agency-dashboard/src/utils/index.ts

Moves the allowlist logic to a `<Protected>` component that will determine whether or not an agency's overview and dashboards are available to be viewed. Proposed option for https://github.com/Recidiviz/justice-counts/pull/882.

[Proposal][Agency Dashboards] Move allowlist logic up a level to a "wrapper" component

---

agency-dashboard/src/utils/formatting.ts
common/components/DataViz/BarChart.tsx
common/components/DataViz/MetricsCategoryBarChart.tsx
common/components/DataViz/Tooltip.tsx

Removes all instances of the word "reported". We don't export the `REPORT` constants from Publisher into the `common` repo. 
We could move it to the `common` repo and update all our imports in Publisher, but I think it's OK for now for us to manually write `record` in these few spots in `common` repo since the usage of the word has been pretty stable so far. Happy to work on this if anyone disagrees - just didn't seem worthwhile to do at the moment.

Remove "report" word from `common` repo

---

agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
agency-dashboard/src/Header/HeaderBar.styles.tsx
agency-dashboard/src/utils/formatting.ts
common/components/DataViz/CategoryOverviewBreakdown.styles.tsx
common/components/DataViz/CategoryOverviewBreakdown.tsx
common/components/DataViz/CategoryOverviewLineChart.tsx
common/components/DataViz/types.ts
common/components/DataViz/utils.ts
common/utils/dateUtils.ts

Feature
Navigate to https://alfonsotest---agency-dashboard-web-b47yvyxs3q-uc.a.run.app/agency/department-of-corrections/capacity-and-costs
Observe the breakdown values in order matching the magnitudes in the chart. 
Observe the updated formatting of values
Closes #22950

[#22950] [Agency Dashboard] breakdown chart updates

---

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
common/components/DataViz/CategoryOverviewBreakdown.tsx
common/components/DataViz/CategoryOverviewLineChart.tsx

There were a couple of agencies that crashed during my testing (see demo). I am playing a bit of whack-a-mole here until a proper refactor.
No other agencies were affected by this - it looks like there are a few spots where the property we're trying to access is undefined and unhandled (either something strange with their datapoints or empty datapoints aren't handled properly). 
https://github.com/Recidiviz/justice-counts/assets/59492998/6c5c9692-c5c5-4365-8044-dfb61d3d1f54

[Bug][Agency Dashboard] Add checks additional checks for data to prevent crashing

---

agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
agency-dashboard/src/Protected/Protected.tsx

`AgencyOverview` used the following logic to render the list of metrics:
```
const metricsByCategory =
agencyDataStore.metricsByCategory[category] || [];
const metricsByCategoryBySystem = metricsByCategory.filter(
(metric) => metric.system.key === currentSystem
);
...
const metricsWithData = metricsByCategoryBySystem.filter(
(metric) =>
agencyDataStore.datapointsByMetric[metric.key].aggregate.filter(
(dp) => dp[DataVizAggregateName] !== null
).length > 0
);
```
Whereas `CategoryOverview` used the following logic:
```
const categoryMetrics = useMemo(
() =>
categoryData[category]?.key
? agencyDataStore.metricsByCategory?.[categoryData[category]?.key]
: [],
[agencyDataStore.metricsByCategory, category]
);
```
This created situations where `AgencyOverview` and `CategoryOverview` were …

[Agency Dashboard] Use same source of truth/calc for list of metrics between AgencyOverview and CategoryOverview

---

publisher/src/components/DataViz/MetricsDataChart.tsx

Issue:
If an agency has no enabled metrics and go to the Explore Data page, Publisher crashes because it is not properly handling the no-metrics case.
Solution:
Add a check to `enabledMetrics[0]` incase it is undefined before accessing the key.
[Huge thank you to Jessica for catching this bug!]

[Bug][Publisher] Fix Explore Data crash when agency has no enabled metrics

---

publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
publisher/src/components/primitives/index.tsx

Adds copy within the Metric Settings overview for the non-superagency systems clarifying that the settings they enter will become the defaults for child agencies - but, those child agencies can override the default.
Example (this only appears on the non-superagency systems' metric overview):
Closes #874

Superagencies: Add copy for non-superagency systems within Metric Settings

---

publisher/src/components/DataViz/MetricsDataChart.styled.tsx
publisher/src/components/DataViz/MetricsDataChart.tsx
publisher/src/components/primitives/index.tsx

Update Explore Data to only show Superagency data for superagencies and add a message with instructions on how to view child agency data.
Before:
After:
Closes #875, #876

Superagencies: Only show superagency system data and add copy explaining how to view child agency data

---

publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/stores/FormStore.test.tsx

As a follow up to the buggy line that was introduced that caused previously saved report values to overwrite recently updated values - this test should provide coverage to ensure that between the DataEntryForm and DataEntryReview components that the data in the FormStore (which is what ultimately gets sent to the BE to be saved) remains consistent. 
In the case where the bug was introduced, the values in the FormStore between DataEntryForm and DataEntryReview were different, and Publishing is what officially saved the values.
Test in action (without and with the buggy line):
https://github.com/Recidiviz/justice-counts/assets/59492998/c076b02c-ee62-4b6a-9454-97c663d84ced
Closes #895 
These boxes should be checked by the …

[Test] Add FormStore test to cover buggy line addition in DataEntryReview

---

publisher/src/components/Home/TaskCard.tsx
publisher/src/stores/FormStore.ts

Implements an alternative solution to validating metrics when going from a publish task card in the Home page directly to the Publish Review page. 
When a user goes to the `ReportDataEntry` > `DataEntryForm` component via opening a record, the previously saved values are loaded and validated in the FormStore so that they appear in the form, and thus, the review page will have validated values it can check to show the appropriate checkmark for each metric. 
Currently, if a user is going directly to the `DataEntryReview` page without having opened up the record in question, the FormStore will have no values loaded for that record - thus, the validation checkmark logic in the review page will have nothing to validate. 
This solution updates the logic in the publish task card and checks to …

Fix metrics list validation in Publish Review page when coming from a publish task card in the Home page

---

common/components/Dropdown/Dropdown.styled.tsx
common/components/Dropdown/Dropdown.tsx
common/components/GlobalStyles/Palette.ts
publisher/src/components/Menu/Menu.tsx

Adds a typeahead search input in the agency dropdown menu to help filter agency options.
https://github.com/Recidiviz/justice-counts/assets/59492998/17ec0d07-9d94-4afa-980b-538329526908
Playtesting Link: https://mahmoudtest---justice-counts-web-qqec6jbn6a-uc.a.run.app/agency/161/
Closes #877

Add typeahead search in agency dropdown menu

---

common/components/DataViz/MetricInsights.tsx

Changes "Year-to-Year" text in the Data Viz charts to "Percent Change".
Closes #920

Data Viz: Change "Year-to-Year" text to "Percent Change"

---

common/components/Dropdown/Dropdown.tsx

Matt (CSG) surfaced an issue with the agency dropdown causing weird behavior with navigation as described below:
"If you log in and then select a new agency from the drop down in the upper left menu, then navigate to any of the menu items using the upper left menu dropdown, it returns you to the agency you originally logged in as, rather than the agency that you've selected"
There was another issue with the agency dropdown where if you select an agency, the highlight icon doesn't update (e.g. you're in Agency 1 when you first login, then switch to Agency 2 - the dropdown highlight icon is still on Agency 1). These two issues are surprisingly related - and all to do with us not having a fresh copy of the dropdown `options` from the parent `Menu` component.
I made an incorrect assumption by …

[Bug] Fix out-of-sync behavior in agency dropdown menu 

---

agency-dashboard/src/DashboardView/DashboardView.tsx
agency-dashboard/src/stores/AgencyDataStore.ts
agency-dashboard/src/utils/index.ts
agency-dashboard/tsconfig.json
common/utils/downloadHelpers.ts
common/utils/index.ts
publisher/src/components/DataViz/MetricsDataChart.tsx
publisher/src/setupProxy.js

Enables CSV download from Explore Data table view download button (which was only implemented in Agency Dashboards). Currently, the button does nothing in table view.
https://github.com/Recidiviz/justice-counts/assets/59492998/058fb138-536b-4fef-9cb4-16be31d84c78
Closes #923 

[Publisher] Enable CSV download from Explore Data table view

---

publisher/src/components/Forms/Form.styles.tsx
publisher/src/components/Reports/DataEntryForm.tsx

During playtesting, Michelle noticed something strange with the monthly records for superagencies that did not have their metrics configured. The record would display the following:
The reason why this is happening is because all of the current superagency metrics have a default **ANNUAL** frequency and no metrics with a default **MONTHLY** frequency. So in a situation where the superagency has no metrics configured, opening up a monthly record will result in the above screenshot.
This change handles these cases by adding copy within monthly records that nudge the user to go to the Metric Settings page to configure their metrics.
Closes #928 
These boxes should …

Superagency: Playtesting Followup - UI adjustment for monthly records for superagencies with no configured metrics and only default annual metrics

---

publisher/src/components/Global/constants.ts
publisher/src/pages/Reports.tsx

Corrects `REPORTING_PERIOD_CAPITALIZED` constant to say "Recording Period" instead of "Reporting Period". [We totally missed this one in our reviews during the Records page refresh ~6 months ago]

[Publisher] Correct REPORTING_PERIOD_CAPITALIZED constant to say "Recording Period" instead of "Reporting Period"

---

agency-dashboard/src/utils/denylist.ts

Removes Agency #544 from deny list. [I missed this request when it was originally made]

[Agency Dashboards] Remove agency from deny list

---

agency-dashboard/src/utils/formatting.ts
common/components/DataViz/CategoryOverviewBreakdown.tsx
common/components/DataViz/types.ts
common/hooks/useLineChartLegend.ts

During a playtesting of Agency 496's dashboard in production, there were times when hovering over a chart crashed the app. This is not easy to reproduce since the charts re-render so often based on mouse movement, but there are times during the transition between Recent and All, where hovering back on a chart after switching the `datapoint` returned by `getHoveredDatapoint` comes back as `undefined`. This happens when there are no datapoints w/ a date that matches the `hoveredDate` - and this in turn causes a crash within the `transformDataForLegend` logic when we set the value for `dimensionsValueFill`. This at the very least handles the `undefined` cases (and hopefully prevents similar crashes).
I'm still trying to figure out why there's a brief mismatch sometimes and it's a bit of a …

[Agency Dashboards][Bug] Intermittent crash when hovering on charts 

---

common/hooks/useLineChart.ts

Stephanie from CSG reported a crash happening in https://dashboard-staging.justice-counts.org/agency/supervision-[demo]/capacity-and-costs
It seems that the `disaggregations[disaggregationKey]` came up as undefined - I'm still investigating why, but this will handle that case and prevent the page from crashing.
Tested this locally running staging as the backend. I tested a couple of other agencies to make sure things were working OK.

[Bug] Agency Dashboards: Handle undefined disaggregations when getting line chart data from metrics

---

common/package.json
yarn.lock

Manual bump of `@babel/preset-env` in `common`. This was the intention of this dependabot generated PR (https://github.com/Recidiviz/justice-counts/pull/954) but the FE tests kept failing in the CI (I couldn't quite figure out why - probably due to some caching within babel? Or the yarn.lock went out of sync when I was merging in other core dependencies?). Anyway, it wasn't worth sinking more time into, so I'm doing a manual upgrade for this dependency.

Manual bump @babel/preset-env from 7.22.7 to 7.22.20 

---

agency-dashboard/src/AgencyOverview/AgencyOverview.styles.tsx
agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
agency-dashboard/src/CategoryOverview/CategoryOverview.tsx

Addresses the following playtesting follow-up items:
* Adds visible demo label under agency name in Agency Overview page
* Adds the agency title above the metric category title in the Category Overview page
https://github.com/Recidiviz/justice-counts/assets/59492998/94096d2e-e191-4fed-b570-c20869bf4d14
Closes #942 

[Agency Dashboards] Playtesting Followup - Add demo label under agency name and add agency name to category page

---

common/components/DataViz/BarChartComponents.tsx
common/components/DataViz/MetricsCategoryBarChart.tsx
common/components/DataViz/types.ts

Right-aligns the y-axis tick values in the bar chart.
Before:
After:
Contributes to #948 

[Agency Dashboards] Playtesting Followup - Right align y-axis in bar chart

---

agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
common/components/DataViz/CategoryOverviewBreakdown.styles.tsx
common/components/DataViz/CategoryOverviewBreakdown.tsx
common/components/DataViz/CategoryOverviewLineChart.tsx
common/components/DataViz/types.ts
common/hooks/useLineChartLegend.ts

Hides individual breakdowns in the line chart legend instead of showing "Not Recorded".
https://github.com/Recidiviz/justice-counts/assets/59492998/ab9facab-b364-4058-b975-678a6cfaa7d1
Closes #963 

[Agency Dashboards] Playtesting Followup - Hide individual breakdowns that have no value in Line Chart legend instead of showing "Not Recorded"

---

agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
agency-dashboard/src/CategoryOverview/CategoryOverview.tsx

For multi-system agencies - instead of displaying all of the metric charts for each system in one page (in the Category Overview page), this will allow you to filter the metric charts by system (via system chips  - similar to the Agency Overview page). This will only appear for agencies with multiple systems.
https://github.com/Recidiviz/justice-counts/assets/59492998/243e1ac3-0265-4b50-9a65-ce23e5705a7f
Closes #959

[Agency Dashboards] Playtesting Followup - Filter charts by system in Category Overview page

---

common/components/DataViz/CategoryOverviewBreakdown.tsx
common/components/DataViz/CategoryOverviewLineChart.tsx
common/hooks/useLineChart.ts

Filters out datapoints in the line chart with `null` aggregate total value (similar to how the bar chart filters null datapoints). This handles the edge case where an agency publishes an empty record - currently, the empty record will not appear on the bar charts (because the aggregate `Total` will be `null` and its filtering those out), but does appear on the line charts (which is not filtering for `null` aggregate totals).
https://github.com/Recidiviz/justice-counts/assets/59492998/63626345-6f73-42b7-84ff-dbdc4884372a
Closes #946 

[Agency Dashboards] Playtesting Followup - Filter out datapoints with no aggregate values when rendering the line chart 

---

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
agency-dashboard/src/CategoryOverview/CategoryOverview.tsx

Small clean up and fixes a couple of things:
* A crash that happens when users go to the `.../agency/agency-name/capacity-and-cost/` directly (without clicking into the Category Overview page from the Agency Overview page)
* When an agency has multiple systems, there's a chance that the default system that shows in the Category Overview page will be a system without data - at which point no metrics, charts or breakdowns will render. 
https://github.com/Recidiviz/justice-counts/assets/59492998/79680f00-0951-4019-86c9-6a94814f847a

[Agency Dashboards] Small Fix & Clean Up

---

publisher/src/components/DataViz/MetricsDataChart.styled.tsx

Fixes the overlapping issue CSG pointed out in the Data Viz page where the list of systems and metrics on the left side was overlapping with the "Notes" section.
**Before**
**After**
Closes #999

[Publisher] Styling Fix in Data Viz page

---

agency-dashboard/src/stores/AgencyDataStore.ts
common/utils/downloadHelpers.ts
publisher/src/components/DataViz/MetricsDataChart.tsx

Updates where we fetch the agencies uploaded data to confirm that only logged-in users can access CSVs containing all uploaded data. 
[Companion BE PR](https://github.com/Recidiviz/recidiviz-data/pull/24903)

get csv for agency data from protected endpoint

---

publisher/src/components/Menu/Menu.tsx

Removes duplicate state codes in agency's name within the agency dropdown menu. The current logic appends the state code to each agency in the dropdown menu - so if an agency's name is "Department of X (CA)" it will render as "Department of X (CA) (CA)" in the menu. This adjustment checks to see if the state code (in parenthesis) is already included in the agency's name - and if so, it will not append a state code.
Demo (the agency has the state code directly in its name):
https://github.com/Recidiviz/justice-counts/assets/59492998/b0b329a6-38ca-459c-b5e5-7068322d9b9a
Closes #1038

[Publisher] Remove duplicate state codes in agency name within the agency dropdown menu

---

publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx

I noticed a bug when I was playing around with the Help Center in production specifically in the link to Agency Dashboards. I was taken to the staging URL which resulted in an error - instead of the production URL. For some reason the piece of logic that creates the URL based on the environment isn't picking up on the right environment. I suspect it is because when this component is mounted, the `api.environment` is first `undefined` until it is set - and since these components aren't `observer`s they might not have been re-rendering when `api.environment` is set and have thus defaulted to the staging URL.
I tried to log the `api.environment` and deploy to playtesting with and without the `observer` and it logged `staging` for both - so my hunch might be off. But regardless, both …

[Bug] Fix link from Help Center to Agency Dashboards for production users

---

publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
publisher/src/components/MetricsConfiguration/MetricAvailability.tsx

We received a request from CSG to include a link to define metrics (includes/excludes) on the top aggregate level metric for metrics with no breakdowns - because the top aggregate level metric will still have includes/excludes to define (and currently, we only show this link when a metric has breakdowns). This change moves the `Define Metrics ->` from within the `hasDisaggregations` conditional, so it will always appear when a metric is enabled. 
I also felt an itch to update the copy a little bit to "Define Metric and Breakdowns" or "Define Metric" depending on whether or not there are breakdowns - let me know your thoughts!
Metric w/ breakdowns:
Metric w/out breakdowns:
Closes #1093
These boxes should be checked by the …

[Justice Counts] Add "Define Metric ->" link to all aggregate metrics in metric configuration

---

common/types.ts
common/utils/helperUtils.ts
publisher/src/components/AdminPanel/AdminPanel.test.tsx
publisher/src/components/AdminPanel/UserProvisioning.tsx
publisher/src/components/AdminPanel/types.ts
publisher/src/components/Reports/CreateReport.test.tsx
publisher/src/stores/AdminPanelStore.test.tsx
publisher/src/stores/AdminPanelStore.ts
publisher/src/stores/AgencyStore.ts

Adds Agency Provisioning related methods and helpers in the `AdminPanelStore` and updates types. This is more/less the "backend" of the frontend - all of these methods will be plugged into the UI and used to update the changes made in the Agency Provisioning view to send off to the BE.
Contributes to #1051 

[Publisher] Admin Panel: Agency Provisioning - Store Updates (2/n)

---

publisher/src/components/AdminPanel/AdminPanel.test.tsx
publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/components/AdminPanel/types.ts

Implements the create/edit agency modal for the Agency Provisioning flow. There are two tabs in this modal - 
1. Agency Information - allows you to edit information related to the agency
2. Team Members - allows you to add, remove, and/or assign roles to users connected to this agency (will be implemented in the next PR)
Demo (creating new/editing existing agency):
https://github.com/Recidiviz/justice-counts/assets/59492998/21a0e40f-1c5e-4ad7-b5bf-cc238835f905
https://github.com/Recidiviz/justice-counts/assets/59492998/25ea6bb6-1444-42ee-894e-2c6aef988962
Contributes to #1051

[Publisher] Admin Panel: Agency Provisioning - Create/Edit Agency Information (4/n)

---

publisher/src/App.tsx
publisher/src/components/Auth/AuthStore.ts
publisher/src/components/Menu/Menu.tsx

Adds an entry point to the admin panel via the profile dropdown menu in Publisher and creates a new Global Justice Counts Admin role in Auth0 (staging for now) that will be used to gate access to the admin panel. It might be worth updating the backend as well to secure these endpoints since the flags set on the FE won't provide full security (task https://github.com/Recidiviz/recidiviz-data/issues/26006). 
Here's what I updated in our tenant in staging:
* Under **User Management > Roles**, I created a `justice-counts-admin` role (referred to as "Global" Justice Counts admin here in the codebase to differentiate from Publisher's JC admin role - let me know if you have better ideas!)
* Under **Actions > Flows > Login**, I updated the `Add custom claims to tokens` post-login script and added …

[Publisher] Admin Panel: Admin Panel Role & Publisher Entry Point

---

publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/AdminPanel.test.tsx
publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/components/AdminPanel/types.ts
publisher/src/stores/AdminPanelStore.ts

Implements the final piece to the Agency Provisioning flow - adding/removing users and updating their roles. 
At this point of the stacked PRs, you should be able to create or edit an agency, add/update all of the agency's information, and add/remove team members in a single request (huge shout out to Nichelle for all the BE work to make this possible).
Update:
- One more thing I forgot to include (thank you for the reminder, Lili!) - there's also additional logic that automatically adds CSG users and their corresponding roles as team members when trying to create a new agency. This was previously accomplished in the backend because the current admin panel's flow is: go to Agency Provisioning view and add a team member -> request sent to the BE, and BE adds the roles -> go to separate …

[Publisher] Admin Panel: Agency Provisioning - Team Members (5/n)

---

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
agency-dashboard/src/stores/AgencyDataStore.ts
common/types.ts
publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
publisher/src/components/AdminPanel/types.ts
publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/SystemSelection.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/UploadFile.tsx
publisher/src/components/DataUpload/UploadedFiles.tsx
publisher/src/components/DataViz/MetricsDataChart.tsx
publisher/src/components/Home/types.ts
publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
publisher/src/components/Reports/DataEntryForm.tsx
publisher/src/components/Reports/PublishConfirmationSummaryPanel.tsx
publisher/src/components/Reports/ReportSummaryPanel.tsx
publisher/src/components/Settings/AgencySettingsSupervisions.tsx
publisher/src/components/Settings/types.ts
publisher/src/components/Settings/utils.ts
publisher/src/stores/AdminPanelStore.ts
publisher/src/stores/AgencyStore.ts
publisher/src/stores/HomeStore.ts
publisher/src/stores/MetricConfigStore.tsx
publisher/src/stores/ReportStore.ts
publisher/src/utils/helperUtils.ts

Implements special handling for marking an agency as a Superagency and/or adding/removing a `Superagency` system. When a user marks the agency as a Superagency by clicking on the checkbox, the `Superagency` system will automatically be added the the list of systems for the agency. When a user unchecks the `Superagency` checkbox, the `Superagency` system will be removed. Similarly, when you add or remove a superagency system, the corresponding checkmark will toggle checked/unchecked.
Note: I realized we didn't have constants for agency systems, so I added an enum and updated all dependent components - hence the large # of files changed. Feel free to just focus on the `AgencyProvisioning.tsx` file as the other 24 files are type name updates.
Much easier to show visually than describe in …

[Publisher] Admin Panel: Agency Provisioning - Superagency System Addition/Removal (6/n)

---

publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
publisher/src/components/AdminPanel/types.ts
publisher/src/stores/AdminPanelStore.ts

Sends over `user_account_id` in admin panel requests to create new users ([companion BE PR](https://github.com/Recidiviz/recidiviz-data/pull/26167))

include `user_account_id` in request when creating new users from the admin panel

---

common/components/DelayedRender/DelayedRender.tsx
common/components/DelayedRender/index.ts
publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/AdminPanel.test.tsx
publisher/src/components/AdminPanel/AdminPanel.tsx
publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
publisher/src/components/AdminPanel/InteractiveSearchList.tsx
publisher/src/components/AdminPanel/UserProvisioning.tsx
publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
publisher/src/components/AdminPanel/types.ts
publisher/src/stores/AdminPanelStore.ts

This implementation allows users to quickly create a new user _while_ in the middle of creating an agency - and vice versa - quickly create a new agency _while_ in the middle of creating a new user. There are some edge cases that still need to be tested for (e.g. the auto adding of CSG members when creating a new agency, etc.) - but this works well so far in local development. Will do a more thorough testing in staging, but mostly trying to get the foundation in for now. Hopefully this makes things a bit easier for us when provisioning new users and agencies - but if it ends up being a pain, it's easy enough to strip out.
Demo (user provisioning):
https://github.com/Recidiviz/justice-counts/assets/59492998/e58bce4f-8998-4b9a-af2e-cd5910b644af
Demo (agency provisioning): …

[Publisher] Admin Panel: Create User/Agency from opposite flows

---

publisher/src/components/Menu/Menu.tsx
publisher/src/components/Settings/AccountSettings.tsx
publisher/src/stores/AdminPanelStore.ts

Fixes a crash that happens when logging into Publisher when your name set as only spaces. In addition to that, adds extra trimming of leading spaces (in admin panel and Publisher account settings) and a bit of logic to prevent users from emptying out the name & email fields in Publisher account settings (which is already in place in admin panel). Thanks to Forrest for uncovering this weird edge case.
I tested this manually by adjusting my name to only spaces via Auth0 (no crash when logging in), and trying to empty the name and email fields in Publisher account settings (reasonably difficult to empty) and the name field in the admin panel (email is not editable at this time - so at creation time, this isn't necessary because the email is being validated).
**This box MUST be checked by the …

[Bug][Publisher] Admin Panel: Playtesting Followup - Fix crash edgecase when username is a string full of spaces

---

common/components/Toast/Toast.ts
publisher/src/components/AdminPanel/AgencyProvisioning.tsx

Removes the "(required)" text from the `Search State` input field in Agency Provisioning. No code changes at all - I just moved the search boxes outside of the `<Styled.InputLabelWrapper></Styled.InputLabelWrapper>` so the `(required)` CSS targets the labels properly.

[Publisher] Admin Panel: Playtesting Followup - Remove "(required)" from state search box in Agency Provisioning modal

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx

Fixes Select All bug in the Agency Provisioning modal when trying to add users. Previously, it showed that it was adding users, but never sent those added users to the backend. This adjustment ensures that the "Select All" button adds those users to the final list AND designates the appropriate default role for each user.
https://github.com/Recidiviz/justice-counts/assets/59492998/5dde545e-ecce-40ee-b857-0b112953f02f

[Publisher] Admin Panel: Playtesting Followup - Fix Select All users bug in Agency Provisioning modal

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/stores/AdminPanelStore.ts

Refetches users and agencies when a change has been made to a superagency selection or a list of child agency - since changes to either will require other agency objects to update reflecting the relationship. Instead of having the FE coordinate all of those individual changes, we can refetch a new list of agencies after saving which will give us all of the updated relationships. (Thank you Lili for the idea to isolate the refetching only when these changes are made!)
I don't think we necessarily need to refetch users - I just included them here because I figured why not get a new list of users to keep the updates in sync. LMK if you think it's better to just refetch a list of agencies.
https://github.com/Recidiviz/justice-counts/assets/59492998/62bab8eb-a067-41e6-9fbf-dfece665dcb9
**This …

[Publisher] Admin Panel: Playtesting Followup - Refetch users and agencies when a change has been made to a superagency/child agency selection

---

publisher/src/components/Menu/Menu.styles.tsx
publisher/src/components/Menu/Menu.tsx

Adds agency name header in the top navigation/header bar for users who belong to only one agency. 
Before:
After:

[Publisher] Admin Panel: Playtesting Followup - Add agency name header for single agency users

---

publisher/src/components/DataViz/MetricsDataChart.tsx

When I was poking around the Explore Data page to resolve a separate issue, I noticed that the "Go to Metric Settings" link at times navigated to a Page Not Found component - and other times go to the proper metric configuration component. 
This is due to the `settingsSearchParams` not being updated when the URL params are being set, thus sending `undefined` for the `system` param and `metric` param (i.e. it navigates to `http://.../agency/147/metric-config?system=undefined&metric=undefined` which shows the Page Not Found component). 
If you refresh the Explore Data page and go to those links, it will work because the `settingsSearchParams` picks up on the already set URL params (e.g. `http://.../agency/147/data?system=superagency&metric=superagency_funding&...`) and will navigate to …

[Publisher][Bug] Explore Data: Fix broken "Go to Metric Settings" link

---

publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/AdminPanel.test.tsx
publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
publisher/src/stores/AdminPanelStore.test.tsx

Adds indicator in the Agency Provisioning Overview cards for child agencies. 

[Publisher] Admin Panel: Playtesting Followup - Add indicator on the agency overview cards for child agencies

---

publisher/src/components/AdminPanel/UserProvisioning.tsx

No-op nitty change - just moving the position of the list of agencies to select from box to above the buttons instead of below. It feels a bit more natural this way.

[Publisher] Admin Panel: Quick UI adjustment of add agencies list position

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
publisher/src/components/AdminPanel/UserProvisioning.tsx
publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
publisher/src/components/AdminPanel/types.ts
publisher/src/stores/AdminPanelStore.ts

Empties out the search input in the overview pages after saving. 
While I was doing this, I ran into a "off-by-one-render" (for lack of a better phrase) bug in the overview pages and realized that I had fallen into an overcomplicated state w/ mobx and local state (search + filtering logic) that could be dramatically simplified. A nice benefit of this small refactor is that it also takes care of the feedback of retaining the value in the searchbox while checking/unchecking the filter checkboxes in the agency provisioning overview - and everything searches and filters as expected.
https://github.com/Recidiviz/justice-counts/assets/59492998/e279d3e7-e26e-4f3f-9f51-d8952803687d
If anyone is super curious - I'm happy to sync with you & dive deeper into the mobx and local state adjustments! …

[Publisher] Admin Panel: Playtesting Followup - Empty search input in overview pages after saving & refactor filtering logic

---

common/components/RadioButton/RadioButtonsWrapper.tsx
publisher/src/components/MetricsConfiguration/MetricAvailability.tsx

Prevents supervision + subsystems agencies from entering a state where both combined and disaggregated metrics are enabled.
https://github.com/Recidiviz/justice-counts/assets/59492998/2de1c109-47dd-404c-a770-be8ec9067546
Tooltips (all copy improvement suggestions welcome):
Closes [#25629](https://github.com/Recidiviz/recidiviz-data/issues/25629)

[Publisher] Prevent agencies from being able to have supervisions metrics that are both combined and disaggregated

---

publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx

I noticed that the link to the **Live Dashboard** in the Agency Provisioning Overview page was not working (or even hovering). I realized that the `LinkToDashboard` component relies on the `agencyName` from the logged in user's list of agencies - so if the user isn't tied to the agency, the `userStore.getAgency(agencyId)?.name` will return `undefined` and the **Live Dashboard** link on the cards just appears as text. 
This adjustment allows the `LinkToDashboard` component to accept a `name` prop and use that if/when provided. From the Agency Provisioning Overview component, we can pass in the agency's name and get the proper linking to the the appropriate dashboard.
This was simple to test as the link and hover interactions began to appear after this change.
**This box MUST be checked by …

[Publisher] Admin Panel: Quick bug fix with link to Live Dashboard

---

common/components/ToggleSwitch/ToggleSwitch.styles.tsx
common/components/ToggleSwitch/ToggleSwitch.tsx
common/components/ToggleSwitch/types.ts
publisher/src/components/Settings/AgencySettings.tsx
publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
publisher/src/stores/AgencyStore.ts

Milestone 4 of the Publisher Notifications project, implementing the subscribe/unsubscribe toggle
https://github.com/Recidiviz/justice-counts/assets/19961693/7587f21c-bd78-469e-b425-f92e4ee7861a
Closes #1056

toggle in agency settings to turn unsubscribe / subscribe to email

---

publisher/src/components/Home/Home.test.tsx
publisher/src/components/Home/TaskCard.tsx
publisher/src/components/Home/types.ts
publisher/src/stores/HomeStore.test.tsx
publisher/src/stores/HomeStore.ts

P0 of the Publisher Notifications project requires that we change the homepage card wording for uploading for a metric.  Title should become “Upload {metric name} Metric” and the “Upload Data” cta should become “Bulk Upload”
Closes  #1129

[Justice Counts] update task cards for uploading missing metrics

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx

Auto-select Supervision sector when any supervision subpopulation sector is selected and auto-deselect subpopulation sectors when Supervision sector is deselected.
Currently, when creating/editing an agency in the admin panel, a user is able to select supervision subpopulations sectors without the selection of the Supervision sector and save. This solution prevents that by automatically handling these supervision selections and avoiding a state where a user has only supervision subpopulation sectors and no Supervision sector.
https://github.com/Recidiviz/justice-counts/assets/59492998/271d263f-3f4f-4ffe-8165-a15f9ac3c8b3
Contributes to #1135
These boxes should …

[Publisher] Admin Panel: CSG Followups - Ensure supervision subpopulation sectors cannot be selected without Supervision sector also being selected

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx

Exclude superagency sector from consideration when determining whether or not a user has sectors selected.
Currently, when creating/editing an agency, a user is able to check the **Superagency** checkbox (which auto-adds the Superagency sector) and the `hasSystems` logic registers that as a user having a minimum of 1 sector and allows you to save with only a Superagency sector (provided all other required fields are filled out). This adjustments prevents a state where an agency can only have a Superagency sector by requiring a user to select an additional sector before being allowed to save.
Note: I also noticed a small bug in the "Select All" and "Deselect All" logic for selecting sectors that I included here - when deselecting all, the Superagency sector is removed as well despite still …

[Publisher][Bug] Admin Panel: Exclude superagency sector from consideration when determining whether or not a user has sectors selected

---

publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx

Adds link to Publisher in the agency cards in the `AgencyOverview` component.
https://github.com/Recidiviz/justice-counts/assets/59492998/f4ad30b6-63f3-4f71-9c72-fd5943eb36b7
Contributes to #1135

[Publisher] Admin Panel: CSG Followups - Add link to Publisher in agency cards

---

publisher/src/components/DataUpload/InstructionsTemplate.tsx
publisher/src/components/DataUpload/UploadFile.tsx

Fix superagency double upload bugs by removing special filtering in `UploadFile` component.
Two bugs surfaced were:
* When you upload a file, the /spreadsheets endpoint is called twice by the FE
* When you upload a successful file (no errors/warnings) as an agency with Superagency + 1 other sector, you bypass the SystemSelection component
Both bugs only appeared for agencies with Superagency + 1 other sector, the other multi-sector agency (Supervision & Prisons) we tested did not experience these bugs. Both bugs point to a root issue of filtering out the Superagency sector from the list of the users agency in the `UploadFile` component (child of `DataUpload` component).
The filtering taking place only in the `UploadFile` component throws off the parent `DataUpload` component because it's …

[Publisher][Bug] Fix superagency double upload bugs by removing special filtering in `UploadFile` component

---

agency-dashboard/src/stores/AgencyDataStore.ts

Hides disabled metrics in Agency Dashboards by filtering them out of the `metrics` list before the list is set in the `AgencyDataStore`.
The came up when CSG had a Prisons & Supervision agency mistakenly published datapoints for the Prisons metrics that were meant to be for the Supervision sector. Adjusting the frequency and disabling the Prisons metrics was futile because the published datapoints don't go away. This change helps provide a bit more control for agencies who need to remove a metric from dashboards. In the above scenario - the agency's datapoints were clean up (thank you @morden35), and they will now be able to disable the Prisons metrics that they are not currently reporting and hide that from their Dashboards.
https://github.com/Recidiviz/justice-counts/assets/59492998/1ce2 …

[Agency Dashboards] Hide disabled metrics

---

publisher/src/pages/Reports.tsx

Groups non-calendar year annual records under the year that matches their end year.
Since we've adjusted the reference year for non-calendar year records/metrics to be their ending year, this is the last collateral adjustment that needs to happen to honor this in the UI. Currently, the records overview page takes a list of records, sorted by their year, and renders them in a linear way dropping report year markers in the UI as the list of records transitions from year to year.
In order to group non-calendar year records under their respective ending year, we need to adjust the structure of the records list and the rendering structure to accommodate this. If we group the list of records by their year - and while doing so, bucket non-calendar year records to their respective end year …

[Publisher] Group non-calendar year records under the year that matches their end year

---

publisher/src/components/DataUpload/InstructionsTemplate.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx

Rename all references to the spreadsheet templates in the Bulk Upload page from "example(s)" to "template(s)".
View changes here: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/
Closes [#26334](https://github.com/Recidiviz/recidiviz-data/issues/26334)

[Publisher] Rename Bulk Upload 'example(s)' to 'template(s)'

---

agency-dashboard/src/Home/Home.tsx
publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx

Fix encoding of agency names when linking to dashboards by using the native `encodeURI` function instead of the helper method `slugify`'s strategy of replacing spaces with hyphens.
This resolves an issue CSG noticed with agencies that have hyphens in their name. Currently, the FE uses a helper method called `slugify` that replaces spaces with hyphens, and the BE decodes the 'slugified' agency name by replacing the hyphens with spaces. Instead, the FE can use the `encodeURI` which will naturally replace spaces with a `%20` and the BE can decode encoded URIs and naturally decode a `%20` into a space and leave hyphens alone.
https://github.com/Recidiviz/justice-counts/assets/59492998/eae3c0aa-47bd-48c2-8b8e-e94218bcdd92
Closes #1144
**This box MUST be checked by the submitter prior to …

[Publisher][Bug] Fix encoding of agency names when linking to dashboards

---

common/types.ts
publisher/src/components/Reports/CreateReport.test.tsx
publisher/src/components/Settings/AgencySettings.tsx
publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx

Changes before launch, updates copy for email subscribe / unsubscribe toggle as well as the access to the toggle. Superagencies and child agencies will not have a toggle on their Agency Settings page because that functionality has not been implemented yet. 
https://github.com/Recidiviz/justice-counts/assets/19961693/3984118c-0f31-43f0-8d9b-ee94908b477e
Closes #26282, #27025

[Justice Counts] update toggle copy and access

---

publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
publisher/src/components/assets/icons8-trash.svg
publisher/src/stores/AdminPanelStore.ts

Add functionality for deleting users from within the admin panel.
Using @brandon-hills' new DELETE endpoint ([reference](https://github.com/Recidiviz/recidiviz-data/pull/26773)), I added a little trash icon on all the cards in the `UserProvisioningOverview` page that appears on hover. When a user clicks this icon, a warning modal appears asking the user to confirm this action. Once confirmed, a call is sent to the delete users endpoint and upon a successful response, the UI updates the list of users with the desired user removed.
https://github.com/Recidiviz/justice-counts/assets/59492998/33a486a8-730b-4fb2-9ae4-c51e0668a55b
Note: for the error condition, I just negated the `response.status === 200` conditional, so it will still delete successfully, but just demo the UI state when it …

[Publisher] Admin Panel: Add functionality for deleting users

---

publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/stores/AdminPanelStore.ts

Adds a way to trigger the copying of superagency metric settings to child agencies in the UI.
Within an open Agency Provisioning modal, and after a user has... 
1. Checked the `Superagency` box
2. Selected at least one non-Superagency sector, and
3. Selected at least one child agency
... there will be a new checkbox available labeled "Copy metric settings to child agencies". Checking this input will display a warning message that alerts the user that this action cannot be undone, and what to expect after clicking "Save".
Once the user clicks "Save", there will be a call to the `copy_metric_config_to_child_agencies` endpoint which will trigger the Cloud Run job that copies the metric settings and sends a confirmation email.
Demo:
https://www.loom.com/share/a2b24c6e0dac4dcd80bea7c34b302b2e …

[Publisher] Admin Panel: Add a FE trigger for the copying of superagency metric settings to child agencies process in the UI

---

publisher/src/components/Auth/AuthStore.ts
publisher/src/index.tsx

Temporarily silencing Sentry so we don't receive a bunch of error alerts working locally until I can investigate and tune the tracing.
Contributes to #1172

[Publisher] Temporarily silencing Sentry

---

publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/AgencyProvisioning.tsx

Update copy for the copy-superagency-metric-settings checkbox and warning message to add more specificity that the copying process will overwrite existing child agency settings and that it will copy across all sectors.
(@morden35 - I also updated the styling for the warning message to make it pop out more - lmk what you think!)
Closes #1178

[Publisher] Admin Panel: Update copy for the copy-superagency-metric-settings checkbox and warning message to add more specificity

---

publisher/src/stores/MetricConfigStore.tsx

Fix Race & Ethnicities grid displaying and saving incorrect enabled/disabled dimension states when set for the first time.
Matt surfaced an issue where when setting the Race & Ethnicities dimensions for the first time via Metric Settings page, the saved results do not align properly with the expected output based on the user's input in the R&E modal form. This seems to only happen when the R&E dimensions have never been set before and are being set for the first time.
When doing a comparison to decide whether or not a particular dimension needs to be updated, It appears that the FE is not properly handling the BE sending `null` for these dimensions' initial state, and it's stumbles when it does a comparison of the current state (initially `null`) against the what the dimension state …

[Publisher][Bug] Fix Race & Ethnicities grid displaying and saving incorrect enabled/disabled dimension states when set for the first time

---

common/package.json
yarn.lock

Reverts Recidiviz/justice-counts#1200 as it required a different node version than the one we have configured - and causing an issue with our staging deploy:
```
Step #1: [2/4] Fetching packages...
Step #1: error eslint-plugin-storybook@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.20.2"
Step #1: error Found incompatible module.
Step #1: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Step #1: error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/kaniko-project/executor:v1.8.1" failed: step exited with non-zero status: 1
```

Revert "Bump eslint-plugin-storybook from 0.6.13 to 0.8.0"

---

.github/workflows/ci.yml
agency-dashboard/package.json
common/package.json
publisher/package.json

Update CI to fail frontend test when incompatible node versions are detected in a new package upgrade by explicitly setting the node version in the `package.json` and updating the `ci.yml` file to use the same node version.
Last week, HelperBot auto-merged in a package that required `node` version `>= 18`, which caused a staging deploy attempt to fail with the following error:
```
Step #1: [2/4] Fetching packages...
Step #1: error eslint-plugin-storybook@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.20.2"
Step #1: error Found incompatible module.
Step #1: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Step #1: error building image: error building stage: failed to execute command: waiting for process …
```

Update CI to fail frontend test when incompatible node versions detected in a new package upgrade

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx

Fix crash when a user has no role set in the Agency Provisioning Team Member & Roles tab by handling the case when `member.role` is `undefined`/`null` and passing in an empty string to `removeSnakeCase`, if so.
https://github.com/Recidiviz/justice-counts/assets/59492998/f793ba4d-af9e-4129-a40c-c177afb3ff46
Closes #1206

[Publisher][Admin Panel][Bug] Fix crash when a user has no role set in the Agency Provisioning Team Member & Roles tab

---

publisher/src/components/Settings/AgencySettings.tsx

This PR un-gates email subscription toggle for superagencies, now that publisher notification emails are supported for them.
Note: child agencies will not receive any upload notifications, so the toggle will not appear on the agency settings page for child agencies. 
Here's a reminder of what the toggle looks like! I tested locally to confirm that the toggle appeared for a superagency but not a child agency. 
Closes #1222 

[Justice Counts] un-gate emails subscription toggle for superagencies

---

common/components/CheckboxOptions/CheckboxOptions.styles.tsx
common/components/CheckboxOptions/CheckboxOptions.tsx
common/components/TabbedBar/TabbedBar.styled.tsx
publisher/src/components/DataViz/MetricsDataChart.tsx
publisher/src/components/MetricsConfiguration/Configuration.tsx
publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx
publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx
publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.styled.tsx
publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.tsx
publisher/src/components/Settings/utils.ts

Update Supervision subpopulation layout and behavior in Metric Settings as outlined in [Figma designs](https://www.figma.com/file/dvX3yg7FMGJSWFaqHWrWgQ/Justice-Counts-Publisher?type=design&node-id=10616%3A14191&mode=design&t=Cn4CLfBljs6GVvji-1) 
Instead of separate Metric Settings views for each supervision subpopulation type, now there is one view for configuring both Supervision and subpopulation metrics. 
Quick tour:
https://github.com/Recidiviz/justice-counts/assets/59492998/dfa6cf94-908f-463f-b2d9-8c5cd362af62
[Note: it looks like there's a bug that appears in our existing Metric Settings page that I just noticed recording this demo when you disaggregate a supervision metric, the default frequency is set to "Annual" for the subpopulation types with `starting_month` set to `null` - …

[Publisher][Design Updates] Update Supervision subpopulation layout and behavior in Metric Settings

---

publisher/src/components/HelpCenter/HelpCenterGuideLayout.tsx

Fix Help Center `pathToGuide` route string to allow relevant guides to link properly.
Demo (`main` branch -> `mahmoud/bug-help-center-links` branch):
https://github.com/Recidiviz/justice-counts/assets/59492998/ee1ef0a5-248e-46c4-88b0-ad253d6f5b45

[Publisher][Bug] Fix Help Center routing bug to allow relevant guides to link properly

---

publisher/src/components/MetricsConfiguration/MetricAvailability.tsx

Adjust "Starting Month" rendering conditional to read from `customOrDefaultFrequency` instead of `customFrequency`.
This is a companion to Nichelle's PR [#28018](https://github.com/Recidiviz/recidiviz-data/pull/28018). Prior to this FE PR - despite Nichelle's BE changes sending the correct starting month for the disaggregated supervision subpopulation systems, it looks like the FE is still blocked on rendering the Starting Month section because it's only reading from `customFrequency` (long story short - it looks like on the FE, any manual updates to the frequency gets saved in the store as `customFrequency` - and we've gotten away with this because the supervision subpopulation behavior is the only thing that takes a metric from a `null` state to pre-setting these values - everything …

[Publisher] Metric Settings - Adjust "Starting Month" section to read from `customOrDefaultFrequency` instead of `customFrequency`.

---

publisher/src/App.tsx
publisher/src/components/Loading/Loading.styles.tsx
publisher/src/components/Loading/LoadingError.tsx
publisher/src/stores/UserStore.ts

Improve handling of /users PUT errors by displaying a generic error page.
Currently, when the `updateAndRetrieveUserPermissionsAndAgencies` errors (indicating something went wrong with the `/api/users` request), it displays the "No agencies found" page because the `initialAgency` in `App.tsx` ends up being `undefined` as a consequence of the above method erroring. The problem is - this isn't an accurate error page/message for users in this state. 
Instead, we can update the behavior to show a generic error page when `updateAndRetrieveUserPermissionsAndAgencies` errors:
Closes #1114

[Publisher] Improve handling of `/users` PUT errors by displaying a generic error message

---

publisher/src/components/DataViz/MetricsDataChart.tsx

Added two download buttons to Explore Data page …

[Publisher] Add two download buttons to Explore Data page

---

publisher/src/components/MetricsConfiguration/MetricAvailability.tsx

Moves "Disaggregated by Supervision Type" tooltip copy to description body of "Metric Disaggregation" for clarity as suggested by Matt from CSG. 

[Publisher] Metric Settings: Moves "Disaggregated by Supervision Type" tooltip copy to description body of "Metric Disaggregation"

---

publisher/src/components/Settings/AgencySettings.styles.tsx
publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
publisher/src/stores/AgencyStore.ts

Implements the frontend for the e-mail notification offset date picker by adding an input with copy that displays the offset date.
I included an error state for when the user input is out of bounds and cleaned up the copy before the date picker a little bit. This was done consistent with the current design and not in the style of the upcoming Agency Settings design update so things don't look super off.
https://github.com/Recidiviz/justice-counts/assets/59492998/1e21cba3-492a-4b0b-9048-a4c79047b68c
Closes [#27978](https://github.com/Recidiviz/recidiviz-data/pull/27978)

[Publisher] Agency Settings: Adds offset date picker for email notifications

---

agency-dashboard/src/stores/AgencyDataStore.ts
common/components/DataViz/CategoryOverviewBreakdown.tsx
common/components/DataViz/CategoryOverviewLineChart.tsx
common/components/DataViz/types.ts
common/components/DataViz/utils.ts
common/stores/BaseDatapointsStore.ts
common/types.ts
publisher/src/components/DataViz/ConnectedDatapointsView.tsx
publisher/src/components/DataViz/MetricsDataChart.tsx
publisher/src/stores/DatapointsStore.ts
publisher/src/stores/ReportStore.ts
publisher/src/stores/RootStore.ts

Display metric datapoints that match currently set frequency for each metric in the data charts in both Publisher & Agency Dashboard.
Play with it here (would love a quick sanity check if folks have bandwidth): 
- Publisher: https://mahmoudtest---publisher-web-b47yvyxs3q-uc.a.run.app/
- Agency Dashboard: https://mahmoudtest---agency-dashboard-web-b47yvyxs3q-uc.a.run.app/
Quick visuals -
Publisher:
https://github.com/Recidiviz/justice-counts/assets/59492998/333b954a-8ff5-4786-ad6e-2737c4f1a7b2
Agency Dashboard:
https://github.com/Recidiviz/justice-counts/assets/59492998/a1330d21-940d-4471-a7f4-8f5225372f88
Closes #1202 
These boxes should be checked by reviewers …

[Publisher + Agency Dashboard] Data Charts: Display metric datapoints that match currently set frequency for each metric

---

common/package.json
yarn.lock

Reverts Recidiviz/justice-counts#1261 due to suspected compile error. This package was amongst the ones that was merged in yesterday and possibly broke the playtesting deploys.

Revert "Bump @babel/preset-env from 7.22.20 to 7.24.3"

---

agency-dashboard/src/App.tsx
agency-dashboard/src/Home/Home.tsx
agency-dashboard/src/Protected/Protected.tsx
agency-dashboard/src/stores/AgencyDataStore.ts
publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
publisher/src/components/Menu/Menu.tsx

This change is a prerequisite for supporting non-unique agency names. The agency dashboard URLS (and the respective queries to the BE) assume that all agencies have unique names. I update the URLs so that they include the agency IDs, which enables the BE to query by agency ID. This way, agencies can have the same name but distinct dashboard URLs. 
The following video is from me playtesting this branch with my [BE branch](https://github.com/Recidiviz/recidiviz-data/pull/28705)! 
https://github.com/Recidiviz/justice-counts/assets/19961693/e51151a4-155f-44b3-b50f-131716325b3a
Closes #1284 

[Justice Counts] Update dashboard URLs to have agencyID 

---

agency-dashboard/src/AgencyOverview/AgencyOverview.tsx

Fix linking to Category Overview page from an agency's main dashboard page by including the agency `id` in the path.
Tested by running locally against staging env and ensuring linking to the Category Overview page works as intended.
Main vs this branch:
https://github.com/Recidiviz/justice-counts/assets/59492998/750fee9a-c075-4632-9a38-6eacea40960f
Closes #XXXX

[Agency Dashboard][Bug] Fix linking to Category Overview page

---

publisher/src/stores/AdminPanelStore.ts

Replace curly apostrophes (`’`) with straight apostrophes (`'`) in agency names upon creation/editing in the admin panel.
I created a new agency that contained curly apostrophes within the agency name. The agency was properly saved in the database with straight apostrophes. I also attempted to edit the agency name and add in a curly apostrophe. I confirmed that this was saved with the expected straight apostrophe.
|-----------------------------	|------------------------------------------------------------------------------------------------------- …

[Justice Counts] Replace curly with straight apostrophe in agency name

---

publisher/src/components/MetricsConfiguration/MetricAvailability.tsx

Disable Supervision Subpopulation checkboxes in Metric Settings for READ ONLY users.
Read Only vs Non-Read Only:
| Type: …

[Publisher] Disable Supervision Subpopulation checkboxes in Metric Settings for READ ONLY users

---

publisher/src/components/Reports/DataEntryForm.test.tsx
publisher/src/components/Reports/DataEntryFormComponents.tsx
publisher/src/stores/FormStore.test.tsx
publisher/src/stores/FormStore.ts

Remove additional context logic from FormStore and DataEntryFormComponents as contexts are no longer handled by the record page.
There was a bug reported in staging for agency 11 where opening up a monthly record resulted in a crash. The crash was a result of the record page validation of previously saved inputs attempting to delete an error on the `metricsValues` object (in the FormStore - this object keeps track of the metric values and error state for each metric value) for a metric that did not exist in this object.
How is this happening? 
I'm not entirely sure when this happened or if it's always been this way, but it appears that when you add a value to the additional context field in the Metric Settings definition for a top-level metric, save it, and then delete the value and save …

[Publisher][Bug] Remove additional context logic from FormStore and DataEntryFormComponents

---

publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx

Fix metric definitions display for agencies with supervision + other non-supervision sectors with similar metrics (e.g. Funding, Staff, etc.) that are disaggregated by subpopulation in the supervision sector.
Huge shout out to @lilidworkin's playbook, as I stumbled into this while testing another PR going through the various agencies. 
This one is super sneaky... If you are in an agency that has, for example, Law Enforcement & Supervision sectors - both of which have a Funding metric - and within the Supervision sector, you disaggregate the Funding metric by subpopulations; when you look at the Funding metric's definitions within the Law Enforcement sector, you'll unfortunately see the list of definitions for the first disaggregated supervision subpopulation, and NOT the list of Law …

[Publisher][Bug] Fix metric definitions display for agencies with supervision + other non-supervision sectors

---

.github/workflows/auto-merge-dependabot.yml

Exclude @babel packages from dependabot auto-merge. 
This one is tough to test because `uses: dependabot/fetch-metadata@v1` will throw an error if the PR's author is not `dependabot`. So, I passed in a string in lieu of `steps.metadata.outputs.dependency-names` with a comma separated list of dependency names - just to test the `if` and `grep` logic - and it properly skipped the auto-merge steps.
It won't hurt anything if this doesn't work, so I'm open to trying it and waiting for a dependabot `babel` package, if folks are OK with that. I've searched high and low for a way to simulate or manually trigger a dependabot package upgrade PR, to no reasonable avail (there was a discussion of a potential way to trigger it via an endpoint, but it didn't seem worth diving into that rabbit hole for …

Exclude @babel packages from dependabot auto-merge

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/components/AdminPanel/UserProvisioning.tsx
publisher/src/stores/AdminPanelStore.ts

This update updates the front-end functionality to refetch agency data after any updates to an agency via the admin panel. This ensures that any changes made to a super agency are accurately reflected in its child agencies ([BE PR](https://github.com/Recidiviz/recidiviz-data/pull/31147/files)).
https://github.com/Recidiviz/justice-counts/assets/19961693/2c566fbf-fd13-4f5b-bb18-17ba491c552b

[Publisher] refetch agencies every time that they are edited in the admin panel

---

publisher/src/components/Reports/CreateReport.styled.tsx
publisher/src/components/Reports/CreateReport.tsx
publisher/src/utils/dateUtils.ts

This change allows users to select starting month when creating an annual record and also updates dropdowns styling.
| Type: …

[Publisher] Allow users to select starting month when creating an annual record

---

common/utils/downloadHelpers.ts

Excluded `filenameWithAgencyName` from url in `downloadFeedData` …

[Publisher] Fix Download Data downloading blank CSVs in Explore Data page

---

agency-dashboard/src/Protected/Protected.tsx
agency-dashboard/src/stores/AgencyDataStore.ts

Updates URL for published_data so that the FE an correctly fetch data to render the dashboard pages. I tested this manually by deploying the changes to staging with the BE changes and visiting the dashboard for various agencies. 
Closes #1444

[Agency Dashboard] Remove slug from published data url for agency dashboards

---

common/components/DataViz/BarChart.tsx
common/components/DataViz/MetricsCategoryBarChart.tsx

Fix react/no-unstable-nested-components (Do not define components during render...) lint errors by defining the `CustomYAxisTick` component outside of the main component render. …

[Bug Bash][Common] Fix react/no-unstable-nested-components lint errors 

---

publisher/src/components/DataUpload/DataUpload.tsx
publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx
publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
publisher/src/components/DataUpload/utils.ts

When testing out the new WorkbookStandardizer code, I noticed a message that reads `This metric is disabled. If you would like to enable it, visit the Metric Configuration page.` for supervision metrics. Though this may be true, the Supervision Combined metric is disabled because the agency is reporting by supervision sub-system, it's confusing because there are still sheet errors that the user needs to address. We cannot group these errors by supervision subsystem because they are sheet wide and none of the data can be ingested.
I've added some logic to remove that message when displaying sheet metrics for supervision uploads _if there are errors._ 
These boxes …

[Publisher] Remove Disabled Metric Message and Show Warning in Alerts When Showing Supervision Sheet Errors

---

common/components/DataViz/DatapointsView.tsx

Updated breakdown view behavior according to task description: 
> If a user is in a breakdown view for metric A and switches to metric B, we could show them the same breakdown if it exists in metric B, otherwise we show them the breakdown metric that is NOT the Biological Sex or Race Ethnicity breakdown. …

[Publisher] Update breakdown view behavior on Explore Data page

---

publisher/src/components/DataUpload/SpreadsheetReview.tsx
publisher/src/stores/ReportStore.ts

**Context**: Matt reported that when uploading 0 values in a sheet via Bulk Upload, these values were not displayed on the Review Data page. Instead, the system acted as if no data had been supplied. 
BEFORE
**Investigation**: After investigating, I confirmed that while the backend correctly saved the 0 values, the frontend was filtering them out. The frontend logic treated 0 values as if they were missing or undefined, leading to them being excluded from display.
**Fix**: I updated the frontend filtering logic to ensure that only undefined values are filtered out. This allows 0 values to be displayed properly on the Review Data page, as they are valid data points. I tested locally by creating the super/ child agencies in my local environment and tested with the sheet Matt supplied. …

[Publisher] Don't filter out 0 values in `Review Data` page

---

publisher/src/components/AdminPanel/AgencyProvisioning.tsx

Alternative solution to #1528 - this is my preferred solution. Explained more here: 
https://www.loom.com/share/b657651b698b4430ac2ce3711b755b35
Fix bug where adding team members to the admin panel clears out all other team members due to recent optimizations of fetching team members separately.
This issue was raised by CSG members who noticed that adding a team member to an agency resulted in clearing out all other team members from the agency aside from the one recently added. Because we now fetch team members separately and ONLY when an agency card is clicked vs. before where they were populated for each agency immediately after the admin panel loads, we need to await the fetch of team members before updating them in the admin panel so all references to the team members will be the …

[Publisher][Bug] Alternate Solution: Fix bug where adding team members to the admin panel clears out all other team members

---

publisher/src/stores/AdminPanelStore.ts

Fix admin panel loading on Create User/Agency flows. This is caused by us initializing the loader to `true` which is not necessary since the `fetchAgencyTeam` and `fetchUserAgencies` agencies already set it to `true` before fetching (L218 and L291), and update it to `false` after fetching. 
Tested this locally w/ staging environment as the backend. Will deploy to testing if folks want to play with it - you can do a side-by-side check of current staging vs. the playtesting link (clicking on either Create User/Agency). …

[Publisher][Admin Panel][Bug] Fix admin panel loader

---

common/types.ts
publisher/src/components/AgencySettings/AgencySettingsJurisdictions.tsx

These changes support sending GEOIDS to the BE instead of FIPS for the Agency Jurisdiction feature as well as the jurisdiction search with geoids. ([BE PR](https://github.com/Recidiviz/recidiviz-data/pull/35300))
https://github.com/user-attachments/assets/2873ea04-ca49-4005-a201-fd99dc177746

[Publisher] Add GEOID data source and Update Jurisdiction Type

---

publisher/src/components/AdminPanel/AdminPanel.styles.tsx

Tweak team members card and modal sizes to fit cards better in smaller screens …

[Publisher][Admin Panel] Fit 3 team member cards in a row

---

common/components/CheckboxOptions/CheckboxOptions.styles.tsx
common/components/CheckboxOptions/CheckboxOptions.tsx
publisher/src/components/AgencySettings/AgencySettingsDataSource.tsx

Fixed issues and bugs of data source questions …

[Publisher][Agency Settings] Fix data source questions bugs

---

common/components/CheckboxOptions/CheckboxOptions.tsx
common/types.ts
publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
publisher/src/components/MetricsConfiguration/types.ts
publisher/src/mocks/HomeMocksHelpers.ts
publisher/src/stores/MetricConfigStore.tsx

Updated metric definitions and checkbox group logic to support radio input …

[Publisher][Metric Settings] Update metric definitions to support radio input

---

publisher/src/components/DataViz/MetricsDataChart.tsx

Fix bug where Explore Data page shows first Combined Supervision datapoints when Supervision sector is disaggregated. Bug was reported by CSG where an agency that has the Supervision sector disaggregated shows a Supervision Combined Funding metric's datapoints by default when first visiting the Explore Data page. This is caused by the current implementation relying on the `system` param which is `undefined` on load and subsequently gets set as the first agency's system instead of the first system with an enabled metric. 
The change proposed here sets the initial search params after initializing the report settings (our current way to infer the enabled/disabled status of a metric for now), which more accurately displays the charts for the first enabled metric and avoids the issue caused by …

[Publisher][Bug] Fix bug where Explore Data page shows first Combined Supervision datapoints when Supervision sector is disaggregated

---

common/components/DataViz/utils.ts

Fixed enabled dimension leaking from another sectors, creating a problem when enabling dimension from sector lead to display the same but disabled dimension from another sector as enabled. …

[Publisher] Fix enabled dimension leaking from another sectors

---

publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx

Fixed "Other" checking and unchecking behavior in Metric Settings page …

[Publisher] Fix "Other" checking and unchecking behavior in Metric Settings

---

common/components/TabbedBar/TabbedBar.tsx
common/components/TabbedBar/types.ts
publisher/src/components/AdminPanel/AdminPanel.styles.tsx
publisher/src/components/AdminPanel/AdminPanel.test.tsx
publisher/src/components/AdminPanel/AgencyProvisioning.tsx
publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
publisher/src/components/AdminPanel/MetricsReportingAgency.tsx
publisher/src/components/AdminPanel/index.ts
publisher/src/components/AdminPanel/types.ts
publisher/src/stores/AdminPanelStore.ts

Added Metrics Reporting Agency feature UI and logic …

[Publisher][Admin Panel] Add Metrics Reporting Agency tab

---

publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx

Fixed metrics definition crash in jails agency …

[Publisher] Fixed metrics definition crash in jails agency
